<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name=description content="<?=(isset($meta['meta_description'])? $meta['meta_description'] : 'Brilio.net')?>" />
        <meta name=keywords content="<?=(isset($meta['meta_keywords'])? $meta['meta_keywords'] : 'Brilio.net')?>" />
        <meta http-equiv="Expires" content="<?= date(DATE_RFC1036) ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="brilio.net">
        <!--SOCMED PROPERTY FB-->
        <meta property="fb:admins" content="1560920678" />
        <meta property="fb:admins" content="1225533149" />
        <meta property="fb:admins" content="1504374378" />
        <meta property="fb:admins" content="550628397" />
        <meta property="fb:pages" content="118943308456455" />
        <meta property="fb:app_id" content="834884736607990" />
        <meta property="og:title" content="<?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?>" />
        <meta property="og:site_name" content="brilio.net" />
        <meta property="og:url" content="<?=(isset($meta['og_url'])? $meta['og_url'] : $this->config['base_url'] )?>" />
        <meta property="og:description" content="<?=(isset($meta['meta_description'])? $meta['meta_description'] : 'Brilio.net')?>" />
        <meta property="og:type" content="article" />
        <meta property="og:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta property="og:image:secure_url" content="<?= (isset($meta['og_image_secure']) ? @$meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <!--SOCMED PROPERTY TWITTER-->
        <meta name="twitter:title" content="<?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?>" />
        <meta name="twitter:description" content="<?=(isset($meta['meta_description'])? $meta['meta_description'] : 'Brilio.net')?>" />
        <meta name="twitter:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@brilionet">
        <meta name="twitter:creator" content="@brilionet">
        <meta name="twitter:domain" content="https://twitter.com/brilionet">

        <title><?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?></title>
        <?php
        if(!empty($amphtml))
        {
            ?>
        <link rel="amphtml" href="<?= $amphtml ?>">
            <?php
        }
        ?>
        <link rel="icon" href="<?php echo $this->config['assets_image_url_v2'] ?>favicon.png" type="image/png" >
        <link rel="stylesheet" href="<?= $this->config['assets_css_url_v2']; ?>bootstrap.css">
        <link rel="stylesheet" href="<?= $this->config['assets_css_url_v2']; ?>main.css?version=<?= $this->config['assets_css_version']; ?>">
        <link rel="canonical" href="<?= $canonical ?>" />
        <?php if ( !empty($meta['meta_alternate']) ): ?>
            <link rel="alternate" href="<?= (isset($meta['meta_alternate'])? $meta['meta_alternate'] : 'm.brilio.net') ?>" />
        <?php else: ?>
            <meta name="robots" content="noindex">
        <?php endif ?>



        <!-- Google Analytics -->
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-77165806-2', 'auto');
           ga('send', 'pageview');

           ga('create', 'UA-71410836-6', 'auto', 'KLNBrilio');
           ga('KLNBrilio.send', 'pageview');

           //ga('create', 'UA-77165806-2', 'auto', 'SUBBrilio'); // old GA UA-61119040-3
           //ga('SUBBrilio.send', 'pageview');
        </script>
        <!-- end Google Analytics -->

        <!-- Chartbeat -->
        <script type='text/javascript'>
            var _sf_startpt = (new Date()).getTime()
        </script>
        <!-- end Chartbeat -->

        <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '213022759033260');
        fbq('track', "PageView");</script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=213022759033260&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Facebook Pixel Code -->
        <script src="<?= $this->config['assets_js_url_v2']; ?>jquery-1.11.2.js"></script>
        <script type="text/javascript">
            var rel_img_url = '<?=$this->config['assets_image_url_v2'] ?>';
        </script>

    </head>
    <body>



    <div class="slide-notifikasi">
        <div class="brilio-container clearfix" style="width: 90%;">
            <span class="slide-title">Would you like to switch to the English version?</span>
            <span class="slide-undo"><a href="<?= $this->config['www_url_en'] ?>">Yes</a></span>
            <span class="slide-close pull-right"><a href="#" class="close-slide-lenguage"><img src="<?= $this->config['assets_image_url'] ?>close-icon.png"></a></span>
        </div>
    </div>
      <!--channel-->
        <div class="list-channel-section">
          <div class="channel-top">
                <ul class="list-channel clearfix">
                    <li class="not-channel channel-left">
                    <span class="middle-channel">KAPANLAGI NETWORK
                        <img src="<?= $this->config['assets_image_url_v2'] ?>kanan.png" class="arrow-channel" />
                    </span>
                    </li><li class="active hidden-xs">
                    <a href="http://www.brilio.net/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Brilio.net');" rel="nofollow">BRILIO.NET</a></li><li class="hidden-xs">
                    <a href="http://www.kapanlagi.com" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Kapanlagi');" rel="nofollow">KAPANLAGI</a></li><li class="hidden-xs">
                    <a href="http://www.merdeka.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Merdeka');" rel="nofollow">MERDEKA</a></li><li class="hidden-xs">
                    <a href="http://www.bola.net/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Bola.net');" rel="nofollow" >BOLA.NET</a></li><li class="visible-lg">
                    <a href="http://www.vemale.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Vemale');" rel="nofollow" >VEMALE</a></li><li class="visible-lg">
                    <a href="http://www.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela');" rel="nofollow" >FIMELA</a></li><li class="visible-lg">
                    <a href="http://www.dream.co.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Dream');" rel="nofollow" >DREAM.CO.ID</a></li><li class="not-channel channel-right">
                    <a href="javascript:void(0);" class="click-more">MORE
                        <img src="<?= $this->config['assets_image_url_v2'] ?>bawah.png" class="arrow-channel arrow-down" />
                        <img src="<?= $this->config['assets_image_url_v2'] ?>atas.png" class="arrow-channel arrow-up" />
                    </a>
                    </li>
                </ul>
            </div>
            <div class="list-channel-more">
                <ul class="list-channel clearfix">
                    <li class="active visible-xs">
                    <a href="http://www.brilio.net" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Brilio.net');" rel="nofollow" >BRILIO.NET</a></li><li class="visible-xs">
                    <a href="http://www.kapanlagi.com" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Kapanlagi');" rel="nofollow" >KAPANLAGI</a></li><li class="visible-xs">
                    <a href="http://www.merdeka.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Merdeka');" rel="nofollow" >MERDEKA</a></li><li class="visible-xs">
                    <a href="http://www.bola.net/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Bola.net');" rel="nofollow" >BOLA.NET</a></li><li class="hidden-lg">
                    <a href="http://www.vemale.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Vemale');" rel="nofollow" >VEMALE</a></li><li class="hidden-lg">
                    <a href="http://www.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela');" rel="nofollow" >FIMELA</a></li><li class="hidden-lg">
                    <a href="http://www.dream.co.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Dream.co.id');" rel="nofollow" >DREAM.CO.ID</a></li><li>
                    <a href="http://www.storibriti.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Storibriti');" rel="nofollow" >STORIBRITI</a></li><li>
                    <a href="http://girl.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela girl');" rel="nofollow" >FIMELA GIRL</a></li><li>
                    <a href="http://www.otosia.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Otosia');" rel="nofollow" >OTOSIA</a></li><li>
                    <a href="http://feed.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Feed.id');" rel="nofollow" >FEED.ID</a></li><li>
                    <a href="http://www.hemat.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Hemat');" rel="nofollow" >HEMAT</a></li><li>
                    <a href="http://www.techno.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Techno.id');" rel="nofollow" >TECHNO.ID</a></li><li>
                    <a href="http://www.sooperboy.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Sooperboy');" rel="nofollow" >SOOPERBOY</a></li><li>
                    <a href="http://www.muvila.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Muvila');" rel="nofollow" >MUVILA</a></li><li>
                    <a href="http://family.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela Family');" rel="nofollow" >FIMELA FAMILY</a></li>
                </ul>
            </div>
        </div>
        <!--endchannel-->
                <!--section-->
        <div class="section">
            <!--header-->
            <div class="header">
                <div class="container">
                    <div class="header-left pull-left">
                        <a href="<?php echo $this->config['base_url'] ?>"><img src="<?= $this->config['assets_image_url_v2'] ?>logo-atas.png" width="190" /></a>
                    </div>
                    <div class="header-right pull-right">
                        <ul class="list-social-bar list-unstyled clearfix">
                            <li><a href="https://www.facebook.com/Brilio-English-165037500527153/?fref=ts&ref=br_tfD" class="fb" target="_blank" onclick="ga('send', 'event', 'Header', 'Button sosmed','Facebook', {'nonInteraction': 1});" ></a></li>
                            <li><a href="https://twitter.com/brilionet" class="twitter" target="_blank" onclick="ga('send', 'event', 'Header', 'Button sosmed','Twitter', {'nonInteraction': 1});" ></a></li>
                            <li><a href="#" class="gplus" onclick="ga('send', 'event',   'Header', 'Button sosmed','G+', {'nonInteraction': 1});"></a></li>
                            <li><a href="https://www.youtube.com/channel/UCjRH2OCntkHDJi0kIX3DZ3w" class="youtube" target="_blank" onclick="ga('send', 'event',   'Header', 'Button sosmed','Youtube', {'nonInteraction': 1});" ></a></li>
                            <li><a href="https://instagram.com/brilionet/" class="instagram" target="_blank" onclick="ga('send', 'event',   'Header', 'Button sosmed','Instagram', {'nonInteraction': 1});" ></a></li>
                            <li><a href="/feed/" class="feed" onclick="ga('send', 'event', 'Header', 'Button sosmed','RSS', {'nonInteraction': 1});" ></a></li>
                            <li><a href="<?php echo str_replace('en/', '', $this->config['base_url']) ?>" class="language" id="switch-language-top"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--endheader-->
            <!--navbar-->
            <div class="navbar-newsite">
                <div class="container">
                    <ul class="list-navbar list-unstyled pull-left clearfix">
                        <li><a href="<?= $this->config['rel_url'] ?>popular/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Popular');" >POPULAR</a></li>
                        <li><a href="<?= $this->config['rel_url'] ?>news/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'News');" >NEWS</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>lol/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'LOL');" >LOL!</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>celebrity/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Celebrity');" >Celebrity</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>figure/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Figure');" >Figure</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>community/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Community');" >Community</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>wow/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Wow!');" >WOW!</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>love/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Love');" >Love</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>tech/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Tech');" >Tech</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>health/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Health');" >Health</a></li>
                        <li class="more-nav" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Button more');" ></li>
                    </ul>
                    <div class="icon-search pull-right"><a href="javascript:void(0);" class="btn-search" onclick="ga('send', 'event', 'Header', 'Search', 'Search box', {'nonInteraction': 1});"><img src="<?= $this->config['assets_image_url_v2'] ?>search-icon-white.png" width="20"></a></div>
                </div>
            </div>
            <!--endnavbar-->
            <!--search-->
            <div class="search-section">
                <div class="table-section">
                    <div class="table-middle">
                        <form class="form-search" action="<?php echo $this->config['rel_url'] ?>search-result.html" method="post">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="submit" class="icon-search"><img src="<?= $this->config['assets_image_url_v2'] ?>search-icon-white.png" width="20"></button>
                                </div>
                                <input type="text" class="form-control" name="inputSearch" placeholder="Type and Enter">
                                <div class="input-group-btn">
                                    <a href="javascript:void(0);" class="close-search"><img src="<?= $this->config['assets_image_url_v2'] ?>close-icon-Search.png"></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!--endsearch-->
            <!--menu-->
            <div class="menu-section">
                <div class="table-section">
                    <div class="table-middle">
                      <a href="javascript:void(0);" class="close-menu"><img src="<?= $this->config['assets_image_url_v2'] ?>close-icon-menu.png"></a>
                        <ul class="list-navbar-more list-unstyled clearfix">
                            <li><a href="<?= $this->config['rel_url'] ?>popular/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Popular');" >POPULAR</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>news/" onclick="ga('send', 'event', 'Homepage', 'Category', 'News');" >NEWS</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>lol/" onclick="ga('send', 'event', 'Homepage', 'Category', 'LOL');" >LOL</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>celebrity/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Celebrity');" >Celebrity</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>figure/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Figure');" >Figure</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>community/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Community');" >Community</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>wow/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Wow!');" >WOW!</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>love/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Love');" >Love</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>tech/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Tech');" >Tech</a></li>
                            <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>health/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Health');" >Health</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>gross/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Gross!');" >Gross!</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>global/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Global');" >Global</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>womp/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Womp');" >Womp</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>animals/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Animals');" >Animals</a></li>
                             <li><a href="<?= $this->config['rel_url'] ?>babies/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Babies');" >Babies</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>sports/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Sports');" >Sports</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>scary/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Scary');" >Scary</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>girls/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Girls');" >Girls</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>guys/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Guys');" >Guys</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>travel/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Travel');" >Travel</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>politics/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Politics');" >Politics</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>economics/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Economics');" >Economics</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>fashion/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Fashion');" >FASHION</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>parents/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Parents');" >Parents</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>music/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Music');" >Music</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>science/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Science');" >Science</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>serious/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Serious');" >Serious</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>personality/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Personality');" >Personality</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>socialite/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Socialite');" >Socialite</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>home-living/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Home Living');" >Home Living</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>food/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Food');" >Food</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>movie/" onclick="ga('send', 'event', 'Homepage', 'Category', 'Movie');" >Movie</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--endmenu-->
            <!--billboard-->
            <?php //echo $announcement ?>
            <!--endbillboard-->

            <script async src="<?= $this->config['assets_js_url_v2']; ?>bootstrap.min.js"></script>
            <script async src="<?= $this->config['assets_js_url_v2']; ?>plugin.js"></script>
            <script async src="<?= $this->config['assets_js_url_v2']; ?>jquery.lazy.min.js"></script>
            
            <script async src="<?= $this->config['assets_js_url_v2']; ?>jquery.tooltip.js"></script>
            <script async src="<?= $this->config['assets_js_url_v2']; ?>main.js"></script>

            <!-- content -->
            <?= $content ?>
            <!-- end content -->

            <!-- bottom menu -->
            <?= $bottom_menu ?>
            <!-- bottom menu -->
            <!--footer-->
            <div class="footer">
              <div class="container">
                  <div class="footer-left pull-left">
                       <a href="<?php echo $this->config['base_url']; ?>"><img src="<?= $this->config['assets_image_url_v2'] ?>logo-atas.png" width="160" /></a>
                    </div>
                    <div class="footer-right pull-right">
                      <ul class="link-footer list-unstyled">
                            <li><a href="#">Contact us</a></li>
                            <li>/</li>
                            <li><a href="#">About Brillio</a></li>
                            <li>/</li>
                            <li><a href="#">Editorial Staff</a></li>
                            <li>/</li>
                            <li><a href="#">Privacy</a></li>
                            <li>/</li>
                            <li><a href="#">Disclaimer</a></li>
                            <li>/</li>
                            <li><a href="<?= $this->config['base_url'] ?>news/your-opportunity-to-join-brilionet-151124j.html">Career</a></li>
                            <li>/</li>
                            <li><a href="#">Sitemap</a></li>
                        </ul>
                        <span class="copyright">&copy; 2016 Brilio.net - KLN Kapanlagi Network. All Right Reserved</span>
                    </div>
                </div>
            </div>
            <!--endfooter-->
        </div>
        <!--endsection-->
        <!--backtotop-->
        <a href="javascript:void(0);" class="backtop">TOP</a>
        <!--end backtotop-->

        <!-- FB SDK -->
        <div id="fb-root"></div>
        <script>
            (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id))
                return;
            js      = d.createElement(s);
            js.id   = id;
            js.src  = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=834884736607990";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script>
        <!-- end FB SDK -->

        <script type='text/javascript'>
            var ver = '1.0.3';
            var src = 'https://cdns.klimg.com/newshub.id/static/js/newshub.id/www/'+ver+'/frontend/' + 'global.js';
            document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');
        </script>

        <!-- script to count pageview when js is not active -->
        <noscript>
            <img style="display: none;" src="https://www.newshub.id/app/record_jsview/" />
        </noscript>
        <!-- end pageview counter -->

        <iframe src="//d.kapanlaginetwork.com/ga.html?<?= (isset($meta['iframe_kl'])? $meta['iframe_kl'] : $this->config['base_config'] )?>" height="1" width="1" style="display:none;visilibity:hidden;"></iframe>

        <!-- Run Chartbeat -->
        <script type='text/javascript'>
            var _sf_async_config = {};
            /** CONFIGURATION START **/
            _sf_async_config.uid = 62012;
            _sf_async_config.domain = 'brilio.net';
            _sf_async_config.useCanonical = true;
            _sf_async_config.sections = "<?=(isset($meta['chartbeat_sections']) ? ucwords($meta['chartbeat_sections']) : 'Homepage')?>";  //CHANGE THIS
            _sf_async_config.authors = "<?=(isset($meta['chartbeat_authors'])? $meta['chartbeat_authors'] : 'Brilio.net')?>";    //CHANGE THIS
            /** CONFIGURATION END **/
            (function () {
                function loadChartbeat() {
                    window._sf_endpt = (new Date()).getTime();
                    var e = document.createElement('script');
                    e.setAttribute('language', 'javascript');
                    e.setAttribute('type', 'text/javascript');
                    e.setAttribute('src', '//static.chartbeat.com/js/chartbeat.js');
                    document.body.appendChild(e);
                }
                var oldonload = window.onload;
                window.onload = (typeof window.onload != 'function') ?
                        loadChartbeat : function () {
                            oldonload();
                            loadChartbeat();
                        };
            })();
        </script>
        <!-- end run chartbeat -->

        <!--LOTAME PIXEL TAG-->
        <script src="//tags.crwdcntrl.net/c/7171/cc_af.js"></script>
    </body>
</html>
