
<link rel="stylesheet"  href="<?= $this->config['assets_css_url']?>main.css">
<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <li><a href="<?= $this->config['rel_url']?>">Home</a></li>
        <li>&raquo;</li>
        <li><a href="#">Company</a></li>
        <li>&raquo;</li>
        <li><a href="#">Sitemap</a></li>
    </ol>
</div>
<div class="sitemap">
    <a href="<?= $this->config['rel_url']?>news/" class="float-left">News</a>
    <a href="<?= $this->config['rel_url']?>life/" class="float-left">Life</a>
    <a href="<?= $this->config['rel_url']?>popular/">Popular</a>
    <ul>
        <li><a href="<?= $this->config['rel_url']?>popular/">Daily</a></li>
        <li><a href="<?= $this->config['rel_url']?>popular/week/">Weekly</a></li>
    </ul>
    <a href="<?= $this->config['rel_url']?>most-liked/">Most Liked</a>
    <ul>
        <li><a href="<?= $this->config['rel_url']?>most-liked/">Daily</a></li>
        <li><a href="<?= $this->config['rel_url']?>most-liked/week/">Weekly</a></li>
    </ul>
    <a href="<?= $this->config['rel_url']?>most-commented/">Most Commented</a>
    <ul>
        <li><a href="<?= $this->config['rel_url']?>most-commented/">Daily</a></li>
        <li><a href="<?= $this->config['rel_url']?>most-commented/week/">Weekly</a></li>
    </ul>
    <a href="<?= $this->config['rel_url']?>most-shared/">Most Shared</a>
    <ul>
        <li><a href="<?= $this->config['rel_url']?>most-shared/">Daily</a></li>
        <li><a href="<?= $this->config['rel_url']?>most-shared/week/">Weekly</a></li>
    </ul>
    <a href="<?= $this->config['rel_url']?>tag/">Recent Tags</a>
</div>
<div class="office">
    <b>Alamat</b><br>
    <b>Redaksi Brilio.net</b><br>
    Jl. Tebet Barat IV No.5<br>
    Jakarta Selatan, 12810<br>
    Email : redaksi@brilio.net<br>
    Telp : (021) 83795245<br>
    Fax : (021) 83795246
</div>
<div class="menu-sitemap">
    <ul>
        <li>
            <a href="<?= $this->config['rel_url']?>company/contact-us/">Kontak Kami</a>
        </li>
        <li>
            <a href="<?= $this->config['rel_url']?>company/pengaduan/">Keberatan Pemberitaan</a>
        </li>
        <li>
            <a href="http://dewanpers.or.id/form_pengaduan/" target="_blank">Pengaduan Dewan Pres</a>
        </li>
    </ul>
</div>