<!--section -->
<link rel="stylesheet" href="<?= $this->config['assets_css_url'] ?>detail.css?v=<?= $this->config['assets_css_version'] ?>" >

<div class="section">
    <!-- breadcrumb -->
    <ol class="list-breadcrumb list-unstyled">
        <li>
            <a href="<?= $this->config['rel_url'] ?>" onclick="ga('send', 'event', 'Detail video - Breadcumb', 'Click', 'Home');">Home</a>
        </li>
        <li>»</li>
        <li>
            <a href="<?= $breadcrumb['category_url'] ?>" onclick="ga('send', 'event', 'Detail video - Breadcumb', 'Click', '<?=$breadcrumb['category'] ?>');"><?=$breadcrumb['category'] ?></a>
        </li>
    </ol>
    <!-- ./ breadcrumb -->
    <?= $collect_email ?>
    <!--end collect email-->

    <!-- share button on top when scroll -->
    <ul class="share-fixed list-unstyled">
        <li class="fb">
            <a href="<?="http://www.facebook.com/sharer/sharer.php?u=". $news_data['url_share'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                    return false" class="fb">
                <div class="fb-icon"></div>
            </a>
        </li>
        <li class="twit">
            <a href="<?= "https://twitter.com/intent/tweet?text=". $news_data['news_title']. "&url=". $news_data['url_share']. "&via=brilio.net"?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                    return false" class="twit">
                <div class="tw-icon"></div>
            </a>
        </li>
        <li class="wa">
            <a href="<?= "whatsapp://send?text=" . "Brilio.net | " . $news_data['news_title'] . " " . $news_data['url_share']?>" data-action="share/whatsapp/share" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                    return false" class="wa">
                <div class="wa-icon"></div>
            </a>
        </li>
    </ul>
    <!-- ./ share button on top when scroll -->

<!-- detail-br -->
<div class="detail-br">
    <div class="headline-detail">
        <span class="date"><?= $news_data['news_date_publish_indo'] ?></span>
        <h1><?= $news_data['news_title'] ?></h1>
        <span class="read-sinopsis"><?= $news_data['news_synopsis'] ?></span>
        <span class="writer"><?= $news_data['reporter']['name'] ?></span>
    </div>
    <div class="img-detail">
        <div class="auto-resizable-iframe">
            <div>
                <?php echo htmlspecialchars_decode($news_data['news_embed_video']['video_path']);  ?>
            </div>
        </div>
        <span class="img-copy"><?= $news_data['news_imageinfo'] ?></span>
        <!-- NEWS PAGING TOP -->
        <?php if ( isset($news_data['news_paging_list']) ): ?>
            <?php if (count($news_data['news_paging_nav_list_top']) > 0): ?>
            <ul class="artikel-paging-list list-unstyled clearfix">
                <li class="intro <?= $news_data['news_paging_next']['intro_active_state'] ?>">
                    <a href="<?= $news_data['news_url_full'] ?>" onclick="ga('send', 'event', 'Detail video - Paging button top', 'Click', 'INTRO');">INTRO</a>
                </li>
                <?php foreach ($news_data['news_paging_nav_list_top'] as $key): ?>
                    <?php echo $key ?>
                <?php endforeach ?>

                <li class="arrow pull-right">
                    <div class="pull-left"><a href="<?= (isset($news_data['news_paging_prev']['news_paging_url']) ? $news_data['news_paging_prev']['news_paging_url'] : '#' ) ?>" onclick="ga('send', 'event', 'Detail video - Paging button top', 'Click', 'PREV');"><span class="arrow-detail arrow-left"></span></a></div>
                    <div class="pull-left"><a href="<?= $news_data['news_paging_next']['news_paging_url'] ?>" onclick="ga('send', 'event', 'Detail video - Paging button top', 'Click', 'NEXT');"><span class="arrow-detail arrow-right"></span></a></div>
                </li>
            </ul>
            <?php endif ?>
        <?php endif ?>
        <!-- ./ NEWS PAGING TOP-->
    </div>


    <div class="body-paragraph">

        <div class="sosmed-box">
            <!-- social share container -->
            <div id="social-share"></div>
            <!-- social share container -->
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#social-share').socialShare({
                        url: "<?= $news_data['news_url_with_base']?>",
                        twitter_user: "brilionet",
                        platform     : "m",
                    });
                });
            </script>
        </div>

        <p>
        <div class="news-content">
            <?php if (isset($news_data['news_paging_now_active']) &&  !empty($news_data['news_paging_now_active'])) : ?>
            <p>
                <strong><?= $news_data['news_paging_now_active']['news_paging_no'] . '. ' .$news_data['news_paging_now_active']['news_paging_title'] ?></strong>
            </p>
            <?php endif ?>
            <?= html_entity_decode($news_data['news_content']) ?>
        </div>
        </p>

        <?php if ( isset($news_data['news_paging_next']) ): ?>
        <div class="detail-box next-paging text-center">
            <a href="<?= $news_data['news_paging_next']['news_paging_url'] ?>" onclick="ga('send', 'event', 'Detail video - Paging button bottom', 'Click', '<?= $news_data['news_paging_next']['news_paging_title'] ?>');" id="next-but" style="background-position: right 13px top 50%;"><?= $news_data['news_paging_next']['news_paging_title'] ?></a>
        </div>
        <?php endif ?>

        <!-- split -->
        <?php if (!empty($split_data)): ?>
            <div class="nextprev-paging text-center clearfix">

                <?php if ( isset($split_data['split_url_prev']) ): ?>
                <!-- {PREV_SPLIT_NAV}  -->
                <a href="<?= $split_data['split_url_prev']  ?>" onclick="ga('send', 'event', 'Detail video - Prev next article', 'Click', 'PREV');" id="prev-but-split">Prev</a>
                    <?php if ( empty($split_data['split_url_next']) ) : ?>
                        <span style="width:50%; height:1px; float: left;"></span>
                    <?php endif ?>
                <?php endif ?>

                <?php if ( isset($split_data['split_url_next']) ): ?>
                <!-- {NEXT_SPLIT_NAV} -->
                    <?php if ( empty($split_data['split_url_prev']) ): ?>
                        <span style="width:50%; height:1px; float: left;"></span>
                    <?php endif ?>
                <a href="<?= $split_data['split_url_next'] ?>" onclick="ga('send', 'event', 'Detail video - Prev next article', 'Click', 'NEXT');" id="next-but-split">Next</a>
                <?php endif ?>
            </div>

            <script type="text/javascript">
                $browser = window.navigatorDetect.browser();
                if ($browser === "UCBrowser") {
                    document.getElementById("next-but-split").style.backgroundPosition = "-100px -100px";
                    document.getElementById("prev-but-split").style.backgroundPosition = "-100px -100px";
                } else {
                    document.getElementById("next-but-split").style.backgroundPosition = 'right 40px center';
                    document.getElementById("prev-but-split").style.backgroundPosition = 'left 40px center';
                }
            </script>
        <?php endif ?>
        <!-- ./ split -->



        <p><?= $news_data['author']['inisial_editor'] ?></p>
    </div>
    <?php echo $video; ?>
    <div class="social-like-box">
        <div class="social-like">
            Klik
            <div class="fb-like" data-href="https://www.facebook.com/BrilioDotNet" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div> untuk Artikel ini
        </div>
    </div>
    <ul class="read-box list-tag list-unstyled">
        <?php
        if(isset($news_data['news_tag_list']) AND !empty($news_data['news_tag_list']))
        {
            foreach ($news_data['news_tag_list'] as $key){
            ?>
                <li>
                    <a href="<?= $key['tag_url_full'] ?>" onclick="ga('send', 'event', 'Detail video - Tags article', 'Click', '<?= $key['tag_news_tags'] ?>');" target="_blank"><?= $key['tag_news_tags'] ?></a>
                </li>
            <?php
            }
        }//if
        if ( !empty($news_data['sponsor_tag']) )
        {
            $key= $news_data['sponsor_tag'] ;
            ?>
                <li>
                    <a href="<?= $key['tag_brand_url'] ?>" onclick="ga('send', 'event', '<?= $TE_2 ?>', 'Tag article', 'Brands');" target="_blank"><?= $key['tag_name'] ?></a>
                </li>
            <?php
        }//if
        ?>
    </ul>
    <div class="detail-box text-center">
        <h6 class="title-black">SHARE NOW</h6>
        <ul class="list-share list-unstyled">
            <li>
                <a href="<?="http://www.facebook.com/sharer/sharer.php?u=". $news_data['news_url_with_base'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                        return false" class="fb"></a>
            </li>
            <li>
            <a href="<?= "https://twitter.com/intent/tweet?text=". $news_data['news_title']. "&url=". $news_data['news_url_with_base']. "&via=brilio.net"?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                        return false" class="twit"></a>
            </li>
            <li>
                <a href="<?= "whatsapp://send?text=" . "Brilio.net | " . $news_data['news_title'] . " " . $news_data['news_url_with_base']?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                        return false" class="wa"></a>
            </li>
        </ul>
    </div>
    <div class="read-gateway">
        <div class="read-gateway-img">
            <a href="http://storytelling.brilio.net/" onclick="ga('send', 'event', 'Detail video - Gateway story telling ', 'Click', 'gateway story telling');" target="_blank">
                <img src="<?= $this->config['assets_image_url'] ?>hubungi.mobile.png">
            </a>
        </div>
        <div class="read-gateway-text">
            <a href="http://storytelling.brilio.net/" onclick="ga('send', 'event', 'Detail video - Gateway story telling ', 'Click', 'gateway story telling');" target="_blank">
                <b>Everyone</b> has <b>Untold Stories</b>. Sebarkan ceritamu di sini.
            </a>
        </div>
    </div>
    <?php if (!empty($news_related)): ?>
        <?php echo $news_related ?>
    <?php endif ?>



    <?php if ($news_data['news_sensitive'] != 1): ?>
    <div class="comment-title">WHAT DO YOU THINK?</div>
    <div class="fb-comment">
        <!-- FB COMMEND -->
        <div class="content-left-commant">
            <div class="fb-comments" data-href="<?= $news_data['news_url_with_base'] ?>" data-width="100%" data-numposts="10" data-colorscheme="light"></div>
        </div>
        <!-- FB COMMEND -->
    </div>
    <?php endif ?>
</div>
<!-- ./detail-br -->

<div class="list-article-box" style="margin-top:-35px;">
    <div class="bottom-tags-title">
        <div class="bottom-tags-title-line"></div>
        <div class="bottom-tags-title-name">MOST POPULAR</div>
    </div>
    <div class="box-float">
        <ul class="list-article-berita list-number list-unstyled">
            <?php
                if(!empty($popular['trending'])):
                  $no=1;
                  foreach ($popular['trending'] as $key): ?>
                  <?php if ($no<=7): ?>

                    <li>
                        <div class="article-left"><?= $key['NO'] ?></div>
                        <div class="deskrip-br-popular">
                            <p class="deskrip-text">
                                <a href="<?= $key['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Homepage - Most popular', 'Click', '<?= $key['NEWS_TITLE'] ?>');" class="popular"><?= $key['NEWS_TITLE'] ?></a>
                            </p>
                        </div>
                    </li>
                  <?php else: break;?>
                  <?php endif; ?>
                <?php
                $no++;
                    endforeach;
                endif;?>
        </ul>
    </div>
</div>

<?php echo $_list_categories_bottom ?>
<!-- jsview -->
<input type="hidden" id="news_url_full" value="<?= $news_data['news_url_with_base']?>">
<input type="hidden" id="jsview_url" value="<?= $news_data['news_url_with_base']?>">
<input type="hidden" id="detail_news" value="true">
<!-- end of jsview -->
