<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta name="description" content="Temukan segala kisah kehidupan, gaya hidup, renungan, inspirasi, dan ilmu pengetahuan di sini" />
    <meta name="keywords" content="brilio, temukan, segala, kisah, kehidupan, gaya, hidup, renungan, inspirasi, dan, ilmu, pengetahuan, di, sini" />
    <title>Brilio.net | Life and science</title>
    <script type="text/javascript" language="javascript" src="http://a.merdeka.com/js_v2/assets/jquery.min.js"></script>

</head>

<body style="margin:0px; padding:0px;">
    <center>
       <img id="image-popup" src="http://cdn.klimg.com/merdeka.com/media/i/a/popup/hari-sejuta-pohon.jpg" width="300" height="300">
        <div id="beacon_bdb24b03c1" style="position: absolute; left: 0px; top: 0px; visibility: hidden;">
            <img width="0" height="0" style="width: 0px; height: 0px;" alt="" src="http://d.kapanlaginetwork.com/lg.php?bannerid=12038&campaignid=4825&zoneid=219&cb=a6c6e1b957">
        </div>
        <div id="wording-popup" style="font-weight:bold;margin-left:5px;font-size:17px;">text wording dibawah image</div>
        <div class="fb_like" style="text-align:center;margin-top:10px;width:250px;">
            <div id="fb_like_wording" style="margin:0px auto;overflow:hidden;">
                <div class="brilio-box-like" style="float:left;width:50px;overflow:hidden;margin:0px 10px 0px 10px;position:relative;">
                    <a target="_blank" id="brilio-fake-like" style="left:0;position: absolute; z-index: +999; border-radius: 2px 0 0 2px; color: #fff; padding: 3px 5px; width: 10px; height: 14px; background: linear-gradient(#4C69BA, #3B55A0) repeat scroll 0% 0% transparent; font-family: 'Helvetica Neue',Helvetica,Arial,'lucida grande',tahoma,verdana,arial,sans-serif; font-size: 11px; font-weight: bold;opacity: 0.0;
				filter: alpha(opacity=40);"></a>
                    <div class="fb-like" data-send="false" data-layout="button_count" data-href="https://www.facebook.com/pages/BRILIOnet/428479613995366" data-width="50" data-height="200" data-show-faces="false"></div>
                </div>
                <div style="float:left;width:75px;">
                    <a href="https://twitter.com/brilionet" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @brilionet</a>
                    <script>
                        ! function (d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0],
                                p = /^http:/.test(d.location) ? 'http' : 'https';
                            if (!d.getElementById(id)) {
                                js = d.createElement(s);
                                js.id = id;
                                js.src = p + '://platform.twitter.com/widgets.js';
                                fjs.parentNode.insertBefore(js, fjs);
                            }
                        }(document, 'script', 'twitter-wjs');
                    </script>
                </div>
                <br class="clear" />
            </div>
        </div>
        <div class="title"></div>
    </center>
    <div style="clear: both"></div>

    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '834884736607990',
                status: true,
                cookie: true,
                xfbml: true
            });
            FB.Event.subscribe('edge.create', function (response) {
                var a = document.getElementById('brilio-fake-like'); //or grab it by tagname etc
                a.href = "https://www.facebook.com/pages/BRILIOnet/428479613995366";
            });
        };
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=341995562513785";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

</body>

</html>