<!--section -->
<div class="section">
    <div class="box-float nav-box">
        <ol class="list-breadcrumb list-unstyled">
            <li>
                <a href="<?php echo $this->config['rel_url']; ?>" onclick="ga('send', 'event', 'Index all tags - Breadcumb', 'Click', 'HOME');">HOME</a>
            </li>
            <li>&raquo;</li>
            <li>
                <a href="<?php echo $this->config['rel_url']; ?>tag/" onclick="ga('send', 'event', 'Index all tags - Breadcumb', 'Click', 'TAG');">TAG</a>
            </li>
            <!-- {BREADCRUMB} -->
            <?php
                if(!empty($BREADCRUMB)) {
                    ?>
                        <li><?php echo $BREADCRUMB['BREADCUMB_SIMBOL'] ?></li>
                        <li>
                            <a href="<?php echo $BREADCRUMB['BREADCUMB_URL']; ?>" onclick="ga('send', 'event', 'Index all tags - Breadcumb', 'Click', '<?php echo $BREADCRUMB['BREADCUMB_TITLE'] ?>);"><?php echo $BREADCRUMB['BREADCUMB_TITLE'] ?></a>
                        </li>
                    <?php
                }
            ?>
            <!-- end {BREADCRUMB} -->
        </ol>
    </div>
    <div class="bottom-tags-title" style ="margin-top:-0px;">
        <div class="bottom-tags-title-line"></div>
        <div class="bottom-tags-title-name"><?php echo $TAGS_TITLE; ?></div>
    </div>
    <div class="list-article-box">
        <!-- {NEWS} -->
        <?php

        if(!empty($LIST_TAG['PESAN'])) {
            ?>
                <span class="pesan-error"><?php echo  $LIST_TAG['PESAN'] ?></span>
            <?php
        }
        else {

        ?>
            <div class="content-left-all-tag">
                <!-- {LIST_TAG_FIRST} -->
                <!-- NEWS_LIST_LEFT -->
                <?php
                    $NEWS_LIST_LEFT = $LIST_TAG[0]['LIST_LEFT'];
//                    echoPre($NEWS_LIST_LEFT);die;
                ?>
                <ul class="list-article-berita list-article-double list-unstyled">
                    <li>
                        <h6 class="title-green text-large title-tag">
                        <a href="<?php echo  $NEWS_LIST_LEFT['TAG_LINK_URL'] ?>" onclick="ga('send', 'event', 'Tag pages - <?php echo $NEWS_LIST_LEFT['TAGS_NEWS_TAGS'] ?>, 'Click', '<?php echo $NEWS_LIST_LEFT['TAGS_NEWS_TAGS'] ?>');"><?php echo $NEWS_LIST_LEFT['TAGS_NEWS_TAGS'] ?></a>
                        </h6>
                        <a href="<?php echo $NEWS_LIST_LEFT['NEWS_URL'] ?>" class="article-left"><img src="<?php echo $NEWS_LIST_LEFT['NEWS_IMG'] ?>" width="104" height="70">
                        </a>
                        <div class="deskrip-br">
                            <p class="deskrip-text"><a href="<?php echo $NEWS_LIST_LEFT['NEWS_URL'] ?>"><?php echo $NEWS_LIST_LEFT['NEWS_TITLE'] ?></a>
                            </p>
                        </div>
                    </li>
                </ul>
                <!-- end NEWS_LIST_LEFT -->
                <!-- NEWS_LIST_RIGHT -->
                <ul class="list-article-berita list-article-small list-unstyled">
                <?php
                    $NEWS_LIST_RIGHT = $LIST_TAG[0]['LIST_RIGHT'];
                    if (!empty($NEWS_LIST_RIGHT)) {
                        foreach ($NEWS_LIST_RIGHT as $data) {
                            ?>
                            <li>
                                <div class="deskrip-br">
                                    <div class="kategori-date">
                                        <span class="date"><?php echo $data['NEWS_TIME']; ?></span>
                                    </div>
                                    <p class="deskrip-text"><a href="<?php echo $data['NEWS_URL']; ?>"><?php echo $data['NEWS_TITLE'] ?></a></p>
                                </div>
                            </li>
                            <?php
                        }
                    }
                ?>
                </ul>
                <!-- end NEWS_LIST_RIGHT -->
                <!-- end {LIST_TAG_FIRST} -->
                <!-- {LIST_ALPABET} -->
                <div class="list-article-box">
                    <div class="bottom-tags-title" style="margin-bottom: 10px;">
                        <div class="bottom-tags-title-line"></div>
                        <div class="bottom-tags-title-name">TAGS ALPHABETICAL</div>
                    </div>
                    <div class="box-float">
                        <ul class="list-alphabet list-unstyled clearfix">
                            <!-- {LIST_ALPABET} -->
                            <?php
                                foreach ($LIST_ALPHABET['LIST_ALPHABET'] as $data) {
                                    ?>
                                        <li>
                                            <a href="<?php echo $this->config['rel_url'] ?>tag/<?php echo $data['ALPHABET'] ?>/" onclick="ga('send', 'event', 'Indexs all tags - Alphabetical box', 'Click', '<?php echo $data['ALPHABET']?>');" class="transform <?php echo $data['TAGS_AKTIF'] ?>"><?php echo  $data['ALPHABET'] ?></a>
                                        </li>
                                    <?php
                                }
                            ?>
                            <!-- end {LIST_ALPABET} -->
                            <li>
                                <a href="<?php echo $this->config['rel_url'] ?>tag/num/">#</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- end {LIST_ALPABET} -->
                <!-- {LIST_TAG_SECOND} -->
                <!-- NEWS LIST LEFT -->
                <?php
//                    if(!empty($NEWS['LIST_TAG_SECOND'])) {
                        $no = 0;
                        foreach ($LIST_TAG as $list_tag_second) {
                            if(!empty($list_tag_second['LIST_LEFT'])){
                            if($no != 0) {
                                ?>
                                    <ul class="list-article-berita list-article-double list-unstyled">
                                        <li>
                                            <h6 class="title-green text-large title-tag">
                                            <a href="<?php echo $list_tag_second['LIST_LEFT']['TAG_LINK_URL'] ?>" onclick="ga('send', 'event', 'Tag pages - <?php echo $list_tag_second['LIST_LEFT']['TAGS_NEWS_TAGS'] ?>', 'Click', '<?php echo $list_tag_second['LIST_LEFT']['TAGS_NEWS_TAGS'] ?>');"><?php echo $list_tag_second['LIST_LEFT']['TAGS_NEWS_TAGS'] ?></a>
                                            </h6>
                                            <a href="<?php echo $list_tag_second['LIST_LEFT']['NEWS_URL'] ?>" class="article-left"><img src="<?php echo $list_tag_second['LIST_LEFT']['NEWS_IMG'] ?>" width="104" height="70">
                                            </a>
                                            <div class="deskrip-br">
                                                <p class="deskrip-text"><a href="<?php echo $list_tag_second['LIST_LEFT']['NEWS_URL'] ?>"><?php echo $list_tag_second['LIST_LEFT']['NEWS_TITLE'] ?></a>
                                                </p>
                                            </div>
                                        </li>
                                    </ul>
                                <?php
                                if(!empty($list_tag_second['LIST_RIGHT'])) {
                                    ?>
                                        <ul class="list-article-berita list-article-small list-unstyled">
                                            <?php
                                                foreach ($list_tag_second['LIST_RIGHT'] as $data) {
                                                    ?>
                                                        <li>
                                                            <div class="deskrip-br">
                                                                <div class="kategori-date">
                                                                    <span class="date"><?php echo $data['NEWS_TIME'] ?></span>
                                                                </div>
                                                                <p class="deskrip-text"><a href="<?php echo $data['NEWS_URL'] ?>"><?php echo $data['NEWS_TITLE'] ?></a></p>
                                                            </div>
                                                        </li>
                                                    <?php
                                                }
                                            ?>
                                        </ul>
                                    <?php
                                }
                            }
                            $no++;
                            }
                        }
//                    }
                ?>

                <!-- end NEWS LIST LEFT -->
                <!-- end {LIST_TAG_SECOND} -->
            </div>
            <ul class="list-pagination list-unstyled">
                <!-- {PAGINATION} -->
                <?php echo $LIST_TAG['PAGINATION']; ?>
                <!-- end {PAGINATION} -->
            </ul>
        <?php
        }
        ?>

        <!-- end {NEWS} -->
    </div>
</div>
<!--end section-->
