<?php
echo '<?xml version="1.0" encoding="utf-8"?>' . "\n";
?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <generator>http://www.brilio.net</generator>
        <title>Brilio.net</title>
        <link>http://www.brilio.net</link>
        <description>Temukan segala kisah kehidupan, gaya hidup, renungan, inspirasi, dan ilmu pengetahuan di sini</description>
        <language>id</language>
        <webMaster>redaksi@brilio.net</webMaster>
        <pubDate><?php echo $content['PUBDATE']; ?></pubDate>
        <image>
            <title>www.brilio.net</title>
            <url>http://www.brilio.net/assets/img/logo-atas.png</url>
            <link>http://www.brilio.net</link>
        </image>
        <?php
        foreach ($content['ITEM'] as $data) {
            ?>
            <item>
                <title><?php echo $data['NEWS_TITLE'] ?></title>
                <link><?php echo $data['NEWS_URL'] ?></link>
                <pubDate><?php echo $data['NEWS_DATE_PUBLISH'] ?></pubDate>
                <dc:creator>brilio.net</dc:creator>
                <category><?php echo $data['CATEGORY_TITLE'] ?></category>
                <guid><?php echo $data['NEWS_URL'] ?></guid>
                <description>
                    <![CDATA[<?php echo $data['NEWS_SYNOPSIS'] ?>]]>
                </description>
                <content:encoded>
                    <![CDATA[<?php echo $data['NEWS_SYNOPSIS'] ?>]]>
                </content:encoded>
                <enclosure url="<?php echo $data['NEWS_IMAGES'] ?>" length="49488" type="image/jpeg">
                </enclosure>
            </item>
            <?php
        }
        ?>
    </channel>
</rss>