<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Brilio.net</title>
    <link>https://www.brilio.net/</link>
    <description>
      Temukan segala kisah kehidupan, gaya hidup, renungan, inspirasi, dan ilmu pengetahuan di sini
    </description>
    <language>id</language>
    <lastBuildDate><?php echo $content[0]['date_pub'] ?></lastBuildDate>
    <?php foreach ($content as $v):?>
    <item>
	  <title><?php echo $v['title'] ?></title>
	  <link><?php echo $v['full_url'] ?></link>
	  <guid><?php echo $v['news_id']; ?></guid>
          <pubDate><?php echo $v['date_iso'] ?></pubDate>
	  <author><?php echo $v['reporter'] ?></author>
	  <description><?php echo $v['synopsis']; ?></description>
	  <content:encoded>
		<![CDATA[
		<!doctype html>
		<html lang="en" prefix="op: http://media.facebook.com/op#">
		<head>
		    <meta charset="utf-8">
		    <link rel="canonical" href="<?php echo $v['full_url'] ?>">
		    <meta property="op:markup_version" content="v1.0">
		</head>
		<body>
		    <article>
		      <header>
		        <h1><?php echo $v['title'] ?></h1>
		        <h2><?php echo $v['synopsis']; ?></h2>
		        <!-- contoh format datetime -->
		       <time class="op-published" datetime="<?php echo $v['date_iso']; ?>"><?php echo $v['date_time']; ?></time>
		       <!-- The authors of your article -->
		       <address><?php echo $v['reporter']; ?></address>
		       <figure>
		          <img src=<?php echo $v['img_url']; ?> />
		          <figcaption><?php echo $v['img_info'] ?></figcaption>
		       </figure>
		       <!-- A kicker for your article -->
		       <details>
		          <summary>Brilio.net</summary>
		          <?php echo $v['category_name']; ?>
		       </details>
		      </header>
		      <!-- Article body goes here -->
		      <!-- Body text for your article -->
                      <?php echo $v['content']; ?>
		      <figure class="op-tracker">
                          <iframe>
                                <script>
                                    (function (i, s, o, g, r, a, m) {
                                        i['GoogleAnalyticsObject'] = r;
                                        i[r] = i[r] || function () {
                                            (i[r].q = i[r].q || []).push(arguments)
                                        }, i[r].l = 1 * new Date();
                                        a = s.createElement(o),
                                                m = s.getElementsByTagName(o)[0];
                                        a.async = 1;
                                        a.src = g;
                                        m.parentNode.insertBefore(a, m)
                                    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

                                    ga('create', 'UA-61119040-2', 'auto');
                                    ga('send', 'pageview');

                                    ga('create', 'UA-71408030-5', 'auto', 'KLNBrilio');
                                    ga('KLNBrilio.send', 'pageview');
                                </script>
                          </iframe>
		      </figure>
		      <footer><small>&copy; 2016 Brilio.net</small></footer>
		    </article>
		</body>
		</html>
		]]>
	  </content:encoded>
	  <enclosure url="<?php echo $v['img_url']; ?>" length="7" type="image/jpeg"></enclosure>
    </item>
    <?php endforeach; ?>
</channel>
</rss>