<?php //echoPre($news_data) ?>
<!--share-article-->
<div class="share-fixed">
    <div class="fixed-table">
        <div class="fixed-left">
            <h5 class="link-share"><?= $news_data['news_title'] ?></h5>
        </div>
        <div class="fixed-right">
            <div class="share-right pull-right">
                <div class="max-share"><span class="fb-share-count-box"></span><span class="text-share">Shares</span></div>
                <div class="col-btn-share">
                    <a href="<?="http://www.facebook.com/sharer/sharer.php?u=". $news_data['news_url_with_base'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260'); return false" class="btn-animation btn-fb">
                        <div class="icon">
                            <div class="before"><span class="fb"></span></div>
                            <div class="after"><span class="fb"></span></div>
                        </div>
                        <span class="text-btn">SHARE</span>
                        <span class="overlay"></span>
                    </a>
                </div>
                <div class="col-btn-share">
                    <a href="<?= "https://twitter.com/intent/tweet?text=Brilio.net - ". $news_data['news_title']. "&url=". $news_data['news_url_with_base']. "&via=brilio.net"?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260'); return false" class="btn-animation btn-tweet">
                        <div class="icon">
                            <div class="before"><span class="tweet"></span></div>
                            <div class="after"><span class="tweet"></span></div>
                        </div>
                        <span class="text-btn">TWEET</span>
                        <span class="overlay"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<!--endshare-article-->

<!--carousel-->
<div class="slider-owl">
    <div class="navigation">
        <a class="prev" onclick="ga('send', 'event', '<?= $TE ?>', 'Carousel button', 'Prev');" ><span class="arrow-left"></span></a>
        <a class="next" onclick="ga('send', 'event', '<?= $TE ?>', 'Carousel button', 'Next');" ><span class="arrow-right"></span></a>
    </div>
    <div class="owl-carousel">
        <?php $no=1;
        foreach ($whats_hot as $key): ?>
            <div class="slide">
            <a href="<?= $key['what_happen_url'] ?>" onclick="ga('send', 'event', '<?= $TE ?>', 'Carousel article', 'Artikel ke-<?=$no?>');"  >
                <img src="<?= $key['what_happen_image_location_full']  ?>" id="278" onerror="imgError(this)" />
                <div class="deskrip-slide">
                    <p><?= $key['what_happen_content'] ?></p>
                </div>
            </a>
            </div>
        <?php $no++;
        endforeach ?>
    </div>
</div>
<!--endcarousel-->

<!--breadcrumb-->
<ol class="list-breadcrumb  list-unstyled">
    <li><a href="<?= $this->config['rel_url'] ?>">BRILIO.NET</a></li>
    <li>&raquo;</li>
    <li><a href="<?= $breadcrumb['category_url'] ?>"><?= $breadcrumb['category'] ?></a></li>
</ol>
<!--endbreadcrumb-->
<!--wrapper-->
<div class="wrapper-col">
    <div class="wrapper-left">
        <div class="detail-article">
            <div class="headline-detail">
                <div class="author-read">
                    <span><?= $news_data['reporter']['name'] ?></span>
                    <span><?= $news_data['news_date_publish_indo'] ?></span>
                </div>
                <h1><?= $news_data['news_title'] ?></h1>
                <h6><?= $news_data['news_synopsis'] ?></h6>
            </div>
            <div class="videoWrapper">
                <?php if (!empty($news_data['news_embed_video']['video_path'])): ?>
                        <?php echo html_entity_decode($news_data['news_embed_video']['video_path']) ?>
                <?php else: ?>
                    <img src="<?= $news_data['news_image_location_full'] ?>" id="1050" onerror="imgError(this)" />
                <?php endif ?>
                <span class="ilustrasi"><?= $news_data['news_imageinfo'] ?></span>

                <?php if (isset($news_data['news_paging_list'])): ?>
                <!-- paging nav top -->
                <div class="paging-berita clearfix">
                    <?php if (count($news_data['news_paging_nav_list_top']) > 0): ?>
                    <a href="<?= $news_data['news_url_full'] ?>" onclick="ga('send', 'event', 'Detail pages - Paging button top', 'Click', 'INTRO');" class="intro" style="background-color:#000 ;color:white;">INTRO</a>
                    <ul class="list-paging-number list-unstyled clearfix">
                        <?php foreach ($news_data['news_paging_nav_list_top'] as $key){
                            echo html_entity_decode($key);
                        } ?>
                    </ul>
                    <div class="arrow-paging">
                        <a href="<?php echo (isset($news_data['news_paging_prev']['news_paging_url']) ? $news_data['news_paging_prev']['news_paging_url'] : '#' ) ?>" onclick="ga('send', 'event', 'Detail pages - Paging button top', 'Click', 'PREV');"><span class="arrow arrow-left"></span></a>
                        <a href="<?php echo (isset($news_data['news_paging_next']['news_paging_url']) ? $news_data['news_paging_next']['news_paging_url'] : '#' ) ?>" onclick="ga('send', 'event', 'Detail pages - Paging button top', 'Click', 'NEXT');"><span class="arrow arrow-right"></span></a>
                    </div>
                    <?php endif ?>
                </div>
                <!-- end paging nav top -->
                <?php endif ?>
            </div>
            <div class="sosmed-box">
                <!-- sosmed newshub -->
                <div class="social-box">
                    <!-- social share container -->
                    <div id="social-share"></div>
                    <!-- social share container -->
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#social-share').socialShare({
                                url: "<?= $news_data['news_url_with_base'] ?>",
                                twitter_user: "brilionet"
                            });
                        });
                    </script>
                </div>
                <!-- end of sosmed newshub -->
            </div>
            <div class="body-paragraph">
                <?= html_entity_decode($news_data['news_content']) ?>

                <?php if ( isset($news_data['news_paging_next']) ) : ?>
                <!-- box paging bottom -->
                <div class="box-paging">
                    <a href="<?= $news_data['news_paging_next']['news_paging_url'] ?>" onclick="ga('send', 'event', 'Detail pages - Paging button bottom', 'Click', '<?= $news_data['news_paging_next']['news_paging_title']?>');" class="img-left"><img src="<?= $news_data['news_paging_next']['news_paging_image']?>" id="150" onerror="imgError(this)"></a>
                    <a href="<?= $news_data['news_paging_next']['news_paging_url'] ?>" onclick="ga('send', 'event', 'Detail pages - Paging button bottom', 'Click', '<?= $news_data['news_paging_next']['news_paging_title']?>');" class="paging-right"><?= $news_data['news_paging_next']['news_paging_title']?></a>
                </div>
                <!-- end box paging bottom -->
                <?php endif ?>

                <?php if (isset($split_data)): ?>
                    <!-- split nav -->
                    <div class="detail-split clearfix">
                    <?php if (isset($split_data['split_url_prev'])): /*for split*/ ?>
                        <div class="col-50">
                            <a href="<?php echo $split_data['split_url_prev'] ?>" onclick="ga('send', 'event', 'Detail Pages - Prev next article', 'Click', 'PREV');" class="pull-left">
                            PREV
                            </a>
                        </div>
                        <?php endif ?>

                        <?php if (isset($split_data['split_url_next'])): ?>
                        <div class="col-50 text-right">
                            <a href="<?php echo $split_data['split_url_next'] ?>" onclick="ga('send', 'event', 'Detail Pages - Prev next article', 'Click', 'NEXT');" class="pull-right">
                            NEXT
                            </a>
                        </div>
                        <?php endif ?>
                    </div>
                    <!-- end split nav -->
                <?php endif ?>

                <p class="author"><?= $news_data['author']['inisial_editor'] ?></p>
            </div>
            <div class="detail-box">
                <ul class="list-tag-border list-unstyled clearfix">
                    <?php if (isset($news_data['news_tag_list'])): ?>
                    <?php $no=1;
                        foreach ($news_data['news_tag_list'] as $key): ?>
                        <li>
                            <a href="<?php echo $key['tag_url_full'] ?>" onclick="ga('send', 'event', '<?=$TE?>', 'Tags article', 'Tag ke-<?=$no ?>');" target="_blank"><?php echo $key['tag_news_tags'] ?></a>
                        </li>
                    <?php
                        $no++;
                        endforeach;
                        endif;
                        if ( !empty($news_data['sponsor_tag']) ) :
                    ?>
                        <li>
                            <a href="<?php echo $news_data['sponsor_tag']['tag_brand_url'] ?>" onclick="ga('send', 'event', '<?=$TE?>', 'Tags article', 'Brands');" target="_blank" ><?php echo $news_data['sponsor_tag']['tag_name'] ?></a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
            <div class="detail-box">
                <div class="detail-share row">
                    <div class="col-md-6">
                        <a href="<?="http://www.facebook.com/sharer/sharer.php?u=". $news_data['news_url_with_base'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260'); return false" class="btn-animation btn-fb">
                            <div class="icon">
                                <div class="before"><span class="fb"></span></div>
                                <div class="after"><span class="fb"></span></div>
                            </div>
                            <span class="text-btn">SHARE ON FACEBOOK</span>
                            <span class="overlay"></span>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="<?= "https://twitter.com/intent/tweet?text=Brilio.net - ". $news_data['news_title']. "&url=". $news_data['news_url_with_base']. "&via=brilio.net"?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260'); return false" class="btn-animation btn-tweet">
                            <div class="icon">
                                <div class="before"><span class="tweet"></span></div>
                                <div class="after"><span class="tweet"></span></div>
                            </div>
                            <span class="text-btn">SHARE ON TWITTER</span>
                            <span class="overlay"></span>
                        </a>
                    </div>
                </div>
            </div>
            <!-- Promote video -->
            <?php
            if(!empty($video))
            {
                echo $video;
            }
            ?>
            <!-- Promote video -->
            <div class="detail-box">
                <div class="title-border">
                    <h4 class="title-line">WHAT DO YOU THINK</h4>
                </div>
                <div class="content-box">
                    <div class="content-left-commant">
                        <div class="fb-comments" data-href="<?php echo $news_data['news_url_with_base'] ?>" data-width="100%" data-numposts="10" data-colorscheme="light"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper-right">
        <div class="article-col-right">
            <?= $collect_email ?>
        </div>
        <div class="article-col-right">
            <?= $trending ?>
        </div>
    </div>
</div>
<!--endwrapper-->

<?= $news_more_stories ?>
<input type="hidden" id="news_url_full" value="<?= $news_data['news_url_with_base'] ?>"/>
