<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name=description content="<?=(isset($meta['meta_description'])? $meta['meta_description'] : 'Brilio.net')?>" />
        <meta name=keywords content="<?=(isset($meta['meta_keywords'])? $meta['meta_keywords'] : 'Brilio.net')?>" />
        <meta http-equiv="Expires" content="<?= date(DATE_RFC1036) ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="brilio.net">
        <!--SOCMED PROPERTY FB-->
        <meta property="fb:admins" content="1560920678" />
        <meta property="fb:admins" content="1225533149" />
        <meta property="fb:admins" content="1504374378" />
        <meta property="fb:admins" content="550628397" />
        <meta property="fb:pages" content="118943308456455" />
        <meta property="fb:app_id" content="834884736607990" />
        <meta property="og:title" content="<?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?>" />
        <meta property="og:site_name" content="brilio.net" />
        <meta property="og:url" content="<?=(isset($meta['og_url'])? $meta['og_url'] : $this->config['base_url'] )?>" />
        <meta property="og:description" content="<?=(isset($meta['meta_description'])? $meta['meta_description'] : 'Brilio.net')?>" />
        <meta property="og:type" content="article" />
        <meta property="og:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta property="og:image:secure_url" content="<?= (isset($meta['og_image_secure']) ? @$meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <!--SOCMED PROPERTY TWITTER-->
        <meta name="twitter:title" content="<?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?>" />
        <meta name="twitter:description" content="<?=(isset($meta['meta_description'])? $meta['meta_description'] : 'Brilio.net')?>" />
        <meta name="twitter:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@brilionet">
        <meta name="twitter:creator" content="@brilionet">
        <meta name="twitter:domain" content="https://twitter.com/brilionet">

        <title><?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?></title>
        <?php
        if(!empty($amphtml))
        {
            ?>
        <link rel="amphtml" href="<?= $amphtml ?>">
            <?php
        }
        ?>
        <link rel="icon" href="<?php echo $this->config['assets_image_url'] ?>favicon.png" type="image/png" >
        <link rel="stylesheet" href="<?= $this->config['assets_css_url_v2']; ?>bootstrap.css">
        <link rel="stylesheet" href="<?= $this->config['assets_css_url_v2']; ?>main.css?version=<?= $this->config['assets_css_version']; ?>">
        <link rel="manifest" href="<?= $this->config['assets_url']; ?>pwa/manifest.json" />
        <link rel="canonical" href="<?= $canonical ?>" />
        <?php if ( !empty($meta['meta_alternate']) ): ?>
            <link rel="alternate" href="<?= (isset($meta['meta_alternate'])? $meta['meta_alternate'] : 'm.brilio.net') ?>" />
        <?php else: ?>
            <meta name="robots" content="noindex">
        <?php endif ?>

        <!-- Google Analytics -->
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-61119040-1', 'auto');
            ga('send', 'pageview');

            ga('create', 'UA-71410836-6', 'auto', 'KLNBrilio');
            ga('KLNBrilio.send', 'pageview');

            ga('create', 'UA-77165806-1', 'auto', 'SUBBrilio');
            ga('SUBBrilio.send', 'pageview');
        </script>
        <!-- end Google Analytics -->

        <!-- Chartbeat -->
        <script type='text/javascript'>
            var _sf_startpt = (new Date()).getTime()
        </script>
        <!-- end Chartbeat -->

        <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '213022759033260');
        fbq('track', "PageView");</script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=213022759033260&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Facebook Pixel Code -->
        <script src="<?= $this->config['assets_js_url_v2']; ?>jquery-1.11.2.js"></script>
        <script type="text/javascript">
            var rel_img_url = '<?=$this->config['assets_image_url_v2'] ?>';
        </script>

    </head>
    <body>



    <div class="slide-notifikasi">
        <div class="brilio-container clearfix" style="width: 90%;">
            <span class="slide-title">Would you like to switch to the English version?</span>
            <span class="slide-undo"><a href="<?= $this->config['www_url_en'] ?>">Yes</a></span>
            <span class="slide-close pull-right"><a href="#" class="close-slide-lenguage"><img src="<?= $this->config['assets_image_url'] ?>close-icon.png"></a></span>
        </div>
    </div>
    	<!--channel-->
        <div class="list-channel-section">
        	<div class="channel-top">
                <ul class="list-channel clearfix">
                    <li class="not-channel channel-left">
                    <span class="middle-channel">KAPANLAGI NETWORK
                        <img src="<?= $this->config['assets_image_url_v2'] ?>kanan.png" class="arrow-channel" />
                    </span>
                    </li><li class="active hidden-xs">
                    <a href="http://www.brilio.net/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Brilio.net');" rel="nofollow">BRILIO.NET</a></li><li class="hidden-xs">
                    <a href="http://www.kapanlagi.com" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Kapanlagi');" rel="nofollow">KAPANLAGI</a></li><li class="hidden-xs">
                    <a href="http://www.merdeka.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Merdeka');" rel="nofollow">MERDEKA</a></li><li class="hidden-xs">
                    <a href="http://www.bola.net/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Bola.net');" rel="nofollow" >BOLA.NET</a></li><li class="visible-lg">
                    <a href="http://www.vemale.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Vemale');" rel="nofollow" >VEMALE</a></li><li class="visible-lg">
                    <a href="http://www.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela');" rel="nofollow" >FIMELA</a></li><li class="visible-lg">
                    <a href="http://www.dream.co.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Dream');" rel="nofollow" >DREAM.CO.ID</a></li><li class="not-channel channel-right">
                    <a href="javascript:void(0);" class="click-more">MORE
                        <img src="<?= $this->config['assets_image_url_v2'] ?>bawah.png" class="arrow-channel arrow-down" />
                        <img src="<?= $this->config['assets_image_url_v2'] ?>atas.png" class="arrow-channel arrow-up" />
                    </a>
                    </li>
                </ul>
            </div>
            <div class="list-channel-more">
                <ul class="list-channel clearfix">
                    <li class="active visible-xs">
                    <a href="http://www.brilio.net" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Brilio.net');" rel="nofollow" >BRILIO.NET</a></li><li class="visible-xs">
                    <a href="http://www.kapanlagi.com" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Kapanlagi');" rel="nofollow" >KAPANLAGI</a></li><li class="visible-xs">
                    <a href="http://www.merdeka.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Merdeka');" rel="nofollow" >MERDEKA</a></li><li class="visible-xs">
                    <a href="http://www.bola.net/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Bola.net');" rel="nofollow" >BOLA.NET</a></li><li class="hidden-lg">
                    <a href="http://www.vemale.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Vemale');" rel="nofollow" >VEMALE</a></li><li class="hidden-lg">
                    <a href="http://www.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela');" rel="nofollow" >FIMELA</a></li><li class="hidden-lg">
                    <a href="http://www.dream.co.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Dream.co.id');" rel="nofollow" >DREAM.CO.ID</a></li><li>
                    <a href="http://www.storibriti.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Storibriti');" rel="nofollow" >STORIBRITI</a></li><li>
                    <a href="http://girl.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela girl');" rel="nofollow" >FIMELA GIRL</a></li><li>
                    <a href="http://www.otosia.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Otosia');" rel="nofollow" >OTOSIA</a></li><li>
                    <a href="http://feed.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Feed.id');" rel="nofollow" >FEED.ID</a></li><li>
                    <a href="http://www.hemat.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Hemat');" rel="nofollow" >HEMAT</a></li><li>
                    <a href="http://www.techno.id/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Techno.id');" rel="nofollow" >TECHNO.ID</a></li><li>
                    <a href="http://www.sooperboy.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Sooperboy');" rel="nofollow" >SOOPERBOY</a></li><li>
                    <a href="http://www.muvila.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Muvila');" rel="nofollow" >MUVILA</a></li><li>
                    <a href="http://family.fimela.com/" onclick="ga('send', 'event', 'Menu channel', 'Click', 'Channel Fimela Family');" rel="nofollow" >FIMELA FAMILY</a></li>
                </ul>
            </div>
        </div>
        <!--endchannel-->
                <!--section-->
        <div class="section">
            <!--header-->
            <div class="header">
                <div class="container">
                    <div class="header-left pull-left">
                        <a href="<?php echo $this->config['base_url'] ?>"><img src="<?= $this->config['assets_image_url_v2'] ?>logo-atas.png" width="190" /></a>
                    </div>
                    <div class="header-right pull-right">
                        <ul class="list-social-bar list-unstyled clearfix">
                            <li><a href="https://www.facebook.com/BrilioDotNetID" class="fb" target="_blank" onclick="ga('send', 'event', 'Header', 'Button sosmed','Facebook', {'nonInteraction': 1});" ></a></li>
                            <li><a href="https://twitter.com/brilionet" class="twitter" target="_blank" onclick="ga('send', 'event', 'Header', 'Button sosmed','Twitter', {'nonInteraction': 1});" ></a></li>
                            <li><a href="#" class="gplus" onclick="ga('send', 'event',   'Header', 'Button sosmed','G+', {'nonInteraction': 1});"></a></li>
                            <li><a href="https://www.youtube.com/channel/UCjRH2OCntkHDJi0kIX3DZ3w" class="youtube" target="_blank" onclick="ga('send', 'event',   'Header', 'Button sosmed','Youtube', {'nonInteraction': 1});" ></a></li>
                            <li><a href="https://instagram.com/brilionet/" class="instagram" target="_blank" onclick="ga('send', 'event',   'Header', 'Button sosmed','Instagram', {'nonInteraction': 1});" ></a></li>
                            <li><a href="/feed/" class="feed" onclick="ga('send', 'event', 'Header', 'Button sosmed','RSS', {'nonInteraction': 1});" ></a></li>
                            <li><a href="<?php echo $this->config['base_url'] ?>en/" class="language" id="switch-language-top"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--endheader-->
            <!--navbar-->
            <div class="navbar-newsite">
                <div class="container">
                    <ul class="list-navbar list-unstyled pull-left clearfix">
                        <li><a href="<?= $this->config['rel_url'] ?>popular/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Popular');" >POPULAR</a></li>
                        <li><a href="<?= $this->config['rel_url'] ?>news/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'News');" >NEWS</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>life/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Life');" >LIFE</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>ngakak/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Ngakak!');" >NGAKAK!</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>selebritis/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Selebritis');" >SELEBRITIS</a></li>
                        <li class="hidden-xs"><a href="<?= $this->config['rel_url'] ?>sosok/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Sosok');" >SOSOK</a></li>
                        <li class="visible-md visible-lg"><a href="<?= $this->config['rel_url'] ?>komunitas/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Komunitas');" >KOMUNITAS</a></li>
                        <li class="visible-md visible-lg"><a href="<?= $this->config['rel_url'] ?>wow/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Wow!');" >WOW!</a></li>
                        <li class="visible-lg"><a href="<?= $this->config['rel_url'] ?>cinta/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Cinta');" >CINTA</a></li>
                        <li class="visible-lg"><a href="<?= $this->config['rel_url'] ?>duh/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Duh');" >DUH</a></li>
                        <li class="more-nav" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Button more');" ></li>
                    </ul>
                    <div class="icon-search pull-right"><a href="javascript:void(0);" class="btn-search" onclick="ga('send', 'event', 'Header', 'Search', 'Search box', {'nonInteraction': 1});"><img src="<?= $this->config['assets_image_url_v2'] ?>search-icon-white.png" width="20"></a></div>
                </div>
            </div>
            <!--endnavbar-->
            <!--search-->
            <div class="search-section">
                <div class="table-section">
                    <div class="table-middle">
                        <form class="form-search" action="<?php echo $this->config['rel_url'] ?>search-result.html" method="post">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="submit" class="icon-search"><img src="<?= $this->config['assets_image_url_v2'] ?>search-icon-white.png" width="20"></button>
                                </div>
                                <input type="text" class="form-control" name="inputSearch" placeholder="Type and Enter">
                                <div class="input-group-btn">
                                    <a href="javascript:void(0);" class="close-search"><img src="<?= $this->config['assets_image_url_v2'] ?>close-icon-Search.png"></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!--endsearch-->
            <!--menu-->
            <div class="menu-section">
                <div class="table-section">
                    <div class="table-middle">
                    	<a href="javascript:void(0);" class="close-menu"><img src="<?= $this->config['assets_image_url_v2'] ?>close-icon-menu.png"></a>
                        <ul class="list-navbar-more list-unstyled clearfix">
                            <li><a href="<?= $this->config['rel_url'] ?>popular/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Popular');" >POPULAR</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>news/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'News');" >NEWS</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>life/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Life');" >LIFE</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>ngakak/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Ngakak!');" >NGAKAK!</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>selebritis/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Selebritis');" >SELEBRITIS</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>sosok/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Sosok');" >SOSOK</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>komunitas/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Komunitas');" >KOMUNITAS</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>jorok/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Jorok!');" >JOROK!</a></li>
                            <li><a href="<?= $this->config['rel_url'] ?>global/" onclick="ga('send', 'event', 'Header', 'Men
