<!--section -->
<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <li><a href="<?= $this->config['rel_url'] ?>" onclick="ga('send', 'event', '<?= $breadcrumb['CATEGORY_TITLE'] ?> - Breadcumb', 'Click', 'Home');">HOME</a></li>
        <li>&raquo;</li>
        <li><a href="<?= $this->config['rel_url']. $breadcrumb['CATEGORY_URL'] ?>" onclick="ga('send', 'event', '<?= $breadcrumb['CATEGORY_TITLE'] ?> - Breadcumb', 'Click', '<?= $breadcrumb['CATEGORY_TITLE'] ?>');"><?= $breadcrumb['CATEGORY_TITLE'] ?></a>
    </ol>
    <div class="title-list text-left">
        <h6><?= $breadcrumb['CATEGORY_TITLE'] ?></h6>
    </div>

    <?php if (!empty($news_list['headline'])): ?>
    <div class="header-br">
        <a href="<?= $news_list['headline'][0]['news_url_full'] ?>" onclick="ga('send', 'event', 'Index category - <?= $breadcrumb['CATEGORY_TITLE']?>', 'Click', '<?= $news_list['headline'][0]['news_title'] ?>');"  class="img-headline blue">
            <img src="<?= $news_list['headline'][0]['news_image_headline'] ?>" data-src="<?= $news_list['headline'][0]['news_image_headline'] ?>" class="img-full">
        </a>
        <div class="deskrip-head-border-bottom">
          <?php if ($news_list['headline'][0]['news_tag_list']): ?>
            <div class="kategori-date">
                <a href="<?= $news_list['headline'][0]['news_tag_list'][0]['tag_url_full'] ?>" class="link-kategori"><?= strtoupper($news_list['headline'][0]['news_tag_list'][0]['tag_news_tags']) ?></a>
            </div>
          <?php endif; ?>
            <h6 class="title-head">
            <a href="<?= $news_list['headline'][0]['news_url_full'] ?>" onclick="ga('send', 'event', 'Index category - <?= $breadcrumb['CATEGORY_TITLE']?>', 'Click', '<?= $news_list['headline'][0]['news_title'] ?>');">
            <?= $news_list['headline'][0]['news_title'] ?>
            </a>
            </h6>
            <span class="date"><?= $news_list['headline'][0]['news_date_publish_indo'] ?></span>
        </div>
    </div>
    <?php endif ?>
    <!-- ./ header br -->
    <?php if ( !empty($news_list['stream_news']) ): ?>
      <?php foreach ($news_list['stream_news'] as $news => $val): ?>
        <ul class="list-article-berita list-article-small list-unstyled">
            <li>
                <div class="deskrip-br">
                    <div class="kategori-date">
                        <div class="kategori-date">
                          <?php if ( !empty($val['news_tag_list']) ): ?>
                            <a href="<?= $val['news_tag_list'][0]['tag_url_full'] ?>" class="link-kategori"><?= $val['news_tag_list'][0]['tag_news_tags'] ?></a>
                          <?php endif; ?>
                        </div>
                    </div>
                    <p class="deskrip-text"><a href="<?= $val['news_url_full'] ?>" onclick="ga('send', 'event', 'Index category - <?= $key['CATEGORY_TITLE']?>', 'Click', '<?= $val['news_title'] ?>');"><?= $val['news_title'] ?></a>
                    </p>
                    <span class="date"><?= $val['news_date_publish_indo'] ?></span>
                </div>
            </li>
        </ul>
      <?php endforeach; ?>
    <?php endif; ?>

    <ul class="list-pagination list-unstyled">
        <?= $pagination ?>
    </ul>

</div>
<!--end section-->
