<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

        <title><?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?></title>
        <meta name=description content="<?=(isset($meta['meta_description'])? html_entity_decode($meta['meta_description']) : 'Brilio.net')?>" />
        <meta name=keywords content="<?=(isset($meta['meta_keywords'])? html_entity_decode($meta['meta_keywords']) : 'brilio, temukan, segala, kisah, kehidupan, gaya, hidup, renungan, inspirasi, dan, ilmu, pengetahuan, di, sini')?>" />
        <meta http-equiv="Refresh" content="900" />
        <meta http-equiv="Expires" content="<?=(isset($meta['expires'])? $meta['expires'] : date(DATE_RFC1036))?>" />
        <meta http-equiv="last-modified" content="<?=(isset($meta['last_modifed'])? $meta['last_modifed'] : date(DATE_RFC1036))?>" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="google-site-verification" content="ULVoXU2ZG9IBdBiKMJLQhBjbyGUbnJ0T5zQoorgpsPw" />
        <link rel="canonical" href="<?= $canonical ?>" />
        <link href="<?= $this->config['assets_image_url'] ?>favicon.png" rel="shortcut icon" />
        <link rel="stylesheet" href="<?= $this->config['assets_css_url'];?>bootstrap.css">
        <link rel="stylesheet" href="<?= $this->config['assets_css_url'];?>main.css?v=<?= $this->config['assets_css_version'];?>">
        <link rel="stylesheet" href="<?= $this->config['assets_font_url'];?>font-awesome.css">

        <!--SOCMED PROPERTY-->
        <meta property="og:site_name" content="brilio.net" />
        <meta property="og:title" content="<?=(isset($meta['meta_title'])? html_entity_decode($meta['meta_title']) : 'Stories worth sharing - Brilio.net')?>" />
        <meta property="og:description" content="<?=(isset($meta['meta_description'])? html_entity_decode($meta['meta_description']) : 'Brilio.net')?>" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="<?=(isset($meta['og_url'])? $meta['og_url'] : $this->config['base_url'] )?>" />
        <meta property="og:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta property="og:image:secure_url" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta property="fb:app_id" content="834884736607990" />
        <meta property="fb:admins" content="1560920678" />

        <meta name="twitter:title" content="<?=(isset($meta['meta_title'])? html_entity_decode($meta['meta_title']) : 'Stories worth sharing - Brilio.net')?>" />
        <meta name="twitter:description" content="<?=((@$meta['meta_description'])? html_entity_decode($meta['meta_description']) : 'Brilio.net')?>" />
        <meta name="twitter:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@brilionet">
        <meta name="twitter:creator" content="@brilionet">
        <meta name="twitter:domain" content="https://twitter.com/brilionet">

        <script src="<?= $this->config['assets_js_url'];?>vendor/jquery-1.11.2.js"></script>


        <!-- Google Analytics -->
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-61119040-4', 'auto');
            ga('send', 'pageview');

            ga('create', 'UA-71408030-5', 'auto', 'KLNBrilio');
            ga('KLNBrilio.send', 'pageview');

            ga('create', 'UA-77164335-2', 'auto', 'SUBBrilio');
            ga('SUBBrilio.send', 'pageview');
        </script>

        <!-- chartbeat -->
        <script type='text/javascript'>
            var _sf_startpt=(new Date()).getTime()
        </script>
        <!-- end chartbeat -->

        <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '213022759033260');
        fbq('track', "PageView");</script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=213022759033260&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Facebook Pixel Code -->


</head>
<body>
    <div class="slide-notifikasi">
        <div class="brilio-container clearfix">
            <span class="slide-title">Would you like to switch to the English version?</span>
            <span class="slide-undo"><a href="<?=$this->config['m_url_en']?>">Yes</a></span>
            <span class="slide-close pull-right">
                <a href="#" class="close-slide-lenguage">
                    <img src="<?= $this->config['assets_image_url']?>close-icon-mob.png">
                </a>
            </span>
        </div>
    </div>
    <div class="channel-section">
        <div class="navbar-channel clearfix">
            <div class="pull-left">
                <h6 class="title-channel middle-channel">KAPANLAGI NETWORK</h6>
            </div>
            <div class="button-channel pull-right">
                <a href="javascript:void(0)" class="click-channel middle-channel">
                    <img src="<?= $this->config['assets_image_url']?>dot_aa2.png" width="3" class="icon-channel">
                    <img src="<?= $this->config['assets_image_url']?>channel_close.png" width="16" class="close-channel">
                </a>
            </div>
        </div>
        <div id="channel-collapse">
            <ul class="list-channelbar clearfix">
                <li class="active"><a href="<?= $this->config['base_url'] ?>" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel BRILIO.NET');" target="_blank" rel="nofollow">BRILIO.NET</a></li>
                <li><a href="http://m.kapanlagi.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel KAPANLAGI');" target="_blank" rel="nofollow">KAPANLAGI</a></li>
                <li><a href="http://m.bola.net/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel BOLA.NET');" target="_blank" rel="nofollow">BOLA.NET</a></li>
                <li><a href="http://m.merdeka.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel MERDEKA');" target="_blank" rel="nofollow">MERDEKA</a></li>
                <li><a href="http://m.vemale.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel VEMALE');" target="_blank" rel="nofollow">VEMALE</a></li>
                <li><a href="http://m.fimela.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel FIMELA');" target="_blank" rel="nofollow">FIMELA</a></li>
                <li><a href="http://m.otosia.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel OTOSIA');" target="_blank" rel="nofollow">OTOSIA</a></li>
                <li><a href="http://feed.id/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel FEED.ID');" target="_blank" rel="nofollow">FEED.ID</a></li>
                <li><a href="http://m.hemat.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel HEMAT');" target="_blank" rel="nofollow">HEMAT</a></li>
                <li><a href="http://m.techno.id/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel TECHNO.ID');" target="_blank" rel="nofollow">TECHNO.ID</a></li>
                <li><a href="http://m.sooperboy.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel SOOPERBOY');" target="_blank" rel="nofollow">SOOPERBOY</a></li>
                <li><a href="http://m.muvila.com/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel MUVILA');" target="_blank" rel="nofollow">MUVILA</a></li>
                <li><a href="http://m.dream.co.id/" onclick="ga('send', 'event', 'Menu Channel', 'click', 'Channel DREAM.CO.ID');" target="_blank" rel="nofollow">DREAM.CO.ID</a></li>
            </ul>
            <div class="logo-channel">
                <a href="http://www.kln.id/" target="_blank"><img src="<?= $this->config['assets_image_url']?>logo_KLN.png" width="86"></a>
            </div>
        </div>
    </div>
    <!--navbar-->

    <nav class="navbar">
        <div class="brand">
            <a href="<?= $this->config['base_url'] ?> "><img src="<?= $this->config['assets_image_url']?>logo.png">
            </a>
        </div>
        <div class="navbar-nav-icon" id="show-nav">
            <div class="menu-icon">
                <img src="<?= $this->config['assets_image_url']?>menu-icon.png">
            </div>
        </div>
        <div id="nav-drop" class="hide-nav">
            <img src="<?= $this->config['assets_image_url']?>arrow-top.png">
        </div>
        <div class="navbar-lang-icon clearfix">
            <a href="<?=  $this->config['m_url']?>" id="switch-language-top">
                <div class="lang-icon">
                    <img src="<?= $this->config['assets_image_url']?>in-button-mob.png">
                </div>
                <div class="lang-title">New!</div>
            </a>
        </div>
    </nav>
    <!--end-navbar-->

    <div id="header-nav">
    <ul>
        <?= $tags_top?>
        <li>
            <a href="#" class="header-nav-close hide-nav">Close</a>
        </li>
    </ul>
    </div>
    <?php if(!empty($box_announcer)) echo $box_announcer?>

    <script async src="<?= $this->config['assets_js_url'];?>vendor/bootstrap.min.js"></script>
    <script src="<?= $this->config['assets_js_url'];?>custom.js"></script>
    <script async src="<?= $this->config['assets_js_url'];?>vendor/modernizr.custom.27302.js"></script>
    <script async src="<?= $this->config['assets_js_url'];?>vendor/respond.js"></script>
    <script async src="<?= $this->config['assets_js_url'];?>navigator-detect.js"></script>

    <?= $content ?>

    <!--footer-->
    <footer>
        <div class="backtop">
            <a href="#0" class="cd-top"><img src="<?= $this->config['assets_image_url'] ?>Arrowbacktotop.png"> BACK TO TOP</a>
        </div>
        <div class="footer-logo">
            <a href="http://www.kln.id/">
                <img src="<?= $this->config['assets_image_url'] ?>KLN-640.png">
            </a>
        </div>
        <div class="copyright">
            <p>2016 Brillio.net
                <br>KLN Kapanlagi Network - All Rights Reserved</p>
        </div>
        <div class="footer-menu">
            <a href="#">About Brilio</a> |
            <a href="<?= $this->config['rel_url'] ?>company/redaksi">Editorial Staff</a> |
            <a href="<?= $this->config['www_url'] ?>news/kesempatan-bergabung-bersama-brilionet-sekarang-juga-1511243.html">career</a> |
            <a href="<?= $this->config['rel_url'] ?>company/sitemap">Sitemap</a>
        </div>
        <div class="footer-lang clearfix">
            <a href="#" class="footer-lang-title">New!</a>
            <a href="<?= $this->config['m_url'] ?>" class="switch-language-bottom">
                <img src="<?= $this->config['assets_image_url'] ?>in-button-mob.png">
            </a>
            <a href="<?= $this->config['rel_url'] ?>" class="switch-language-bottom">
                <img src="<?= $this->config['assets_image_url'] ?>en-button-mob.png">
            </a>
        </div>
    </footer>
    <!--end footer-->


    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id))
                return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=834884736607990";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <iframe src="//d.kapanlaginetwork.com/mga.html?<?= (isset($meta['iframe_kl'])? $meta['iframe_kl'] : 'https://www.brilio.net')?>" height="1" width="1" style="display:none;visilibity:hidden;"></iframe>

    <script type='text/javascript'>
        var ver = '1.0.3';
        var src = 'https://cdns.klimg.com/newshub.id/static/js/newshub.id/www/'+ver+'/frontend/' + 'global.js';
        document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');
    </script>

    <!-- script to count pageview when js is not active -->
    <noscript>
        <img style="display: none;" src="https://www.newshub.id/app/record_jsview/" />
    </noscript>
    <!-- end pageview counter -->

    <script type='text/javascript'>
        var _sf_async_config = {};
        /** CONFIGURATION START **/
        _sf_async_config.uid = 62012;
        _sf_async_config.domain = 'brilio.net';
        _sf_async_config.useCanonical = true;
        _sf_async_config.sections = '<?=(isset($meta["chartbeat_sections"]) ? ucwords($meta["chartbeat_sections"]) : "Homepage")?>';  //CHANGE THIS
        _sf_async_config.authors = '<?=(isset($meta["chartbeat_authors"]) ? $meta["chartbeat_authors"] : "Brilio.net")?>';    //CHANGE THIS
        /** CONFIGURATION END **/
        (function () {
            function loadChartbeat() {
                window._sf_endpt = (new Date()).getTime();
                var e = document.createElement('script');
                e.setAttribute('language', 'javascript');
                e.setAttribute('type', 'text/javascript');
                e.setAttribute('src', '//static.chartbeat.com/js/chartbeat.js');
                document.body.appendChild(e);
            }
            var oldonload = window.onload;
            window.onload = (typeof window.onload != 'function') ?
                    loadChartbeat : function () {
                        oldonload();
                        loadChartbeat();
                    };
        })();
    </script>
    <!--LOTAME PIXEL TAG-->
    <script async src="//tags.crwdcntrl.net/c/7171/cc_af.js" ></script>
    <!--END LOTAME PIXEL TAG-->

</body>

</html>
