
<div class="headline clearfix">
<?php
    if($headline):
        $no = 1;
        foreach ($headline as $data):
    ?>
    <div class="headline-box col-sm-4">
        <div style="background-image:url(<?php echo $data['news_image_location_full'] ?>);" >
            <a href="<?php echo $data['news_url'] ?>" onclick="ga('send', 'event', 'Homepage', 'Headline', 'Headline ke-<?php echo $no ?>');" class="img-click">
            </a>
            <div class="deskrip-headline">

            <?php if ( !empty($data['tag_title']) ): ?>
                <a href="<?php echo $data['tag_url'] ?>" class="link-tag" onclick="ga('send', 'event', 'Homepage', 'Headline tag', 'Headline ke-<?php echo $no ?>');" ><?php echo strtoupper( $data['tag_title'] ) ?></a>
            <?php endif ?>
                <p><a href="<?php echo $data['news_url'] ?>" onclick="ga('send', 'event', 'Homepage', 'Headline', 'Headline ke-<?php echo $no ?>');" > <?php echo $data['news_title'] ?> </a></p>
            </div>
        </div>
    </div>
    <?php
        $no++;
        endforeach;
    endif;
    ?>
</div>
<!--endheadline-->
<div class="wrapper-col">
    <div class="wrapper-left">
        <div class="article-col-left">
            <ul class="article-berita list-unstyled" id="myList">
                <?php
                if($stream_news):
                    $no =1 ;
                    foreach ($stream_news as $data):
                ?>
                        <li>
                            <a href="<?php echo $data['news_url'] ?>"
                               onclick="ga('send', 'event', 'Homepage', 'Stream article', 'Stream ke-<?= $no ?>');"
                               class="article-left">
                                <img src="<?php echo $data['news_image_location_255_170'] ?>" data-src="<?php echo $data['news_image_location_255_170'] ?>" width='278px' class="img-full lazy" id="278" onerror="imgError(this)">
                            </a>
                            <div class="deskrip-right">
                                <a href="<?php echo $data['tag_url'] ?>" class="link-kategori" onclick="ga('send', 'event', 'Homepage', 'Stream tag', 'Stream ke-<?= $no ?>');" ><?php echo $data['tag_title']; ?></a>
                                <p class="text-article">
                                    <a href="<?php echo $data['news_url'] ?>"
                                       onclick="ga('send', 'event', 'Homepage', 'Stream article', 'Stream ke-<?= $no ?>');" >
                                        <?php echo $data['news_title'] ?>
                                    </a>
                                </p>
                                <span class="date"><?php echo $data['news_date_publish'] ?></span>
                            </div>
                        </li>
                <?php
                    $no++;
                    endforeach;
                endif;
                ?>
            </ul>
        </div>
    </div>
    <!--wrapper-->
    <div class="wrapper-right">
        <?= $share_story ?>
        <?= $trending ?>
        <?= $check_this_out ?>
    </div>
</div>
<!--endwrapper-->
<!--showmore-->
<div class="showmore floating" id="loadMore" onclick="ga('send', 'event', 'Homepage', 'Show more', 'Show more');"><img src="<?= $this->config['assets_image_url_v2']; ?>brlilio-icon.png" width="42"> <br>Show More Stories</div>
<!--endshowmore-->
