<!--breadcrumb-->
<ol class="list-breadcrumb  list-unstyled">
    <li>
        <a href="<?php echo $this->config['rel_url'] ?>" onclick="ga('send', 'event', 'Index all tags - Breadcumb', 'Click', 'BRILIO.NET');">BRILIO.NET</a>
    </li>
    <li>&raquo;</li>
    <li>
        <a href="<?php echo $this->config['rel_url'] . "tag" ?>" onclick="ga('send', 'event', 'Index all tags - Breadcumb', 'Click', 'TAG');">TAG</a>
    </li>
    <li>
        <?php echo (!empty($breadcrumb['LIST_BREADCUMB']['BREADCUMB_SIMBOL']) ? $breadcrumb['LIST_BREADCUMB']['BREADCUMB_SIMBOL'] : '' ) ?>
    </li>
    <li>
        <a href="<?php echo $breadcrumb['LIST_BREADCUMB']['BREADCUMB_URL'] ?>" onclick="ga('send', 'event', 'Index all tags - Breadcumb', 'Click', '<?php echo (isset($breadcrumb['LIST_BREADCUMB']['BREADCUMB_TITLE']) ? $breadcrumb['LIST_BREADCUMB']['BREADCUMB_TITLE'] : '' ) ?>');"><?php echo (isset($breadcrumb['LIST_BREADCUMB']['BREADCUMB_TITLE']) ? $breadcrumb['LIST_BREADCUMB']['BREADCUMB_TITLE'] : '' ) ?></a>
    </li>
</ol>
<!--endbreadcrumb-->
<!--wrapper-->
<div class="wrapper-col">
    <div class="wrapper-left">
        <?php
        if(!empty($list_tag['PESAN']))
        {
            ?>
            <span class="pesan-error"><?php echo $list_tag['PESAN'] ?></span>
            <?php
        }
        else
        {
            // BOX FIRST
            $data = $list_tag[0]['LIST_LEFT'];
            ?>
            <div class="title-middle-line">
                <h6>RECENT TAGS</h6>
            </div>
            <div class="article-col-left">
                <div class="article-trending">
                    <div class="header-trending clearfix">
                        <a href="<?php echo $data['TAG_LINK_URL']; ?>" class="title-trending" onclick="ga('send', 'event', '<?= $TE ?>', 'Stream', 'tags ke-1');">
                            <?php echo $data['TAGS_NEWS_TAGS']; ?>
                        </a>
                    </div>
                    <div class="article-content-trending clearfix">
                        <div class="trending-box-left">
                            <a href="<?php echo $data['NEWS_URL'] ?>" class="img-block" onclick="ga('send', 'event', '<?= $TE ?>', 'Big article', 'tags ke-1 ?>');">
                                <img src="<?php echo $data['NEWS_IMG'] ?>" class="lazy" onerror="this.src='<?= $this->config['assets_image_url']?>default-360x180.jpg'">
                            </a>
                            <div class="deskrip-block">
                                <h5>
                                    <a href="<?php echo $data['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Alphabetical tag', 'Big article', 'tags ke-1');">
                                        <?php echo $data['NEWS_TITLE'] ?>
                                    </a>
                                </h5>
                            </div>
                        </div>
                        <ul class="list-circle-trending list-unstyled">
                            <?php
                            if(!empty($list_tag[0]['LIST_RIGHT']))
                            {
                                $no = 1 ;
                                foreach ($list_tag[0]['LIST_RIGHT'] as $data_right)
                                {
                                    ?>
                                        <li>
                                            <span class="date"><?php echo $data_right['NEWS_TIME_RIGHT'] ?></span>
                                            <a href="<?php echo $data_right['NEWS_URL'] ?>" class="link-berita"
                                               onclick="ga('send', 'event', '<?= $TE ?>', 'Article', 'Artikel ke-<?= $no ?>');">
                                                <?php echo $data_right['NEWS_TITLE_RIGHT'] ?>
                                            </a>
                                        </li>
                                    <?php
                                    $no++;
                                }

                            }
                            ?>
                            <li class="more-box">
                                <a href="<?php echo $list_tag[0]['MORE_UPDATE_URL'] ?>" onclick="ga('send', 'event', '<?= $TE ?>', 'More Update', 'more update');" class="more-update">
                                    <?php echo $list_tag[0]['TOTAL_NEWS'] ?> More Updates
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="article-col-left">
                <h5 class="title-single title-single-md">TAGS ALPHABETICAL</h5>
                <ul class="list-alphabet list-unstyled clearfix">
                    <li class="active"></li>
                    <!-- {LIST_ALPABET} -->
                    <?php
                    foreach ($list_alphabet['LIST_ALPHABET'] as $val_alpabet)
                    {
                        ?>
                        <li class="<?php echo $val_alpabet['TAGS_AKTIF']; ?>">
                            <a href="<?php echo $this->config['rel_url'] ?>tag/<?php echo $val_alpabet['ALPHABET'] ?>/"
                                onclick="ga('send', 'event', 'Index all tag', 'Alphabetical box', '<?php echo $val_alpabet['ALPHABET'] ?>');">
                                <?php echo $val_alpabet['ALPHABET'] ?>
                            </a>
                        </li>
                        <?php
                    }
                    ?>
                    <li>
                        <a href="<?php echo $this->config['base_url'] ?>tag/num/">#</a>
                    </li>
                </ul>
            </div>
            <?php
            $no = 1;
            foreach ($list_tag as $data)
            {
                if($no != 1)
                {
                    if(!empty($data['LIST_LEFT']))
                    {
                        $value_second = $data['LIST_LEFT'];
                        ?>
                        <div class="article-col-left">
                            <div class="article-trending">
                                <div class="header-trending clearfix">
                                    <a href="<?php echo $value_second['TAG_LINK_URL'] ?>" class="title-trending"
                                       onclick="ga('send', 'event', '<?= $TE ?>', 'Stream', 'tags ke-<?= $value_second['TAGS_NEWS_TAGS'] ?>');" >
                                        <?php echo $value_second['TAGS_NEWS_TAGS'] ?>
                                    </a>
                                </div>
                                <div class="article-content-trending clearfix">
                                    <div class="trending-box-left">
                                        <a href="<?php echo $value_second['NEWS_URL'] ?>" class="img-block" onclick="ga('send', 'event', '<?= $TE ?>', 'Big article', 'tags ke-<?= $value_second['TAGS_NEWS_TAGS'] ?>');">
                                            <img src="<?php echo $value_second['NEWS_IMG'] ?>" class="lazy" onerror="this.src='<?= $this->config['assets_image_url']?>default-360x180.jpg'">
                                        </a>
                                        <div class="deskrip-block">
                                            <h5>
                                                <a href="<?php echo $value_second['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Index all tag', 'Big article', 'tags ke-<?= $value_second['TAGS_NEWS_TAGS'] ?>');" >
                                                    <?php echo $value_second['NEWS_TITLE'] ?>
                                                </a>
                                            </h5>
                                        </div>
                                    </div>
                                    <ul class="list-circle-trending list-unstyled">
                                        <?php
                                        if (!empty($data['LIST_RIGHT']))
                                        {   $no = 1;
                                            foreach ($data['LIST_RIGHT'] as $val_right_second)
                                            {
                                                ?>
                                                    <li>
                                                        <span class="date"><?php echo $val_right_second['NEWS_TIME_RIGHT'] ?></span>
                                                        <a href="<?php echo $val_right_second['NEWS_URL'] ?>" onclick="ga('send', 'event', '<?= $TE ?>', 'Article', 'Artikel ke-<?= $no ?>');" class="link-berita">
                                                            <?php echo $val_right_second['NEWS_TITLE_RIGHT'] ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            $no++;
                                            }
                                        }
                                        ?>
                                        <li>
                                            <a href="<?php echo $data['MORE_UPDATE_URL'] ?>" onclick="ga('send', 'event', '<?= $TE ?>', 'More Update', 'more update');" class="more-update">
                                                <?php echo $data['TOTAL_NEWS'] ?> More Updates
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                }
                $no++;
            }
        }
        ?>
        <ul class="list-pagination list-unstyled clearfix">
            <?php echo $list_tag['PAGINATION']; ?>
        </ul>
    </div>
    <div class="wrapper-right">
        <?php echo $collect_email ?>
        <?php echo $editor_picks ?>
        <?php echo $popular_tags ?>
        <div class="article-col-right">
            <div class="fb-page" data-href="https://www.facebook.com/BrilioDotNetID" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false">
                <div class="fb-xfbml-parse-ignore">
                    <blockquote cite="https://www.facebook.com/BrilioDotNetID">
                        <a href="https://www.facebook.com/BrilioDotNetID">Brilio</a>
                    </blockquote>
                </div>
            </div>
        </div>
        <?php echo $just_update ?>
        <?php echo $check_this_out ?>
    </div>
</div>
<!--endwrapper-->
