<div style="position: absolute; left: 0; right: 0; width: 100%; border-bottom: 1px solid #ececec;"></div>
    <div class="section clearfix">
        <ol class="list-breadcrumb list-unstyled">
            <li>
                <a href="<?php echo $this->config['base_url'] ?>" onclick="ga('send', 'event', 'Carrer - Breadcumb', 'Click', 'Home');">Home</a>
            </li>
            <li>&raquo;</li>
            <li>
                <a href="#">Company</a>
            </li>
            <li>&raquo;</li>
            <li>
                <a href="<?php echo $this->config['base_url'] ?>company/karir/" onclick="ga('send', 'event', 'Carrer - Breadcumb', 'Click', 'news');">Carrer</a>
            </li>    
        </ol>
    </div>
    <div class="karir-img"><img src="{IMG_URL}image-web.jpg"></div>
    <div class="karir-content">
        <div class="karir-content-box karir-border-bottom">
            <div class="karir-content-box-title">VIDEO CONTENT PRODUCTION</div>
            <div class="karir-content-box-description">
                <b>Urgently needed</b>, 5 candidates for <b>Brilio.net</b> video content production<br>
                <ul>
                    <li>- 1 Scriptwriter</li>
                    <li>- 1 Producer</li>
                    <li>- 1 Director</li>
                    <li>- 1 Graphic designer (special effects)</li>
                    <li>- 1 Video editor</li>
                </ul>
                <br>
                <b>Requirements:</b><br>
                <ul>
                    <li>- Male/Female, preferably of age under 30 years old</li>
                    <li>- Min. diploma/bachelor's degree</li>
                    <li>- Ready to work on full time position in Yogyakarta</li>
                    <li>- Dynamic, creative and aware of what's trending and current topics</li>
                    <li>- Ready to work under pressure of deadline</li>
                </ul>
                Send your application letter, CV, and portfolio to <b>redaksi@brilio.net</b>            

            </div>
        </div>
        <div class="karir-content-box karir-border-bottom">
            <div class="karir-content-box-title">WEB PRODUCT DEVELOPMENT</div>
            <div class="karir-content-box-description">
                <ul>
                    <li>- Being able to provide or generating ideas for product development</li>
                    <li>- Able to convert concept or ideas into wireframes</li>
                    <li>- Familiar and have high interest with mobile, apps, website and online activities</li>
                    <li>- Having good taste in design layouts</li>
                    <li>- Have passion of research, development and concepting</li>
                    <li>- Willing to full-time working in Malang</li>
                    <li>- Preferably those who have experience in IT/Computer software or equivalent</li>
                </ul>

                Send your application letter, CV, and portfolio to <b>tito@kapanlagi.net</b>            

            </div>
        </div>
        <div class="karir-content-box">
            <div class="karir-content-box-title">IT PROGRAMMER</div>
            <div class="karir-content-box-description">
                <ul>
                    <li>- High skill in PHP and MySQL.</li>
                    <li>- PHP Web Programmer: Solid knowledge of XHTML, CSS and JQuery.</li>
                    <li>- Have experience in CodeIgniter or Laravel.</li>
                    <li>- Comfortable to work in a TEAM (not individually).</li>
                    <li>- Able to work well under pressure.</li>
                    <li>- Have a high attention to detail and ZERO-tolerance approach to errors.</li>
                </ul>

                Send your application letter, CV, and portfolio to <b>adi@kapanlagi.net</b>           

            </div>
        </div>
    </div>