<div class="kolom-brand">
<div class="kolom-brand-brilio"><img src="<?= $this->config['assets_image_url'] ?>logo-brilio-detil-artikel-mobile.png"></div>
<div class="kolom-brand-add">+</div>
<div class="kolom-brand-partner">
<a href="<?= !empty($brand['brand_url']) ? $brand['brand_url'] : $brand['tag_brand_url']  ?>" target="_blank" onclick="ga('send', 'event', '<?= $TE ?>', 'Logo brand', '<?= !empty($brand['brand_url']) ? $brand['brand_url'] : $brand['tag_brand_url'] ?>')" >
	<img style="max-height:50px; max-width:110px;" src="<?= $brand['brand_image'] ?>">
</a>
</div>
</div>