<div class="brilio-header-billboard clearfix">
        <div class="brilio-header-billboard-wording-gateway" style="padding-top:8px; padding-bottom:10px;">

            <a href="http://bit.ly/BrilioJombloAnnouncement" onclick="ga('send', 'event', 'Header', 'Announcement bar', 'Microsite jomblo', {'nonInteraction': 1});" target="_blank">
                Tonton perjuangan 10 jombloers yang bertransformasi menjadi jomblo yang berkualitas demi mendapatkan pujaan hatinya di sini!
            </a>
        </div>
</div>
