<?php
    $WORDING_TITLE = "MASIH PILIH-PILIH CERITA?";
    $WORDING_DESCRIPTION = "Biarkan Brilio yang rekomendasikan & mengirim cerita terbaik untukmu!";
    $WORDING_BUTTON_YES = "Setuju, kirimkan ke saya";
    $WORDING_BUTTON_NO = "Nanti saja, ingatkan saya besok";
?>
<link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
<link href='<?= $this->config['assets_css_url']?>collect.css' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="<?= $this->config['assets_js_url']?>collect.js"></script>
<!--collect-email-->
<div class="collect-email" id="collect-start">
    <div id="data"></div>
    <a href="javascript:void(0)" class="close-collect"><img src="<?= $this->config['assets_image_url']?>close.png" width="16" /></a>
    <div class="section-collect">
        <h6 class="title-collect"><?= $WORDING_TITLE ?></h6>
        <p class="text-collect"><?= $WORDING_DESCRIPTION ?></p>
        <form class="form-collect-email" method="post" name="form" action="">
            <input type="text" class="form-collect" id="email" placeholder="Isi email kamu di sini" />
            <button type="submit" class="btn-collect" id="btn_collect"><?= $WORDING_BUTTON_YES ?></button>
            <div class="btn-no">
                <a href="javascript:void(0)" class="btn-collect-no"><?= $WORDING_BUTTON_NO ?></a>
            </div>
        </form>
    </div>
</div>
<!--end collect email-->
<div id="flash"></div>
<div id="display"></div>
<!--collect-email-->
<div class="collect-email" id="collect-done">
    <a href="javascript:void(0)" class="close-collect-done"><img src="<?= $this->config['assets_image_url']?>close.png" width="16" /></a>
    <div class="section-collect">
        <h6 class="title-collect">Terima Kasih!</h6>
        <p class="text-collect">Proses berhasil, email kamu sudah sukses terdaftar</p>
    </div>
</div>
<!--end collect email-->
