<div class="section clearfix">
  <div class="bg-list-tag">
    <ul class="list-tag list-unstyled">
        <li><a href="<?php echo $this->config['base_url'] ?>popular/" onclick="ga('send', 'event', '<?php echo $_list['TE'] ?>', 'Menu bar', 'Popular');" >POPULAR</a></li>
      <?php foreach ($_list['list_cat'] as $key): ?>
        <?php
          $raw_key = $key;
          $key = str_replace('!', '', $key);
          $key = str_replace(' ', '-', $key);
        ?>
        <li><a href="<?php echo $this->config['base_url'].strtolower($key) ?>/" onclick="ga('send', 'event', '<?php echo $_list['TE'] ?>', 'Category', '<?php echo ucwords($raw_key) ?>');" ><?php echo strtoupper($raw_key) ?></a></li>
      <?php endforeach; ?>
    </ul>
  </div>
      <a href="javascript:void(0);" class="show-tag"></a>
</div>
