<div class="bottom-tags-title">
    <div class="bottom-tags-title-line"></div>
    <div class="bottom-tags-title-name">MOST POPULAR</div>
</div>

<div class="box-float">
    <ul class="list-article-berita list-number list-unstyled">
    <?php
    if(!empty($list_trending)):
        foreach ($list_trending as $key): ?>
    <li>
        <div class="article-left"><?= $key['NO'] ?></div>
        <div class="deskrip-br-popular">
            <p class="deskrip-text">
                <a href="<?= $key['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Homepage - Most popular', 'Click', '<?= $key['NEWS_TITLE'] ?>');" class="popular"><?= $key['NEWS_TITLE'] ?></a>
            </p>
        </div>
    </li>
    <?php
        endforeach;
    endif;?>
    </ul>
</div>
