<div class="kolom-brand">
<div class="kolom-brand-brilio"><amp-img width="101" height="24" src="<?= $this->config['assets_image_url'] ?>logo-brilio-detil-artikel-mobile.png"></amp-img></div>
<div class="kolom-brand-add">+</div>
<div class="kolom-brand-partner">
<a href="<?= !empty($brand['brand_url']) ? $brand['brand_url'] : $brand['tag_brand_url']  ?>" target="_blank" onclick="ga('send', 'event', '<?= $TE ?>', 'Logo brand', '<?= !empty($brand['brand_url']) ? $brand['brand_url'] : $brand['tag_brand_url'] ?>')" >
	<amp-img width="110" height="50" src="<?= $brand['brand_image'] ?>"></amp-img>
</a>
</div>
</div>
