<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

        <title><?=(isset($meta['meta_title'])? $meta['meta_title'] : 'Stories worth sharing - Brilio.net')?></title>
        <meta name=description content="<?=(isset($meta['meta_description'])? html_entity_decode($meta['meta_description']) : 'Brilio.net')?>" />
        <meta name=keywords content="<?=(isset($meta['meta_keywords'])? html_entity_decode($meta['meta_keywords']) : 'brilio, temukan, segala, kisah, kehidupan, gaya, hidup, renungan, inspirasi, dan, ilmu, pengetahuan, di, sini')?>" />
        <meta http-equiv="Refresh" content="900" />
        <meta http-equiv="Expires" content="<?=(isset($meta['expires'])? $meta['expires'] : date(DATE_RFC1036))?>" />
        <meta http-equiv="last-modified" content="<?=(isset($meta['last_modifed'])? $meta['last_modifed'] : date(DATE_RFC1036))?>" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="google-site-verification" content="ULVoXU2ZG9IBdBiKMJLQhBjbyGUbnJ0T5zQoorgpsPw" />
        <link rel="canonical" href="<?= $canonical ?>" />
        <link href="<?= $this->config['assets_image_url'] ?>favicon.png" rel="shortcut icon" />
        <link rel="stylesheet" href="<?= $this->config['assets_css_url'];?>bootstrap.css">
        <?php if (ENVIRONTMENT == 'development'): ?>
          <link rel="stylesheet" href="<?= $this->config['assets_css_url'];?>localmain.css">
        <?php else: ?>
          <link rel="stylesheet" href="<?= $this->config['assets_css_url'];?>main.css">
        <?php endif; ?>

        <link rel="stylesheet" href="<?= $this->config['assets_font_url'];?>font-awesome.css">

        <!--SOCMED PROPERTY-->
        <meta property="og:site_name" content="brilio.net" />
        <meta property="og:title" content="<?=(isset($meta['meta_title'])? html_entity_decode($meta['meta_title']) : 'Stories worth sharing - Brilio.net')?>" />
        <meta property="og:description" content="<?=(isset($meta['meta_description'])? html_entity_decode($meta['meta_description']) : 'Brilio.net')?>" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="<?=(isset($meta['og_url'])? $meta['og_url'] : $this->config['base_url'] )?>" />
        <meta property="og:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta property="og:image:secure_url" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta property="fb:app_id" content="834884736607990" />
        <meta property="fb:admins" content="1560920678" />

        <meta name="twitter:title" content="<?=(isset($meta['meta_title'])? html_entity_decode($meta['meta_title']) : 'Stories worth sharing - Brilio.net')?>" />
        <meta name="twitter:description" content="<?=((@$meta['meta_description'])? html_entity_decode($meta['meta_description']) : 'Brilio.net')?>" />
        <meta name="twitter:image" content="<?= (isset($meta['og_image_secure']) ? $meta['og_image_secure'] : $this->config['assets_image_url'].'logo-BRILIO.png' ) ?>" />
        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@brilionet">
        <meta name="twitter:creator" content="@brilionet">
        <meta name="twitter:domain" content="https://twitter.com/brilionet">

        <script src="<?= $this->config['assets_js_url'];?>vendor/jquery-1.11.2.js"></script>


        <!-- Google Analytics -->
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-77164335-1', 'auto');
            ga('send', 'pageview');

            ga('create', 'UA-71408030-5', 'auto', 'KLNBrilio');
            ga('KLNBrilio.send', 'pageview');

            //ga('create', 'UA-77164335-1', 'auto', 'SUBBrilio'); // old GA UA-61119040-2
            //ga('SUBBrilio.send', 'pageview');
        </script>

        <!-- chartbeat -->
        <script type='text/javascript'>
            var _sf_startpt=(new Date()).getTime()
        </script>
        <!-- end chartbeat -->

        <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '213022759033260');
        fbq('track', "PageView");</script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=213022759033260&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Facebook Pixel Code -->

</head>
<body>
    <div class="slide-notifikasi">
        <div class="brilio-container clearfix">
            <span class="slide-title">Would you like to switch to the English version?</span>
            <span class="slide-undo"><a href="<?=$this->config['m_url_en']?>">Yes</a></span>
            <span class="slide-close pull-right">
                <a href="#" class="close-slide-lenguage">
                    <img src="<?= $this->config['assets_image_url']?>close-icon-mob.png">
                </a>
            </span>
        </div>
    </div>
    <!--navbar-->
    <!-- nav -->
	   <div class="navbar clearfix">
		<a href="<?php echo $this->config['m_url'] ?>" class="header-logo pull-left">
			<img src="<?php echo $this->config['assets_image_url'] ?>logo.png" height="45">
		</a>
		<a href="<?php echo $this->config['m_url_en'] ?>" class="lang-icon pull-right" onclick="ga('send', 'event', 'Header', 'Switch language', 'English');" target="_blank">
			<img src="<?php echo $this->config['assets_image_url'] ?>en-button-mob.png" height="30">
		</a>
		<a href="javascript:void(0);" class="menu-img">
			<span class="icon-svg icon-menu"></span>
		</a>
	</div>

    <!-- dropdownn -->
  	<div class="collapse">
      	<div class="sosmed-close clearfix">
              <div class="menu-sosmed pull-left">
                  <a href="https://www.facebook.com/BrilioDotNetID" class="mensos-fb"  onclick="ga('send', 'event', 'Header', 'Button sosmed', 'Facebook', {'nonInteraction': 1});" target="_blank" ></a>
                  <a href="https://twitter.com/brilionet" class="mensos-twitter"  onclick="ga('send', 'event',  'Header', 'Button sosmed','Twitter', {'nonInteraction': 1});" target="_blank" ></a>
                  <a href="https://instagram.com/brilionet/" class="mensos-ig"  onclick="ga('send', 'event', 'Header', 'Button sosmed','Instagram', {'nonInteraction': 1});" target="_blank" ></a>
                  <a href="https://www.youtube.com/channel/UCjRH2OCntkHDJi0kIX3DZ3w" class="mensos-youtube"  onclick="ga('send', 'event', 'Header', 'Button sosmed','Youtube', {'nonInteraction': 1});" target="_blank" ></a>
              </div>
              <a href="javascript:void(0);" class="close-nav pull-right">
                  <span class="icon-svg icon-close"></span>
              </a>
          </div>
          <div class="form-grup">
            <form class="" action="<?php echo $this->config['base_url'] ?>search-result.html" method="post">
              <input id="searchbar" name="inputSearch" class="search-menu error" type="text" onclick="ga('send', 'event', 'Header', 'Search', 'Search box'', {'nonInteraction': 1});">
              <div class="search-placeholder"><span class="icon-svg icon-search"></span> Search</div>
            </form>
          </div>
  		<ul class="menu-tablet list-unstyled clearfix">
              <li><a href="<?php echo $this->config['base_url'] ?>popular/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Popular');"  >POPULAR</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>news/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'News');" >NEWS</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>life/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Life');"  >LIFE</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>ngakak/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Ngakak!');"  >NGAKAK!</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>selebritis/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Selebritis');"  >SELEBRITIS</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>sosok/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Sosok');"  >SOSOK</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>komunitas/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Komunitas');"  >KOMUNITAS</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>jorok/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Jorok!');"  >JOROK!</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>global/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Global');"  >GLOBAL</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>duh/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Duh!');"  >DUH!</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>binatang/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Binatang');"  >BINATANG</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>cinta/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Cinta');"  >CINTA</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>gadget/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Gadget');"  >GADGET</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>wow/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Wow!');"  >WOW!</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>bayi/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Bayi');"  >BAYI</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>kesehatan/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Kesehatan');"  >KESEHATAN</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>olahraga/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Olahraga');"  >OLAHRAGA</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>cewek/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Cewek');"  >CEWEK</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>cowok/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Cowok');"  >COWOK</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>jalan-jalan/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Jalan-Jalan');"  >JALAN-JALAN</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>politik/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Politik');"  >POLITIK</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>ekonomi/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Ekonomi');"  >EKONOMI</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>fashion/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Fashion');"  >FASHION</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>orang-tua/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Orang Tua');"  >ORANG TUA</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>musik/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Musik');"  >MUSIK</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>ilmiah/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Ilmiah');"  >ILMIAH</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>serius/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Serius');"  >SERIUS</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>kepribadian/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Kepribadian');"  >KEPRIBADIAN</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>sosialita/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Sosialita');"  >SOSIALITA</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>rumah/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Rumah');"  >RUMAH</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>film/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Film');"  >FILM</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>kuliner/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Kuliner');"  >KULINER</a></li>
              <li><a href="<?php echo $this->config['base_url'] ?>serem/" onclick="ga('send', 'event', 'Header', 'Menu bar', 'Serem');"  >SEREM</a></li>
         		<li class="close-main-menu"><a href="javascript:void(0);">Close</a></li>
  		</ul>
  	</div>
    <!--end-navbar-->

    <div id="header-nav">
    <ul>
        <?= $tags_top?>
        <li>
            <a href="#" class="header-nav-close hide-nav">Close</a>
        </li>
    </ul>
    </div>
    <?php if(!empty($box_announcer)) echo $box_announcer?>

    <script type="text/javascript">
      var rel_img_url = '<?=$this->config['assets_image_url'] ?>';
    </script>
    <script async src="<?= $this->config['assets_js_url'];?>vendor/bootstrap.min.js"></script>
    <script src="<?= $this->config['assets_js_url'];?>custom.js"></script>
    <script async src="<?= $this->config['assets_js_url'];?>vendor/modernizr.custom.27302.js"></script>
    <script async src="<?= $this->config['assets_js_url'];?>vendor/respond.js"></script>
    <script async src="<?= $this->config['assets_js_url'];?>navigator-detect.js"></script>
    <!-- <script async src="<?= $this->config['assets_js_url'];?>plugin.js"></script> -->

    <?= $content ?>


    <!--footer-->
    <footer>
      <div class="backtop">
          <a href="#0" class="cd-top"><img src="<?= $this->config['assets_image_url'] ?>Arrowbacktotop.png"> BACK TO TOP</a>
      </div>
        <div class="copyright">
            <p>2016 Brillio.net
                <br>KLN Kapanlagi Network - All Rights Reserved</p>
        </div>
        <div class="footer-menu">
            <a href="#">About Brilio</a> |
            <a href="<?= $this->config['rel_url'] ?>company/redaksi">Redaksi</a> |
            <a href="<?= $this->config['www_url'] ?>news/kesempatan-bergabung-bersama-brilionet-sekarang-juga-1511243.html">Karir</a> |
            <a href="<?= $this->config['rel_url'] ?>company/sitemap">Sitemap</a>
        </div>
        <div class="footer-lang clearfix">
            <a href="<?= $this->config['m_url_en'] ?>" class="switch-language-bottom" onclick="ga('send', 'event', 'Header', 'Switch language', 'English');" target="_blank" >
                <img src="<?= $this->config['assets_image_url'] ?>en-button-mob.png">
            </a>
            <a href="<?= $this->config['rel_url'] ?>" class="switch-language-bottom" onclick="ga('send', 'event', 'Header', 'Switch language', 'Indonesia');" target="_blank" >
                <img src="<?= $this->config['assets_image_url'] ?>in-button-mob.png">
            </a>
        </div>
    </footer>
    <!--end footer-->

    <script async src="<?= $this->config['assets_js_url'];?>stacktable.js"></script>

    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id))
                return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=834884736607990";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <iframe src="//d.kapanlaginetwork.com/mga.html?<?= (isset($meta['iframe_kl'])? $meta['iframe_kl'] : 'https://www.brilio.net')?>" height="1" width="1" style="display:none;visilibity:hidden;"></iframe>

    <script type='text/javascript'>
        var ver = '1.0.3';
        var src = 'https://cdns.klimg.com/newshub.id/static/js/newshub.id/www/'+ver+'/frontend/' + 'global.js';
        document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');
    </script>

    <!-- script to count pageview when js is not active -->
    <noscript>
        <img style="display: none;" src="https://www.newshub.id/app/record_jsview/" />
    </noscript>
    <!-- end pageview counter -->

    <script type='text/javascript'>
        var _sf_async_config = {};
        /** CONFIGURATION START **/
        _sf_async_config.uid = 62012;
        _sf_async_config.domain = 'brilio.net';
        _sf_async_config.useCanonical = true;
        _sf_async_config.sections = '<?=(isset($meta["chartbeat_sections"]) ? ucwords($meta["chartbeat_sections"]) : "Homepage")?>';  //CHANGE THIS
        _sf_async_config.authors = '<?=(isset($meta["chartbeat_authors"]) ? $meta["chartbeat_authors"] : "Brilio.net")?>';    //CHANGE THIS
        /** CONFIGURATION END **/
        (function () {
            function loadChartbeat() {
                window._sf_endpt = (new Date()).getTime();
                var e = document.createElement('script');
                e.setAttribute('language', 'javascript');
                e.setAttribute('type', 'text/javascript');
                e.setAttribute('src', '//static.chartbeat.com/js/chartbeat.js');
                document.body.appendChild(e);
            }
            var oldonload = window.onload;
            window.onload = (typeof window.onload != 'function') ?
                    loadChartbeat : function () {
                        oldonload();
                        loadChartbeat();
                    };
        })();
    </script>
    <!--LOTAME PIXEL TAG-->
    <script async src="//tags.crwdcntrl.net/c/7171/cc_af.js" ></script>
    <!--END LOTAME PIXEL TAG-->
</body>

</html>
