<!--section -->
<link rel="stylesheet" href="<?= $this->config['assets_css_url'] ?>detail.css?v=<?= $this->config['assets_css_version'] ?>" >
<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <!-- {BREADCUMB}-->
        <li>
            <a href="<?php echo  $this->config['rel_url'] ?>" onclick="ga('send', 'event', 'Detail foto - Breadcumb', 'Click', 'Home');">Home</a>
        </li>
        <li>&raquo;</li>
        <li>
            <a href="<?php echo  $this->config['rel_url'] . $BREADCRUMB['CATEGORY_URL'] ?>" onclick="ga('send', 'event', 'Detail foto - Breadcumb', 'Click', '<?php echo  $BREADCRUMB['CATEGORY_TITLE'] ?>');">
                    <?php echo  $BREADCRUMB['CATEGORY_TITLE'] ?>
            </a>
        </li>
        <!-- end {BREADCUMB}-->
    </ol>
    <!-- {NEWS} -->
    <ul class="share-fixed list-unstyled">
        <li class="fb">
            <a href="<?php echo $news_data['FACEBOOK_SHARE'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                return false" class="fb">
                <div class="fb-icon"></div>
            </a>
        </li>
        <li class="twit">
            <a href="<?php echo $news_data['TWITTER_SHARE'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                return false" class="twit">
                <div class="tw-icon"></div>
            </a>
        </li>
        <li class="wa">
            <a href="<?php echo $news_data['WA_SHARE'] ?>" data-action="share/whatsapp/share" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                return false" class="wa">
                <div class="wa-icon"></div>
            </a>
        </li>
    </ul>
    <div class="detail-br">
        <div class="headline-detail">
            <span class="date"><?php echo  $news_data['news_date'] ?></span>
            <h1><?php echo  $news_data['news_title']; ?></h1>
            <span class="read-sinopsis">
                <?php
                if ($news_data['nav_paging_photos']['visit_images_number'] == 1)
                {
                    echo html_entity_decode($news_data['news_synopsis']);
                }
                ?>
            </span>
            <span class="writer"><?php echo $news_data['reporter'] ?></span>

        </div>
        <!-- {IMAGES_HEADLINE} -->
        <?php
        if(isset($news_data['images_headline'])) {
            ?>
                <div class="img-detail">
                    <img src="<?php echo  $news_data['images_headline']['news_image_url'] ?>" class="img-full">
                    <span class="img-copy"><?php echo  $news_data['images_headline']['news_imageinfo'] ." . ". $news_data['images_headline']['photonews_copyright'] ?></span>
                </div>
            <?php
        }
        ?>
        <!-- end {IMAGES_HEADLINE} -->
        <div class="body-paragraph">
            <div class="sosmed-box">
                <!-- social share container -->
                <div id="social-share"></div>
                <!-- social share container -->
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('#social-share').socialShare({
                            url: "<?php echo $news_data['url_share']; ?>",
                            twitter_user: "brilionet",
                            platform     : "m",
                        });
                    });
                </script>
            </div>
            <p>
                <!-- {NEWS_CONTENT} -->
                <?php
                if ($news_data['nav_paging_photos']['visit_images_number'] == 1):
                    echo html_entity_decode($news_data['news_content']);
                endif
                ?>
                <!-- end {NEWS_CONTENT} -->

            </p>
        </div>
        <div class="img-detail-foto">
            <div class="img-foto">
                <img src="<?php echo $news_data['data_photos_visited']['photonews_image_url'] ?>" class="img-full">
            </div>
            <p><?php echo $news_data['data_photos_visited']['photonews_description'] ?></p>
            <p class='copy'><?php echo $news_data['data_photos_visited']['photonews_copyright'] ?></p>
            <!-- {NAV_LIST_PHOTOS} -->
            <div class="artikel-paging-number text-center clearfix">
                <div class="arrow-number-l pull-left">
                    <a href="<?php echo $news_data['nav_paging_photos']['prev_photonews_url'] ?>" onclick="ga('send', 'event', 'Detail foto - Prev next', 'Click', 'PREV');"><span class="arrow-br arrow-left"></span></a>
                </div>
                <div class="number"><?php echo $news_data['nav_paging_photos']['visit_images_number']."/".$news_data['nav_paging_photos']['total_images'] ?></div>
                <div class="arrow-number-r pull-right">
                    <a href="<?php echo $news_data['nav_paging_photos']['next_photonews_url'] ?>" onclick="ga('send', 'event', 'Detail foto - Prev next', 'Click', 'NEXT');"><span class="arrow-br arrow-right"></span></a>
                </div>
            </div>
            <!-- end {NAV_LIST_PHOTOS} -->
            <p>
                <!-- INITIAL EDITR -->
                <?php echo  $news_data['initial_editor']; ?>
                <!-- end INITIAL EDITR -->
            </p>
        </div>
        <?php echo $video; ?>
        <div class="social-like-box">
            <div class="social-like">
                Klik
                <div class="fb-like" data-href="https://www.facebook.com/BrilioDotNet" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div> untuk Artikel ini
            </div>
        </div>
        <ul class="detail-box list-tag list-unstyled">
            <!-- {LIST_TAG} -->
            <?php
            if(isset($news_data['list_tag'])) {
                foreach ($news_data['list_tag'] as $data) {
                    ?>
                        <li>
                            <a href="<?php echo $data['tag_link'] ?>" onclick="ga('send', 'event', 'Detail foto - Tags article', 'Click', '<?php echo $data['tag_news_title'] ?>');" target="_blank"><?php echo $data['tag_news_title'] ?></a>
                        </li>
                    <?php
                }

            }//if
            if ( !empty($news_data['sponsor_tag']) )
            {
                $key= $news_data['sponsor_tag'] ;
            ?>
                <li>
                    <a href="<?= $key['tag_brand_url'] ?>" onclick="ga('send', 'event', '<?= $TE_2 ?>', 'Tag article', 'Brands');" target="_blank"><?= $key['tag_name'] ?></a>
                </li>
            <?php
            }//if
            ?>
            <!-- end {LIST_TAG} -->
        </ul>
        <div class="detail-box text-center">
            <h6 class="title-black">SHARE NOW</h6>
            <ul class="list-share list-unstyled">
                <li>
                    <a href="<?php echo $news_data['FACEBOOK_SHARE'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                        return false" class="fb"></a>
                </li>
                <li>
                    <a href="<?php echo $news_data['TWITTER_SHARE'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                        return false" class="twit"></a>
                </li>
                <li>
                    <a href="<?php echo $news_data['WA_SHARE'] ?>" onclick="window.open(this.href, 'child', 'scrollbars,width=600,height=260');
                        return false" class="wa"></a>
                </li>
            </ul>
        </div>
        <div class="read-gateway">
            <div class="read-gateway-img">
                            <a href="http://storytelling.brilio.net/" onclick="ga('send', 'event', 'Detail foto - Gateway story telling ', 'Click', 'gateway story telling');" target="_blank">
                                    <img src="<?php echo $this->config['assets_image_url'] ?>hubungi.mobile.png">
                            </a>
                    </div>
            <div class="read-gateway-text">
                <a href="http://storytelling.brilio.net/" onclick="ga('send', 'event', 'Detail foto - Gateway story telling ', 'Click', 'gateway story telling');" target="_blank">
                    <b>Everyone</b> has <b>Untold Stories</b>. Sebarkan ceritamu di sini.
                </a>
            </div>
        </div>
        <div class="list-article-box">
            <div class="box-float">
                <ul class="list-article-berita-read list-article-small list-unstyled">
                    <?php
                    foreach ($related_news as $key) { ?>
                        <li>
                            <div class="deskrip-br">
                                <p class="deskrip-text">
                                    <a href="<?= $key['news_url_full']?>" onclick="ga('send', 'event', 'Detail foto - Related', 'Click', '<?= $key['news_title']?>');">
                                        <?= $key['news_title']?>
                                    </a>
                                </p>
                            </div>
                        </li>
                        <?php
                    }
                    ?>
                </ul>
            </div>

        </div>
        <!--<div class="uc-web">
            <div class="uc-web-img">
                <img src="<?php echo $this->config['assets_image_url'] ?>ad-image.jpg">
            </div>
            <div class="uc-web-text">
                <script src="http://admaster.union.ucweb.com/js/union_html5_sdk.js"></script>
                <script>
                        try {
                            Umobi.AdView({
                                pub: "fuquan@brilio",
                                format_type: Umobi.AdFormatType.TEXT
                            });
                        } catch (e) {
                        }
                </script>
                <noscript>
                <a href="http://click.union.ucweb.com/?pub=fuquan@brilio&tm={TM}">
                    <img src="http://slot.union.ucweb.com/?pub=fuquan@brilio&format_type=img&tm={TM}"/>
                </a></noscript>
            </div>
        </div>-->
        <?php
            if ($news_data['news_sensitive'] != 1) {
                ?>
                    <div class="comment-title">WHAT DO YOU THINK?</div>
                    <div class="fb-comment">
                        <!-- FB COMMEND -->
                        <div class="content-left-commant">
                            <div class="fb-comments" data-href="<?php echo $news_data['url_share'] ?>" data-width="100%" data-numposts="10" data-colorscheme="light"></div>
                        </div>
                        <!-- FB COMMEND -->
                    </div>
                 <?php
            }
        ?>
    </div>
    <div class="list-article-box" style="margin-top:-50px;">
        <div class="bottom-tags-title">
            <div class="bottom-tags-title-line"></div>
            <div class="bottom-tags-title-name">MOST POPULAR</div>
        </div>
        <div class="box-float">
            <ul class="list-article-berita list-number list-unstyled">
                <!-- {POPULAR} -->
                 <?php
                    if(!empty($popular['trending'])):
                      $no = 1;
                      foreach ($popular['trending'] as $key): ?>
                      <?php if ($no<=7): ?>

                    <li>
                        <div class="article-left"><?= $key['NO'] ?></div>
                        <div class="deskrip-br-popular">
                            <p class="deskrip-text">
                                <a href="<?= $key['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Homepage - Most popular', 'Click', '<?= $key['NEWS_TITLE'] ?>');" class="popular"><?= $key['NEWS_TITLE'] ?></a>
                            </p>
                        </div>
                    </li>
                    <?php else: break;?>
                  <?php endif; ?>
                    <?php
                    $no++;
                        endforeach;
                    endif;?>
                <!-- end {POPULAR} -->
            </ul>
        </div>
    </div>
    <!-- <div class="list-article-box">
        <div class="section-hardlink">
            <span style="padding-bottom: 0px; padding-left: 10px;"><img style="margin-top: -4px;" src="<?php echo $this->config['assets_image_url'] ?>Menu-Thin-grey-32-b.png"></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>news/">NEWS</a></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>life/">LIFE</a></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>popular/">DAILY</a></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>popular/week/">WEEKLY</a></span>
        </div>
    </div> -->

    <!-- jsview -->
    <input type="hidden" id="news_url_full" value="<?php echo $news_data['url_share']; ?>">
    <input type="hidden" id="jsview_url" value="<?php echo $news_data['url_share']; ?>">
    <input type="hidden" id="detail_news" value="true">
    <!-- end of jsview -->
    <!-- {end NEWS} -->
</div>
<!--end section-->
<?php echo $_list_categories_bottom ?>
