<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <li><a href="<?php echo $this->config['rel_url'] ?>">Home</a></li>
        <li>&raquo;</li>
        <li><a href="#">Company</a></li>
        <li>&raquo;</li>
        <li><a href="#">Redaksi</a></li>
    </ol>
</div>
<div class="redaksi">
    <div class="redaksi-title">Pemimpin Redaksi :</div>
    <div class="redaksi-list">Didik Supriyanto</div>
    <div class="redaksi-title">Redaktur Eksekutif :</div>
    <div class="redaksi-list">Titis Widyatmoko</div>
    <div class="redaksi-title">Staf Redaksi :</div>
    <div class="redaksi-list">Ahada Ramadhana, Ahmad Ragridio Saptama Tanjung, Andi Rosita Dewi, Agustin Wahyuningsih, Angga Roni Priambodo, Annisa Endriyati Utami, Dona Arvanto, Erina Wardoyo, Fadila Adelin, Fefy Dwi Haryanto, Janne Hillary, Joshua Riwu Kaho, Ines Faradina, Irwan Khoiruddin, Ismarlina Mokodompit, MT Ardynata, Muhammad Abduh Lubis, Muhammad Gufron Salim, Nur Romdlon, Regga Hendarto, Sabar Artiyono, Sugeng Tri Wahyudi, Tony Febryanto.</div>
</div>