<!--section -->

<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <!-- {BREADCUMB}-->
        <li>
            <a href="<?php echo  $this->config['rel_url'] ?>" >Home</a>
        </li>
        <li>&raquo;</li>
        <li>
            <a href="<?php echo  $this->config['rel_url'] . $BREADCRUMB['CATEGORY_URL'] ?>" >
                    <?php echo  $BREADCRUMB['CATEGORY_TITLE'] ?>
            </a>
        </li>
        <!-- end {BREADCUMB}-->
    </ol>
    <!-- {NEWS} -->
    <div class="detail-br">
        <div class="headline-detail">
            <span class="date"><?php echo  $news_data['news_date'] ?></span>
            <h1><?php echo  $news_data['news_title']; ?></h1>
            <span class="read-sinopsis">
                <?php 
                if ($news_data['nav_paging_photos']['visit_images_number'] == 1)
                {
                    echo html_entity_decode($news_data['news_synopsis']);
                }
                ?>
            </span>
            <span class="writer"><?php echo $news_data['reporter'] ?></span>
            
        </div>
        <!-- {IMAGES_HEADLINE} -->
        <?php
        if(isset($news_data['images_headline'])) {
            ?>
                <div class="img-detail">
                    <amp-img src="<?php echo  $news_data['images_headline']['news_image_url'] ?>" class="img-full" layout="responsive" width="320" height="200">
                    <span class="img-copy"><?php echo  $news_data['images_headline']['news_imageinfo'] ." . ". $news_data['images_headline']['photonews_copyright'] ?></span>
                </div>
            <?php
        }
        ?>
        <!-- end {IMAGES_HEADLINE} -->
        <div class="body-paragraph">
            <p>
                <!-- {NEWS_CONTENT} -->
                <?php 
                if ($news_data['nav_paging_photos']['visit_images_number'] == 1):
                    echo html_entity_decode($news_data['news_content']);
                endif 
                ?>
                <!-- end {NEWS_CONTENT} -->
                
            </p>
        </div>
        <div class="img-detail-foto">
            <div class="img-foto">
                <amp-img src="<?php echo $news_data['data_photos_visited']['photonews_image_url'] ?>" layout="responsive" width="320" height="200" class="img-full"></amp-img>
            </div>
            <p><?php echo $news_data['data_photos_visited']['photonews_copyright']." - ".$news_data['data_photos_visited']['photonews_description'] ?></p>
            <!-- {NAV_LIST_PHOTOS} -->
            <div class="artikel-paging-number text-center clearfix">
                <div class="arrow-number-l pull-left">
                    <a href="<?php echo $news_data['nav_paging_photos']['prev_photonews_url'] ?>" ><span class="arrow-br arrow-left"></span></a>
                </div>
                <div class="number"><?php echo $news_data['nav_paging_photos']['visit_images_number']."/".$news_data['nav_paging_photos']['total_images'] ?></div>
                <div class="arrow-number-r pull-right">
                    <a href="<?php echo $news_data['nav_paging_photos']['next_photonews_url'] ?>" ><span class="arrow-br arrow-right"></span></a>
                </div>
            </div>
            <!-- end {NAV_LIST_PHOTOS} -->
            <p>
                <!-- INITIAL EDITR -->
                <?php echo  $news_data['initial_editor']; ?>
                <!-- end INITIAL EDITR -->
            </p>
        </div>
        <?php echo $video ?>
        <ul class="detail-box list-tag list-unstyled">
            <!-- {LIST_TAG} -->
            <?php
            if(isset($news_data['list_tag'])) {
                foreach ($news_data['list_tag'] as $data) {
                    ?>
                        <li>
                            <a href="<?php echo $data['tag_link'] ?>" ><?php echo $data['tag_news_title'] ?></a>
                        </li>
                    <?php
                }
                
            }
            ?>
            
            <!-- end {LIST_TAG} -->
        </ul>
        <div class="detail-box text-center">
            <h6 class="title-black">SHARE NOW</h6>
            <ul class="list-share list-unstyled">
                <li>
                    <a href="<?php echo $news_data['FACEBOOK_SHARE'] ?>" class="fb"></a>
                </li>
                <li>
                    <a href="<?php echo $news_data['TWITTER_SHARE'] ?>" class="twit"></a>
                </li>
                <li>
                    <a href="<?php echo $news_data['WA_SHARE'] ?>" class="wa"></a>
                </li>
            </ul>
        </div>
        <div class="read-gateway">
            <div class="read-gateway-img">
                            <a href="http://storytelling.brilio.net/" >
                                <amp-img src="<?php echo $this->config['assets_image_url'] ?>hubungi.mobile.png" width="247" height="66"></amp-img>
                            </a>
                    </div>
            <div class="read-gateway-text">
                <a href="http://storytelling.brilio.net/" >
                    <b>Everyone</b> has <b>Untold Stories</b>. Sebarkan ceritamu di sini.
                </a>
            </div>
        </div>    
        <div class="list-article-box">
            <?php 
            //echopre($related_news);
            if(!empty($related_news)) {
                echo $related_news['TITLE_RELATED_NEWS'];
                ?>
            <div class="box-float">
                <ul class="list-article-berita-read list-article-small list-unstyled">
                    <?php
                    $no = 1;
                    foreach ($related_news as $key) {
                        if($no != 1) {
                        ?>
                        <li>
                            <div class="deskrip-br">
                                <p class="deskrip-text">
                                    <a href="<?= $key['RELATED_NEWS_URL']?>" >
                                        <?= $key['RELATED_NEWS_TITLE']?>
                                    </a>
                                </p>
                            </div>
                        </li>
                        <?php
                        }
                        $no++;
                    }
                    ?>
                </ul>
            </div>
                <?php
            }
           
                    
            ?>
            
        </div>
    </div>
    <div class="list-article-box">
        <div class="bottom-tags-title">
            <div class="bottom-tags-title-line"></div>
            <div class="bottom-tags-title-name">MOST POPULAR</div>
        </div>
        <div class="box-float">
            <ul class="list-article-berita list-number list-unstyled">
                <!-- {POPULAR} -->
                 <?php
                    if(!empty($popular['trending'])):
                      foreach ($popular['trending'] as $key): ?>
                    <li>
                        <div class="article-left"><?= $key['NO'] ?></div>
                        <div class="deskrip-br-popular">
                            <p class="deskrip-text">
                                <a href="<?= $key['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Homepage - Most popular', 'Click', '<?= $key['NEWS_TITLE'] ?>');" class="popular"><?= $key['NEWS_TITLE'] ?></a>
                            </p>
                        </div>
                    </li>
                    <?php
                        endforeach;
                    endif;
                 ?>
                <!-- end {POPULAR} -->
            </ul>
        </div>
    </div>
    <div class="list-article-box">
        <div class="section-hardlink">
            <span><amp-img src="<?php echo $this->config['assets_image_url'] ?>Menu-Thin-grey-32-b.png" width="20" height="20"></amp-img></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>news/">NEWS</a></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>life/">LIFE</a></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>popular/">DAILY</a></span>
            <span><a href="<?php echo $this->config['rel_url']; ?>popular/week/">WEEKLY</a></span>
        </div>
    <!-- {end NEWS} -->
    </div>
</div>
<!--end section-->
<?php echo $today_tags; ?>


