<?php if ( $related_news_list ): ?>
    <div class="list-article-box">
         <div class="bottom-tags-title">
            <div class="bottom-tags-title-line"></div>
            <div class="bottom-tags-title-name">RELATED</div>
        </div>
        
        <div class="box-float">
            <ul class="list-article-berita-read list-article-small list-unstyled">
                <?php foreach ($related_news_list as $key): ?>
                <li>
                    <div class="deskrip-br">
                        <p class="deskrip-text">
                            <a href="<?= $key['news_url_amp_full']?>" target="_blank">
                                <?= $key['news_title']?>
                            </a>
                        </p>
                    </div>
                </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
<?php endif ?>