<div class="article-col-right">
<div class="share-story" id="subs">
    <h6>DON'T MISS OUT ON BRILIO'S TOP STORIES!</h6>
    <p>We'll send a list to your inbox. Subscribe now!</p>
    <div id="box-emailSuccess" style="display: none;">
    	<p><h6>Thank you!</h6>Your email sucessfuly registered.</p>
    </div>
    <div id="box-form-email" style="display: none">
    <p id="emailError" style="color:red" ></p>
	    <form action="<?= $this->config['base_url'].'save_collect_email/'?>" method="POST" id="email-form">
	        <div class="input-group input-share">
	            <span class="input-group-addon"><img src="<?= $this->config['assets_image_url_v2']?>email-icon.png"></span>
	            <input type="text" class="form-control" name="emailsubscribe" id="txtEmail" placeholder="Enter your Email">
	        </div>
	        <button type="submit" class="btn btn-share" onclick="ga('send', 'event', '<?= $TE ?>', 'Newsletter', 'Submit');" >YES, send to me</button>
	    </form>
    </div>
</div>
</div>
