<div class="tag-section">
    <div class="container">
        <ul class="list-tag list-unstyled clearfix list-bottom-menu">
            <li><a href="<?= $this->config['rel_url'] ?>popular/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Popular');" >POPULAR</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>news/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'News');" >NEWS</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>lol/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'LOL');" >LOL</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>celebrity/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Celebrity');" >Celebrity</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>figure/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Figure');" >Figure</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>community/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Community');" >Community</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>wow/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Wow!');" >WOW!</a></li>
             <li><a href="<?= $this->config['rel_url'] ?>love/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Love');" >Love</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>tech/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Tech');" >Tech</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>health/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Health');" >Health</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>gross/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Gross!');" >Gross!</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>global/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Global');" >Global</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>womp/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Womp');" >Womp</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>animals/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Animals');" >Animals</a></li>
             <li><a href="<?= $this->config['rel_url'] ?>babies/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Babies');" >Babies</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>sports/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Sports');" >Sports</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>scary/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Scary');" >Scary</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>girls/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Girls');" >Girls</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>guys/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Guys');" >Guys</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>travel/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Travel');" >Travel</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>politics/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Politics');" >Politics</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>economics/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Economics');" >Economics</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>fashion/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Fashion');" >FASHION</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>parents/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Parents');" >Parents</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>music/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Music');" >Music</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>science/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Science');" >Science</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>serious/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Serious');" >Serious</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>personality/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Personality');" >Personality</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>socialite/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Socialite');" >Socialite</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>home-living/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Home Living');" >Home Living</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>food/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Food');" >Food</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>movie/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Movie');" >Movie</a></li>
        </ul>
    </div>
</div>
