<?php
if(!empty($POPULAR_TAGS)):
?>    
<div class="article-col-right">
	<div class="title-border">
			<h4 class="title-line">POPULAR TAGS</h4>
	</div>
	<ul class="article-border article-number list-unstyled">
            <?php
            $no = 1;
            foreach ($POPULAR_TAGS as $data):
            ?>
                <li>
                    <a href="" class="article-left"><span class="number-left"><?php echo $no++ ?></span></a>
                    <div class="deskrip-right">
                        <p class="text-article text-sm">
                            <a href="<?php echo $data['TAG_URL']; ?>"><?php echo $data['TAG_TITLE'] ?></a>
                        </p>
                    </div>
		</li>
            <?php
            endforeach;
            ?>
	</ul>
</div>
<?php
endif;
?>