
<link rel="stylesheet"  href="<?= $this->config['assets_css_url']?>main.css">
<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <li><a href="<?= $this->config['rel_url']?>">Home</a></li>
        <li>&raquo;</li>
        <li><a href="#">Company</a></li>
        <li>&raquo;</li>
        <li><a href="<?= $this->config['rel_url']?>company/disclaimer">Disclaimer</a></li>
    </ol>
</div>
<div class="redaksi">
    <div class="detail-statik-title">Disclaimer</div>
    <div class="redaksi-list">
<b>Brilio.net</b> memiliki ketentuan layanan yang harus ditaati oleh setiap pembaca. Apabila

pembaca berkeberatan atas ketentuan layanan ini, mohon memaklumi ketentuan kami 

demi kebaikan kita bersama.<br><br>

<b>Hak Cipta</b><br>

Informasi yang ditampilkan di situs <b>Brilio.net</b> maupun elemen-elemen pendukungnya 

dilindungi oleh undang-undang Hak Cipta. Barang siapa 

menyalahgunakan/menggunakan/mencetak seluruh isi atau sebagian, memperbanyak, 

menerjemahkan, menggunakan, atau memanfaatkannya dengan cara yang lain tanpa izin 

tertulis dari pihak <b>Brilio.net</b> dapat dikenakan ketentuan pidana.<br><br>

Setiap materi yang diambil dari <b>Brilio.net</b> wajib memberi kredit kepada <b>Brilio.net</b> dengan 

mencantumkan logo atau menulis <b>Brilio.net</b> dan memberi link ke halaman <b>Brilio.net</b> pada 

setiap materi yang digunakan.<br><br>

<b>Berita dan Foto</b><br>

Semua berita dan foto yang ada di layanan <b>Brilio.net</b>, baik yang didapat oleh wartawan 

<b>Brilio.net</b> maupun dari kantor berita disajikan apa adanya, isi dan tanggung jawab ada 

pada sumber utama.<br><br>

<b>Materi dari Pembaca</b><br>

<b>Brilio.net</b> tidak bertanggung jawab terhadap materi yang di-upload oleh pembaca atau 

ditulis oleh pembaca, baik itu berupa komentar berita, foto, profil dan sebagainya.<br><br>

<b>Brilio.net</b> berhak sewaktu-waktu menghapus apa pun yang di-upload oleh pembaca atau 

ditulis oleh pembaca tanpa adanya pemberitahuan terlebih dahulu.<br><br>

<b>Kontribusi Pembaca</b><br>

<b>Brilio.net</b> hanya menerima press release, berita, artikel maupun foto dari pembaca yang 

mengirimkan materi dengan disertai data diri lengkap. Ini dilakukan untuk menghindari 

komplain/tuntutan, dan sebagai pertanggungjawaban dari kontributor terhadap setiap 

materi yang dikirimkan. Materi yang masuk akan mengalami proses seleksi dan editing 

sesuai dengan penilaian tim redaksi <b>Brilio.net</b>. <b>Brilio.net</b> akan mencantumkan nama 

kontributor untuk setiap materi yang diupload.<br><br>

<b>Kontak</b><br>

<b>Brilio.net</b> hanya melayani kontak dengan pembaca melalui form yang telah disediakan. 

Hanya kontak yang disertai data diri lengkap yang akan mendapat respon dari pihak 

<b>Brilio.net</b>. <b>Brilio.net</b> menjamin kerahasiaan data diri Anda.<br><br>

<b>Lain-Lain</b><br>

<b>Brilio.net</b> berhak untuk menambah atau mengurangi peraturan dan ketentuan yang ada 

saat ini tanpa pemberitahuan terlebih dahulu.
	</div>
</div>	