
<link rel="stylesheet"  href="<?= $this->config['assets_css_url']?>main.css">
<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <li><a href="<?= $this->config['rel_url']?>">Home</a></li>
        <li>&raquo;</li>
        <li><a href="#">Company</a></li>
        <li>&raquo;</li>
        <li><a href="#">Kontak</a></li>
    </ol>
</div>
<div class="contact">
    <div class="contact-text">Silahkan isi form di bawah ini untuk mengirim pertanyaan, kritik dan saran tentang <b>brilio.net</b></div>
    <div class="contact-form">
        <form class="form-send" method="post" name="form" action="">
            <ul>
                <li>
                    <input type="text" class="contact-txt" id="nama" name="nama" placeholder="Nama">
                </li>
                <li>
                    <input type="text" class="contact-txt" id="alamat" name="alamat" placeholder="Alamat">
                </li>
                <li>
                    <input type="text" class="contact-txt" id="telp" name="telp" placeholder="No Hp/Telp">
                </li>
                <li>
                    <input type="text" class="contact-txt" id="email" name="email" placeholder="Email">
                </li>
                <li>
                    <textarea class="contact-textarea" id="pesan" name="pesan" placeholder="Pesan"></textarea>
                </li>
                <li>
                    <input type="submit" class="contact-btn" id="btn_contact" value="Kirim">
                </li>
            </ul>
        </form>
    </div>
</div>
<div class="office">
    <b>Alamat</b>
    <br>
    <b>Redaksi Brilio.net</b>
    <br> Jl. Tebet Barat IV No.5
    <br> Jakarta Selatan, 12810
    <br> Email : redaksi@brilio.net
    <br> Telp : (021) 83795245
    <br> Fax : (021) 83795246
</div>
<div class="menu-sitemap">
    <ul>
        <li>
            <a href="<?= $this->config['rel_url']?>company/contact-us/">Kontak Kami</a>
        </li>
        <li>
            <a href="<?= $this->config['rel_url']?>company/pengaduan/">Keberatan Pemberitaan</a>
        </li>
        <li>
            <a href="http://dewanpers.or.id/form_pengaduan/" target="_blank">Pengaduan Dewan Pres</a>
        </li>
    </ul>
</div>