<div class="section">
    <ol class="list-breadcrumb list-unstyled">
<!--        {BREADCRUMB}-->
        <?php
            if(isset($BREADCRUMB)) {
                if($BREADCRUMB['init'] == 'A') {
                    ?>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', 'Home');">Home</a>
                        </li>
                        <li>&raquo;</li>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>most-shared/" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', 'Most Shared');">Most Shared</a>
                        </li>
                    <?php
                }
                elseif($BREADCRUMB['init'] == 'B') {
                    ?>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', 'Home');">Home</a>
                        </li>
                        <li>&raquo;</li>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>most-shared/" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', 'Most Shared');">Most Shared</a>
                        </li>
                        <li>&raquo;</li>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $BREADCRUMB['TAHUN']; ?>/" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', '<?php echo $BREADCRUMB['TAHUN']; ?>');"><?php echo $BREADCRUMB['TAHUN']; ?></a>
                        </li>
                    <?php
                }
                else {
                    ?>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', 'Home');">Home</a>
                        </li>
                        <li>&raquo;</li>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>most-shared/" onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', 'Most Shared');">Most Shared</a>
                        </li>
                        <li>&raquo;</li>
                        <li>
                            <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $BREADCRUMB['TAHUN'] . "/" . $BREADCRUMB['BULAN'] . "/" . $BREADCRUMB['TANGGAL']."/"; ?>"  onclick="ga('send', 'event', 'Most Shared - Breadcumb', 'Click', '<?php echo $BREADCRUMB['TANGGAL_FORMAT'] ?>);"><?php echo $BREADCRUMB['TANGGAL_FORMAT'] ?></a>
                        </li>
                    <?php
                }
            }
        ?>
    </ol>
    <ul class="list-tab list-unstyled clearfix">
        <!-- {MENU_TYPE_DATE} -->
        <?php 
            if(isset($MENU_TYPE_DATE)) {
                ?>
                    <li <?php echo $MENU_TYPE_DATE['CLASS_TODAY']; ?>>
                        <a href="<?php echo $MENU_TYPE_DATE['URL_TODAY'] ?>/" onclick="ga('send', 'event', 'Most Shared - Switch trending top', 'Click', 'TOP DAILY');">TOP DAILY</a>
                    </li>
                    <li <?php echo $MENU_TYPE_DATE['CLASS_WEEK'] ?>>
                        <a href="<?php echo $MENU_TYPE_DATE['URL_WEEK']; ?>/" onclick="ga('send', 'event', 'Most Shared - Switch trending top', 'Click', 'TOP WEEKLY');">TOP WEEKLY</a>
                    </li>
                <?php
            }
        ?>
        <!-- end {MENU_TYPE_DATE} -->
    </ul>
    <div class="tab-content">
        <div id="dailytop" class="content-daily tab-pane fade in active">
            <div class="artikel-paging-number paging-number-popular text-center clearfix"> 
                <!-- {MENU_PER_DATE} -->
                <?php
                    $data = $MENU_PER_DATE['VIEW_MENU_PER_DATE'];
                    if($MENU_PER_DATE['init'] == 'sebelum') {
                        ?>
                            <div class="arrow-number-l-popular pull-left">
                                <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $data['TANGGAL_SEBELUM_SEKARANG_FORMAT'] ?>/" onclick="ga('send', 'event', 'Most Shared - Date top', 'click', 'PREV');"><span class="arrow-br-popular arrow-left"></span></a>
                            </div>
                            <div class="number-black"><?php echo $data['TANGGAL_SEKARANG_FORMAT'] ?></div>
                            <div class="arrow-number-r-popular pull-right">
                                <a href="#"><span class="arrow-br-popular arrow-right"></span></a>
                            </div>
                        <?php
                    }
                    elseif($MENU_PER_DATE['init'] == 'sesudah') {
                        ?>
                            <div class="arrow-number-l-popular pull-left">
                                <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $data['TANGGAL_SEBELUM_VISIT_FORMAT'] ?>/" onclick="ga('send', 'event', 'Most Shared - Date top', 'click', 'PREV');"><span class="arrow-br-popular arrow-left"></span></a>
                            </div>
                            <div class="number-black"><?php echo $data['TANGGAL_VISIT_FORMAT'] ?></div>
                            <div class="arrow-number-r-popular pull-right">
                                <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $data['TANGGAL_SESUDAH_VISIT_FORMAT'] ?>/" onclick="ga('send', 'event', 'Most Shared - Date top', 'click', 'NEXT');"><span class="arrow-br-popular arrow-right"></span></a>
                            </div>
                        <?php
                    }
                    
                ?>
                <!-- end {MENU_PER_DATE} -->
            </div>
            <!-- {HEADLINE} -->
            <?php
                if(isset($HEADLINE['ERROR'])) {
                    echo $HEADLINE['MESSAGE'];
                }
                else {
                    ?>
                        <div class="header-br headline-popular">
                            <a href="<?php echo $HEADLINE['NEWS_URL'] ?>" class="img-headline"
                               onclick="ga('send', 'event', 'Most Shared - Stream', 'click', '<?php echo $HEADLINE['NEWS_TITLE'] ?>);">
                                <img src="<?php echo $HEADLINE['NEWS_IMAGES'] ?>" class="img-full">
                                <div class="number-top"><p>1</p></div>
                            </a>
                            <div class="deskrip-head">
                                <h6 class="title-head">
                                    <a href="<?php echo $HEADLINE['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Most Shared - Stream', 'click', '<?php echo $HEADLINE['NEWS_TITLE'] ?>);">
                                        <?php echo $HEADLINE['NEWS_TITLE'] ?>
                                    </a>
                                </h6> 
                            </div>
                        </div>
                    <?php
                }
            ?>
            <!-- end {HEADLINE} -->
        </div>
        <div class="list-article-box list-article-popular">
            <!-- {NEWS_LIST} -->
            <ul class="list-article-berita-border list-article-popular list-unstyled">
            <?php
                if(!empty($NEWS_LIST)) {
                    foreach ($NEWS_LIST as $data):
                    ?>
                        <li>
                            <a href="<?php echo $data['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Most Shared - Stream', 'click', '<?php echo $data['NEWS_TITLE'] ?>);" class="article-left">
                                <img src="<?php echo $data['NEWS_IMAGES'] ?>" width="100" height="100">
                                <div class="number-top">
                                    <p><?php echo $data['NO'] ?></p>
                                </div>
                            </a>
                            <div class="deskrip-br">
                                <p class="deskrip-text"><a href="<?php echo  $data['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Most Shared - Stream', 'click', '<?php echo $data['NEWS_TITLE'] ?>');"><?php echo $data['NEWS_TITLE'] ?></a>
                                </p>
                            </div>
                        </li>
                    <?php
                    endforeach;
                }
            ?>
            </ul>
            <!-- end {NEWS_LIST} -->
        </div>
    </div>
    <ul class="list-tab list-unstyled clearfix">
        <!-- {MENU_TYPE_DATE BOTTOM} -->
        <?php 
            if(isset($MENU_TYPE_DATE)) {
                ?>
                    <li <?php echo $MENU_TYPE_DATE['CLASS_TODAY']; ?>>
                        <a href="<?php echo $MENU_TYPE_DATE['URL_TODAY'] ?>/" onclick="ga('send', 'event', 'Most Shared - Switch trending bottom', 'Click', 'TOP DAILY');">TOP DAILY</a>
                    </li>
                    <li <?php echo $MENU_TYPE_DATE['CLASS_WEEK'] ?>>
                        <a href="<?php echo $MENU_TYPE_DATE['URL_WEEK']; ?>/" onclick="ga('send', 'event', 'Most Shared - Switch trending bottom', 'Click', 'TOP WEEKLY');">TOP WEEKLY</a>
                    </li>
                <?php
            }
        ?>
        <!-- end {MENU_TYPE_DATE BOTTOM} -->
    </ul>
    <div class="tab-content">
        <div id="dailybottom" class="content-daily tab-pane fade in active">
            <div class="artikel-paging-number paging-number-popular text-center clearfix">
                <!-- {MENU_PER_DATE} -->
                <?php
                    $data = $MENU_PER_DATE['VIEW_MENU_PER_DATE'];
                    if($MENU_PER_DATE['init'] == 'sebelum') {
                        ?>
                            <div class="arrow-number-l-popular pull-left">
                                <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $data['TANGGAL_SEBELUM_SEKARANG_FORMAT'] ?>/" onclick="ga('send', 'event', 'Most Shared - Date bottom', 'click', 'PREV');"><span class="arrow-br-popular arrow-left"></span></a>
                            </div>
                            <div class="number-black"><?php echo $data['TANGGAL_SEKARANG_FORMAT'] ?></div>
                            <div class="arrow-number-r-popular pull-right">
                                <a href="#"><span class="arrow-br-popular arrow-right"></span></a>
                            </div>
                        <?php
                    }
                    elseif($MENU_PER_DATE['init'] == 'sesudah') {
                        ?>
                            <div class="arrow-number-l-popular pull-left">
                                <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $data['TANGGAL_SEBELUM_VISIT_FORMAT'] ?>/" onclick="ga('send', 'event', 'Most Shared - Date bottom', 'click', 'PREV');"><span class="arrow-br-popular arrow-left"></span></a>
                            </div>
                            <div class="number-black"><?php echo $data['TANGGAL_VISIT_FORMAT'] ?></div>
                            <div class="arrow-number-r-popular pull-right">
                                <a href="<?php echo $this->config['rel_url']; ?>most-shared/<?php echo $data['TANGGAL_SESUDAH_VISIT_FORMAT'] ?>/" onclick="ga('send', 'event', 'Most Shared - Date bottom', 'click', 'NEXT');"><span class="arrow-br-popular arrow-right"></span></a>
                            </div>
                        <?php
                    }
                    
                ?>
                <!-- end {MENU_PER_DATE} -->
            </div>
            <ul class="list-nav-most list-unstyled">
                <li>
                    <a href="<?php echo $this->config['rel_url']; ?>popular/" onclick="ga('send', 'event', 'Most Shared - Trending menu', 'click', 'Popular');">
                        <span class="img-nav-most img-popular"></span>POPULAR
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->config['rel_url']; ?>most-liked/" onclick="ga('send', 'event', 'Most Shared - Trending menu', 'click', 'Most liked');">
                        <span class="img-nav-most img-liked"></span>MOST LIKED
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->config['rel_url']; ?>most-commented/" onclick="ga('send', 'event', 'Most Shared - Trending menu', 'click', 'Most commented');">
                        <span class="img-nav-most img-comment"></span>MOST COMMENTED
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->config['rel_url']; ?>most-shared/" onclick="ga('send', 'event', 'Most Shared - Trending menu', 'click', 'Most shared');">
                        <span class="img-nav-most img-shared"></span>MOST SHARED
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!--end section-->