<div class="section">

    <div class="header-br">
    <a href="<?= $headline_big['news_url_full'] ?>" onclick="ga('send', 'event', 'Homepage - Headline', 'Click', '<?= $headline_big['news_title'] ?>');" class="img-headline">
        <img src="<?= $headline_big['news_image_headline']?>" data-src="<?= $headline_big['news_image_headline']?>" class="img-full" onclick="ga('send', 'event', 'Homepage - Headline', 'Impression', '<?= $headline_big['news_title'] ?>');">
    </a>
    <div class="deskrip-head">
        <div class="kategori-date">
            <a href="<?= $headline_big['news_tag_list'][0]['tag_url_full'] ?>" class="link-kategori"><?= ucwords($headline_big['news_tag_list'][0]['tag_news_tags']) ?></a>
        </div>
        <h6 class="title-head">
        <a href="<?= $headline_big['news_url_full'] ?>" onclick="ga('send', 'event', 'Homepage - Headline', 'Click', '<?= $headline_big['news_title'] ?>');">
        <?= $headline_big['news_title'] ?>
        </a>
        </h6>
    </div>
    </div>

    <?= $announcer_index ?>


<div class="list-article-box">

<ul class="list-article-berita-border list-article-bt list-unstyled">

    <?= $sticky_news_1 ?>

    <?php
    $for_sticky = 1;
    foreach ($headline_list as $k ):
    ?>
    <li>
        <a href="<?= $k['news_url_full']?>" onclick="ga('send', 'event', '<?= $k['TE']?> - Headline', 'Click', '<?= $k['news_title']?>');" class="article-left-ads">
            <img src="<?= $k['news_image_headline_second']?>" data-src="<?= $k['news_image_headline_second']?>" onclick="ga('send', 'event', '<?= $k['TE']?> - Headline', 'Impression', '<?= $k['news_title']?>');" width="120" height="60">
        </a>
        <div class="deskrip-br">
          <?php if ( !empty($k['news_tag_list']) ): ?>
            <div class="kategori-date-ads">
                <a href="<?= $k['news_tag_list'][0]['tag_url_full']?>" class="link-kategori-ads"><?= ucwords($k['news_tag_list'][0]['tag_news_tags']) ?></a>
            </div>
          <?php endif; ?>
            <p class="deskrip-text-arial"><a href="<?= $k['news_url_full']?>" onclick="ga('send', 'event', '<?= $k['TE']?> - Headline', 'Click', '<?= $k['news_title']?>');"><?= $k['news_title']?></a>
            </p>
        </div>
    </li>
    <?php
        if($for_sticky == 1){
            echo $sticky_news_2;
        }
        $for_sticky++;
    endforeach;
    ?>
</ul>

</div>


<div class="list-article-box">
    <div class="bottom-tags-title">
        <div class="bottom-tags-title-line"></div>
        <div class="bottom-tags-title-name">MOST POPULAR</div>
    </div>

    <div class="box-float">
        <ul class="list-article-berita list-number list-unstyled">
        <?php
        if(!empty($popular['trending'])):
          foreach ($popular['trending'] as $key): ?>
        <li>
            <div class="article-left"><?= $key['NO'] ?></div>
            <div class="deskrip-br-popular">
                <p class="deskrip-text">
                    <a href="<?= $key['NEWS_URL'] ?>" onclick="ga('send', 'event', 'Homepage - Most popular', 'Click', '<?= $key['NEWS_TITLE'] ?>');" class="popular"><?= $key['NEWS_TITLE'] ?></a>
                </p>
            </div>
        </li>
        <?php
            endforeach;
        endif;?>
        </ul>
    </div>

        <div class="list-article-box">
            <div class="section-hardlink">
                <span style="padding-bottom: 0px; padding-left: 10px;"><img style="margin-top: -4px;" src="<?= $this->config['assets_image_url']?>Menu-Thin-grey-32-b.png"></span>
                <span><a href="https://m.brilio.net/news/">NEWS</a></span>
                <span><a href="https://m.brilio.net/life/">LIFE</a></span>
                <span><a href="https://m.brilio.net/popular/">DAILY</a></span>
                <span><a href="https://m.brilio.net/popular/week/">WEEKLY</a></span>
            </div>
        </div>
</div>



<div class="list-article-box">
    <div class="bottom-tags-title">
        <div class="bottom-tags-title-line"></div>
        <div class="bottom-tags-title-name">JUST UPDATED</div>
    </div>

    <?php

    foreach ($just_update as $key => $val): ?>
    <div class="box-float">
        <?php
        if ($key == 0){ ?>
            <ul class="list-article-berita list-article-double list-unstyled">
            <li>
                <a href="<?= $val['news_url_full'] ?>" onclick="ga('send', 'event', 'Homepage - Just updated click', 'Click', '<?= $val['news_title'] ?>');" class="article-left">
                    <img src="<?= $val['news_image_location'].'100x100-'.$val['news_image_thumbnail'] ?>" data-src="<?= $val['news_image_location'].'100x100-'.$val['news_image_potrait'] ?>" width="100" height="100">
                </a>
            <div class="deskrip-br">
              <?php if ( !empty($val['news_tag_list']) ): ?>
                <div class="kategori-date">
                    <a href="<?= $val['news_tag_list'][0]['tag_url_full'] ?>" class="link-kategori"><?= strtoupper($val['news_tag_list'][0]['tag_news_tags']) ?></a>
                </div>
              <?php endif; ?>
                <p class="deskrip-text">
                    <a href="<?= $val['news_url_full'] ?>" onclick="ga('send', 'event', 'Homepage - Just updated', 'Click', '<?= $val['news_title'] ?>');"><?= $val['news_title'] ?></a>
                </p>
                <div class="kategori-date">
                    <span class="date"><?= $val['news_date_publish_indo'] ?></span>
                </div>
            </div>
            </li>
            </ul>
        <?php
        }
        else {
        ?>

        <ul class="list-article-berita list-article-small list-unstyled">
            <li>
            <div class="deskrip-br">
              <?php if ( !empty($val['news_tag_list']) ): ?>

                <div class="kategori-date">
                    <a href="<?= $val['news_tag_list'][0]['tag_url_full'] ?>" class="link-kategori"><?= $val['news_tag_list'][0]['tag_news_tags'] ?></a>
                </div>
              <?php endif; ?>
                <p class="deskrip-text">
                    <a href="<?= $val['news_url_full'] ?>" onclick="ga('send', 'event', 'Homepage - Just updated', 'Click', '<?= $val['news_title'] ?>');">
                    <?= $val['news_title'] ?>
                    </a>
                </p>
                <div class="kategori-date">
                    <span class="date"><?= $val['news_date_publish_indo'] ?></span>
                </div>
            </div>
            </li>
        </ul>
    <?php
        }
    endforeach;
    ?>
    </div>

</div>
</div>

<?= $today_tags ?>
