<div class="section">
    <ol class="list-breadcrumb list-unstyled">
        <li><a href="<?php echo $this->config['rel_url']; ?>">Home</a></li>
        <li>&raquo;</li>
        <li><a href="#">Company</a></li>
        <li>&raquo;</li>
        <li><a href="<?php echo $this->config['rel_url']; ?>company/privacy-policy">Privacy Policy</a></li>
    </ol>
</div>
<div class="redaksi">
    <div class="detail-statik-title">PRIVACY POLICY</div>    
    <div class="redaksi-list">
	<!-- privacy -->
Privacy Policy ini menjelaskan kebijakan penanganan dan penggunaan data-data pribadi 

para pengguna layanan KLN yang diberikan kepada situs KLN secara online, telepon, 

teks, email, surat-surat atau korespondensi.<br>

Dalam rangka KLN menyediakan berbagai layanan untuk pengguna, kami (KLN) 

terkadang perlu untuk mengumpulkan informasi mengenai pengguna layanan, termasuk 

Anda.<br>

Penjelasan Kebijakan Privasi ini adalah sebagai berikut: <br>
<ul>
<li>Informasi apa saja yang dapat dikumpulkan KLN mengenai Anda; </li>

<li>Bagaimana KLN akan menggunakan informasi yang dikumpulkan mengenai Anda; </li>

<li>Kapan KLN dapat menggunakan informasi tersebut untuk menghubungi Anda; </li>

<li>Apakah KLN akan mengungkapkan informasi mengenai Anda kepada orang lain; </li>

<li>Pilihan Anda terkait informasi pribadi yang akan Anda berikan kepada kami; </li>

<li>Penggunaan cookies pada situs KLN dan bagaimana Anda dapat menolak 

ketentuan cookies.</li>
</ul>

KLN berkomitmen untuk melindungi informasi pribadi Anda apabila Anda menggunakan 

setiap layanan yang ada di KLN. Setiap kali Anda memberikan informasi tersebut, kami 

secara hukum diharuskan untuk menggunakan informasi Anda sesuai dengan undang-

undang tentang perlindungan informasi pribadi.<br>

Situs KLN berisi hyperlink ke situs-situs yang dimiliki termasuk yang dioperasikan oleh 

pihak ketiga. Situs pihak ketiga ini memiliki kebijakan privasi mereka sendiri, termasuk 

cookies, dan kami meminta Anda untuk meninjau dan mempelajari ketentuan yang 

mereka miliki, sebelum memberikan informasi pribadi. Mereka akan mengatur 

penggunaan informasi pribadi yang Anda masukkan atau dikumpulkan oleh cookies saat 

mengunjungi situs milik mereka. Kami tidak bertanggung jawab atau punya kewajiban 

untuk praktik privasi dari situs web milik pihak ketiga dan akses dan/atau penggunaan 

situs tersebut menjadi risiko Anda sendiri.<br><br>

<b>SITUS YANG TERCAKUP DALAM PRIVACY POLICY</b><br>

Privacy Policy ini berlaku untuk situs Brilio.net.<br><br>

<b>INFORMASI YANG KAMI DAPATKAN DARI PENGGUNA</b><br>

Informasi yang didapatkan dari pengguna layanan kami terbagi dalam dua kategori: <br>

<ol>
<li>Data pribadi yang secara suka rela Anda berikan ketika Anda berpartisipasi, 

mengakses atau mendaftar ke salah satu layanan situs KLN, kegiatan atau konten 

online, seperti newsletter, kompetisi, chatting, message boards, telepon atau teks 

pada situs KLN, polling, mendonasikan dana amal pada KLN, memesan tiket untuk 

acara yang diselenggarakan KLN, membuat account melalui sistem pendaftaran 

online pada KLN, memesan barang atau layanan tertentu, mengisi dan melengkapi 

survei, mendaftar untuk mengikuti diskusi online, berpartisipasi dalam kontes atau 

kuis atau memberikan alamat e-mail 
<ul>

<li>Mendaftar pada situs web kami Semua orang bisa mengakses dan melihat 

situs kami, tapi sebuah proses registrasi gratis dibutuhkan untuk mengakses 

informasi dan layanan secara penuh yang ditawarkan berbagai situs kami. 

Untuk mendaftar pada KLN, Anda harus memberikan alamat e-mail dan info 

demografi (usia, jenis kelamin, nama kota dan kode pos, pendapatan rumah 

tangga (tidak wajib), industri pekerjaan dan jabatan). Dengan menggunakan 

KLN, berarti Anda setuju pada Syarat dan Ketentuan Keanggotaan kami. </li>

<li>Kuis, Undian dan Special Offer Dari waktu ke waktu, KLN mengumpulkan

Survey Pembaca dan Riset Pasar KLN dapat mengumpulkan informasi dari

Promosi dan event khusus Kami seringkali menerima informasi mengenai

Mobile Messaging Service KLN menggunakan informasi yang terkumpul dari 

KLN mengumpulkan data nomor telepon yang Anda gunakan ketika 

informasi pribadi dari pembaca pada hal-hal yang berkaitan dengan undian, 

kuis atau berbagai tawaran istimewa dari sponsor. Jika informasi ini akan 

dibagi bersama pihak ketiga selain KLN, kami akan memberitahukan kepada 

Anda pada saat pengumpulan datanya. Jika Anda tidak menginginkan data 

atau informasi pribadi Anda berada pada pihak lain selain KLN, Anda bisa 

menolak untuk mengikuti berbagai undian, kuis atau penawaran lainnya. </li>

<li>pembaca dalam hubungannya dengan berbagai survei yang 

diselenggarakan. Data bisa kami kumpulkan melalui situs web, pesawat 

telepon atau melalui surat. Informasi yang Anda berikan pada jawaban 

pertanyaan survey bisa dibagi, tapi hanya sebagai keseluruhan, bersama 

pengiklan dan rekanan kecuali sebelumnya ada pemberitahuan pada saat 

pengumpulan data. </li>
<li>
Promosi dan event khusus Kami seringkali menerima informasi mengenai

berbagai berbagai promosi dan acara khusus yang diselenggarakan oleh sponsor 

atau rekanan kami. Untuk itu kami juga menawarkan pada pembaca kami 

yang ingin diundang pada acara-acara tersebut untuk memberikan informasi 

yang dibutuhkan pihak penyelenggara dan akan diindikasikan pada waktu 

pengumpulan.</li>

<li>
Mobile Messaging Service KLN menggunakan informasi yang terkumpul dari

hasil interaksi Anda dengan KLN menggunakan Layanan Pesan Pendek 

(Layanan SMS) hanya untuk keperluan peningkatan layanan SMS. Informasi 

yang terkumpul tidak akan disediakan, dijual, dilisensikan, disewakan atau 

diberikan kepada Pihak Ketiga, kecuali diperintahkan secara hukum, dan 

kami juga tidak akan menggunakan nomor telepon Anda untuk menghubungi 

atau mengirimkan SMS pada Anda tanpa sepengetahuan dan persetujuan 

Anda. Penyedia jasa telekomunikasi Anda dan penyedia jasa lainnya juga 

mengumpulkan data penggunaan Layanan SMS Anda, kegiatan ini diatur 

oleh kebijakan penanganan data-data pribadi mereka sendiri. </li>
<li>

KLN mengumpulkan data nomor telepon yang Anda gunakan ketika mengirimkan teks SMS dan isi pesan yang terkirim antara Anda dan KLN. 

Ketika Anda mengirimkan pesan teks ke KLN atau melalui KLN, kami 

menyimpan nomor telepon pengirim, data provider telekomunikasi yang 

berkaitan dengan nomor tersebut, dan tanggal serta waktu transaksi. 

Informasi yang kami kumpulkan secara otomatis hanyalah yang berkaitan 

pada penggunaan layanan Mobile kami. KLN menggunakan data-data ini 

untuk menganalisa lalu lintas pesan untuk mengoperasikan, 

mengembangkan dan meningkatkan Layanan SMS kami.</li>
</ul>
</li>
<li>Penelusuran informasi yang dikumpulkan ketika Anda bernavigasi di dalam situs kami. 
<ul>
<li>Cookies dan teknologi Lainnya Kami menggunakan session ID cookie, yang

berarti ketika pengguna menutup browser, cookie tersebut dihapus. Cookie 

juga digunakan untuk manajemen session di website kami. Pengguna harus 

mengaktifkan cookie untuk menggunakan website kami. Pengguna juga 

dapat menggunakan cookie untuk mengingat password mereka agar secara 

otomatis bisa log in pada situs kami. Kami tidak dan tidak akan 

menggunakan cookie untuk mengumpulkan informasi pribadi dari pengguna 

manapun yang tidak dimaksudkan untuk disampaikan pada kami.</li>

<li>IP Addresses KLN menyimpan IP (Internet Protocol) address, atau lokasi

komputer Anda di Internet, untuk keperluan administrasi sistem dan 

troubleshooting. Kami menggunakan IP address secara keseluruhan 

(agregat) untuk mengetahui lokasi-lokasi yang mengakses situs kami.</li>

<li>Log Files Data log hanya digunakan dalam bentuk agregat (keseluruhan) untuk menganalisa penggunaan web kami.</li>

<li>Kami dapat menerima informasi pribadi tentang Anda yang terdiri dari

informasi seperti: nama, alamat email, alamat tempat tinggal, telepon atau 

nomor ponsel atau tanggal lahir, tergantung pada aktivitas terkait yang 

diselenggarakan KLN.</li>

<li>Dengan mengirimkan rincian data diri Anda, Anda dimungkinkan untuk

mengaktifkan akun KLN dan bisa mengakses pada semua layanan, kegiatan 

atau konten online yang Anda pilih pada situs KLN. Sebagai tambahan, 

terkadang kami akan meminta Anda untuk memberikan informasi pribadi 

tambahan, termasuk informasi pribadi yang terkadang sensitif, seperti 

mengirimkan aplikasi untuk menjadi kontributor pada partai politik dengan 

tujuan untuk mengetahui kecenderungan politik Anda. Kami akan 

memberikan informasi lebih lanjut tentang mengapa kami mengumpulkan 

informasi tambahan dari Anda dan bagaimana kami akan menggunakannya. 

KLN juga menggunakan cookies dan mengumpulkan alamat IP (nomor unik 

untuk mengidentifikasi jaringan komputer tertentu atau perangkat jaringan 

lainnya di internet) dari pengunjung yang mengakses konten pada situs KLN.</li>
</ul>
</li>
</ol>

<b>PENGGUNAAN INFORMASI</b><br>

KLN akan menggunakan informasi pribadi Anda untuk beberapa tujuan termasuk: 
<ol>

<li>Menyediakan layanan yang kami miliki, kegiatan atau konten online dan untuk 

menyediakan permintaan dan pertanyaan Anda; </li>

<li>Tujuan administrasi layanan, berarti bahwa KLN mungkin akan menghubungi Anda 

untuk alasan yang berhubungan dengan konten layanan, kegiatan atau pendaftaran 

online yang telah Anda lakukan (misalnya untuk menyediakan pengingat password 

atau untuk memberitahukan kepada Anda terhadap layanan tertentu, kegiatan atau 

konten online yang telah ditangguhkan untuk tujuan pemeliharaan);</li> 

<li>Menghubungi Anda mengenai pendaftaran yang telah Anda buat, termasuk setiap 

konten yang telah Anda sediakan. </li>

<li>Menyediakan bagi Anda informasi mengenai layanan kami, kegiatan atau konten 

online; </li>

<li>Personalisasi konten KLN yang disajikan kepada Anda (misalnya apa yang Anda 

lihat pertama setiap harinya dari KLN seperti berita aktual atau fitur hiburan, kami 

akan menghadirkan link informasi ini pada situs Anda); </li>

<li>Menggunakan alamat IP untuk mengidentifikasi lokasi pengguna, untuk 

menghindari penyalahgunaan, untuk menetapkan jumlah kunjungan dari berbagai 

negara dan untuk menentukan apakah Anda mengakses layanan dari wilayah 

Indonesia atau tidak </li>

<li>Menganalisis dan meningkatkan layanan yang ditawarkan di situs KLN, untuk 

menyediakan bagi Anda pengalaman kunjungan situs KLN dengan navigasi user-

friendly. KLN juga dapat menggunakan dan mengungkapkan informasi secara 

agregat (menyeluruh) sehingga tidak ada identifikasi secara individual untuk tujuan 

pemasaran dan tujuan pengembangan strategis </li>

<li>Analisa statistik KLN dapat melakukan analisa statistik, demografi dan marketing 

dari para pengguna dan pelanggannya serta kebiasaan serta pola-pola 

penggunaan yang terjadi untuk pengembangan produk dan menarik pengiklan 

terhadap kebiasaan pengguna. Kami juga menggunakan informasi ini untuk 

memungkinkan iklan yang lebih sesuai target pengguna. KLN juga dapat berbagi 

informasi pengguna dengan perusahaan-perusahaan di grup KLN untuk tujuan 

analisa, termasuk analisa untuk meningkatkan hubungan pelanggan. </li>

<li>Produk dan layanan KLN Secara rutin, kami akan memberikan berbagai informasi 

dan penawaran produk dan layanan lain KLN pada pembaca kami. Informasi ini 

hanya akan kami bagi secara internal. Anda bisa memilih untuk tidak menerima 

penawaran-penawaran ini. </li>

<li>Iklan banner Kami dapat menggunakan informasi demografi dan preferensi untuk 

memungkinkan pemasangan iklan di situs kami agar lebih tepat sasaran. Hal ini 

berarti pengguna dapat melihat iklan yang hanya menarik bagi mereka, dan 

pengiklan dapat menyampaikan pesan hanya kepada target yang tepat bagi produk 

mereka. Hal ini meningkatkan pengalaman pengguna dan keefektifan iklan. Kami 

hanya menyampaikan informasi kepada pihak ketiga dalam format agregat 

(keseluruhan) </li>

<li>Konten yang dibuat oleh pengguna (Message Board, Forum, Review Pembaca dan 

Chat) Kami menawarkan banyak fasilitas message board bagi pembaca di 

sejumlah area situs kami. Informasi apapun yang Anda sampaikan dan 

dipublikasikan di message board bersama dengan nama pengguna (screen name 

atau ID), adalah di area publik dan dapat digunakan oleh KLN untuk keperluan 

promosi di seluruh media online dan offline. Untuk informasi lebih lanjut, silakan 

melihat Persetujuan Pengguna di masing-masing fasilitas dan layanan kami. </li>

<li>Email Newsletter Jika Anda memilih untuk menerimanya, KLN secara teratur akan 

mengirimkan newsletter e-mail atau promosi tentang layanan KLN dan 

pengiklannya.</li>
</ol>

Jika KLN akan menggunakan informasi pribadi Anda untuk keperluan lain maka kami akan 

memastikan untuk memberitahu Anda terlebih dahulu. Anda juga akan diberi kesempatan 

untuk menahan atau membatalkan persetujuan Anda terkait penggunaan informasi pribadi 

Anda untuk tujuan selain yang tercantum di atas.<br><br>

<b>KEBIJAKAN COOKIE INFORMASI YANG DIKUMPULKAN DARI ANDA</b> <br> 

<ol>
<li>Apa itu cookie? Cookie adalah sejumlah kecil data, yang sering kali berisi pengenal 

unik yang dikirimkan ke browser komputer Anda atau ponsel dari komputer milik 

situs dan disimpan pada harddrive perangkat Anda. Setiap website dapat 

mengirimkan cookie sendiri ke browser Anda jika preferensi browser Anda 

mengijinkannya, tetapi untuk tujuan melindungi privasi Anda, browser yang ada di 

perangkat Anda hanya mengizinkan situs web untuk mengakses cookie yang telah 

dikirim kepada Anda, bukan cookie yang dikirimkan kepada Anda oleh situs lain. 

Banyak situs melakukan hal ini setiap kali pengguna mengunjungi situs web 

mereka dalam rangka untuk melacak arus lalu lintas online. 

Di situs KLN, cookie mencatat informasi tentang preferensi online Anda dan 

memungkinkan kita untuk menyesuaikan website untuk kepentingan Anda. 

Pengguna memiliki kesempatan untuk mengatur perangkat mereka untuk 

menerima semua cookie, untuk memberitahu mereka ketika cookie dikeluarkan 

atau tidak menerima cookies setiap saat. Masing-masing browser berbeda satu 

dengan lainnya, maka periksalah menu Help pada browser anda untuk mengetahui 

bagaimana caranya mengubah pilihan cookie seperti yang Anda inginkan. 

Selama Anda kunjungan situs KLN, halaman yang Anda lihat bersama dengan 

cookie akan diunduh ke perangkat Anda. Banyak situs melakukannya, karena 

dengan cookie penerbit situs web dimungkinakn untuk melakukan hal-hal yang 

bermanfaat seperti mencari tahu apakah perangkat pengguna telah melakukan 

kunjungan pada situs web sebelumnya. Hal ini dilakukan pada kunjungan ulang 

dengan memeriksa untuk melihat dan menemukan, cookie lalu akan ditinggalkan 

pada kunjungan terakhir. </li>

<li>Bagaimana KLN menggunakan cookie? Informasi yang diberikan oleh cookie dapat 

membantu kami untuk menganalisis profil dari pengunjung situs kami dan 

membantu kami untuk memberikan pengalaman pengguna yang lebih baik untuk 

Anda. Sebagai contoh, jika pada kunjungan sebelumnya Anda mengakses suatu 

halaman KLN, kami mungkin akan menemukan jejak akses Anda dari cookie yang 

Anda tinggalkan dan selanjutnya akan menyorot informasi terkait konten di halaman 

tertentu tersebut pada kunjungan Anda berikutnya. </li>

<li>Cookie dari Pihak Ketiga pada halaman KLN Harap dicatat bahwa selama 

kunjungan Anda ke situs KLN, Anda mungkin akan melihat beberapa cookie yang 

tidak berhubungan dengan KLN atau rekanan KLN. Ketika Anda mengunjungi 

sebuah halaman dengan konten yang berasal dari pihak ketiga misalnya YouTube 

atau Flickr, Anda mungkin akan disajikan dengan cookie yang berasal dari situs 

tersebut. KLN tidak mengendalikan penyebaran cookie ini, jadi Anda harus 

memeriksa situs web pihak ketiga untuk informasi lebih lanjut. </li>
</ol>

<b>KEBIJAKAN PENANGANAN ALAMAT E-MAIL </b><br>
<ul>
<li>Kami tidak akan membagi, menjual, menyewakan, menukar atau memberikan 

wewenang kepada pihak ketiga tanpa persetujuan Anda. Jika Anda merasa telah 

menerima e-mail dari kami karena suatu kesalahan, silakan kontak KLN. </li>

<li>E-mail yang berkaitan dengan Account dan Layanan: KLN berhak untuk mengirim 

e-mail kepada Anda berkaitan dengan status account Anda. Hal ini termasuk 

konfirmasi pemesanan, pemberitahuan pembaruan/kadaluarsa, pemberitahuan 

masalah metode pembayaranan, e-mail transaksional lainnya dan pemberitahuan 

tentang perubahan menyeluruh pada situs web kami dan/atau Privacy Policy kami. 

Jika Anda terdaftar pada fasilitas diskusi online atau layanan lainnya, Anda akan 

menerima e-mail yang spesifik pada partisipasi Anda di kegiatan tersebut. </li>

<li>E-mail Newsletter: KLN menawarkan fasilitas e-mail newsletter. Jika Anda tak ingin 

lagi menerima newsletter tertentu, silakan ikuti langkah "unsubscribe" yang ada di 

sudut bawah setiap newsletter. </li>

<li>E-mail Promosi: Jika Anda memilih untuk menerimanya, KLN secara rutin akan 

mengirimkan e-mail yang berisi tawaran produk dan jasa yang mungkin menarik 

bagi Anda. Anda bisa memilih untuk tidak menerima pesan-pesan ini di masa 

datang dengan cara (1) ikuti petunjuk "unsubscribe" yang terletak di bagian bawah 

setiap e-mail, atau (2) Anda memilih untuk tidak menerima e-mail jenis ini. Secara 

rutin, KLN mendapatkan alamat e-mail yang bersumber dari pihak ketiga untuk 

digunakan sebagai e-mail promosi. Anda bisa memilih untuk tidak menerima pesan-

pesan ini di masa datang dengan cara ikuti petunjuk "unsubscribe" yang terletak di 

bagian bawah setiap e-mail atau Anda memilih untuk tidak menerima e-mail jenis 

ini. </li>

<li>E-mail Survey: Kami dapat mengirimkan e-mail yang mengundang Anda untuk 

berpartisipasi dalam survey pengguna, bertanya mengenai tanggapan Anda 

tentang KLN dan produk serta layanan yang sudah ada atau sedang 

dikembangkan, serta informasi lain yang untuk mengetahui pengguna kami dengan 

lebih baik. Survey pengguna sangat membantu kami dalam mengembangkan situ 

web kami, dan informasi yang kami dapatkan dari survey tersebut tidak akan kami 

bagi kepada pihak ketiga, kecuali dalam bentuk agregat (keseluruhan). </li>

<li>E-mail HTML: Ketika Anda mendaftar untuk menerima e-mail dari kami, Anda bisa 

memilih untuk menerima e-mail dalam format teks atau HTML (dengan gambar). 

Jika Anda memilih format HTML, kami akan menempatkan sebuah gambar dalam 

format gif berukuran satu piksel untuk mengetahui apakah penerima membuka e-

mail tersebut atau tidak. Proses ini tidak meninggalkan informasi apapun di 

komputer Anda, atau mengumpulkan informasi apapun dari komputer Anda. KLN 

hanya membagi data ini secara agregat (keseluruhan). </li>

<li>E-mails Dari Anda: Jika Anda mengirim e-mail kepada kami, Anda harus paham jika 

informasi yang tercantum di dalam e-mail tersebut tidak aman atau terenkripsi, 

sehingga mungkin saja bisa terlihat oleh pihak lain. Kami menyarankan agar Anda 

sangat berhati-hati ketika mengirimkan untuk mencantumkan informasi pribadi atau 

rahasia di dalam e-mail. Kami akan menggunakan alamat e-mail Anda untuk 

memberikan jawaban langsung atas komentar atau pertanyaan Anda. </li>

<li>Fitur Kirim Artikel melalui E-mail: Pembaca KLN dapat menggunakan fitur ini untuk 

mengirimkan link artikel kepada orang lain melalui alamat e-mail. Alamat e-mail 

yang Anda berikan ketika menggunakan fitur ini hanya akan digunakan untuk 

mengirimkan artikel yang telah dipilih. </li>
</ul>

<b>BERBAGI INFORMASI DENGAN PIHAK KETIGA</b>
<ol> 

<li>KLN Jika Anda telah terdaftar dalam salah satu layanan situs kami, kami akan 

menyimpan informasi rahasia Anda. KLN tidak akan menjual, menyewakan, 

menukar, atau memberikan wewenang kepada pihak ketiga untuk menggunakan 

alamat e-mail Anda atau informasi lainnya yang secara pribadi bisa 

mengidentifikasi diri Anda tanpa ijin. Kecuali jika diperlukan pengungkapan atau 

diizinkan oleh hukum (misalnya untuk badan-badan pemerintah dan badan-badan 

penegak hukum). Namun kami memang berbagi informasi tentang pengguna kami 

dalam bentuk keseluruhan (agregat). </li>

<li>Service Provider Umumnya, kami hanya akan menggunakan informasi pribadi Anda 

dalam situs KLN. Namun, terkadang KLN menggunakan pihak ketiga untuk 

memproses informasi pribadi Anda. Kami terikat kontrak dengan banyak 

perusahaan lain untuk memberikan berbagai layanan yang memperkaya 

pengalaman Anda dalam menggunakan situs KLN, termasuk perusahaan penerbit 

kartu kredit dan pemrosesan transaksi serta tagihan, jasa pengiriman barang dan 

dokumen, agensi iklan dan pemasaran atau manajemen promosi. Kami 

memberikan informasi kepada perusahaan-perusahaan tersebut hal-hal yang 

mereka butuhkan untuk melakukan layanan mereka. Perusahaan-perusahaan ini 

dilarang untuk menyalahgunakan data-data yang kami berikan selain dengan 

layanan yang berkaitan dengan KLN, dan mereka tidak diperkenankan membagi 

atau menjual kembali data ini, menggunakan informasi pribadi Anda untuk tujuan 

bisnis mereka sendiri, kecuali Anda secara eksplisit menyetujui penggunaan 

informasi pribadi Anda dengan cara ini. </li>
</ol>
<b>
KAPAN KLN MENGHUBUNGI ANDA?</b><br>

KLN mungkin akan menghubungi Anda:
<ol> 

<li>Dalam kaitannya dengan konten layanan, kegiatan atau konten online yang telah 

Anda daftar untuk memastikan bahwa KLN dapat memberikan layanan kepada 

Anda, saat Anda telah memilih untuk menerima korespondensi lebih lanjut; </li>

<li>Dalam kaitannya dengan kontribusi apapun yang telah Anda kirimkan kepada KLN, 

misalnya pada message boards KLN atau melalui teks atau pesan suara;</li> 

<li>Untuk mengundang Anda ikut berpartisipasi dalam survei tentang layanan KLN 

(bersifat sukarela) </li>

<li>Untuk tujuan pemasaran di mana Anda secara khusus telah menyetujui hal ini.

Halaman lokal akan memberikan informasi rinci mengenai bagaimana KLN akan 

menghubungi Anda terkait layanan tertentu, kegiatan atau konten online.</li>
</ol>

<b>APAKAH ANDA AKAN DIHUBUNGI UNTUK TUJUAN PEMASARAN?</b><br>

KLN tidak akan menghubungi Anda untuk tujuan pemasaran, atau mempromosikan 

layanan baru, kegiatan atau konten online untuk Anda, kecuali Anda secara khusus telah 

setuju untuk dihubungi sebelumnya.<br>

<b>PERIHAL KONTEN MENYINGGUNG ATAU TIDAK PATUT DI SITUS 

KLN</b><br>

Jika Anda memposting atau mengirim konten yang menyinggung, tidak patut atau tidak 

menyenangkan di mana saja pada/ke situs-situs KLN atau terlibat dalam perilaku yang 

mengganggu pada setiap layanan KLN, KLN mungkin akan menggunakan informasi 

pribadi Anda untuk menghentikan perilaku tersebut.<br>

Pada saat KLN cukup yakin bahwa Anda terbukti melakukan pelanggaran terhadap hukum 

yang berlaku di Indonesia (misalnya konten bermuatan fitnah yang Anda posting), KLN 

dapat menggunakan informasi pribadi Anda untuk menginformasikan kepada pihak ketiga 

yang relevan seperti kantor tempat anda bekerja, sekolah, penyedia layanan email/internet 

atau lembaga penegak hukum untuk konten dan perilaku Anda pada situs web kami.<br>

<b>BAGAIMANA JIKA ANDA PENGGUNA BERUSIA 16 TAHUN KE 

BAWAH?</b><br>

Jika Anda berusia 16 ke bawah, kami membutuhkan izin orang tua/wali sebelum Anda 

memberikan informasi pribadi apapun kepada KLN. Tanpa persetujuan ini pengguna tidak 

diperbolehkan untuk memberikan informasi pribadi kepada kami.<br>

<b>BERAPA LAMA KLN MENYIMPAN INFORMASI PRIBADI ANDA?</b><br>

Kami akan menyimpan informasi pribadi Anda pada sistem kami selama diperlukan untuk 

aktivitas yang relevan, atau selama yang ditetapkan dalam setiap kontrak yang relevan 

sesuai kesepakatan antara Anda dengan KLN atau menurut retensi jadwal perusahaan 

berdasarkan periode simpan database KLN.<br>

Jika Anda membatalkan pendaftaran sebagai anggota situs KLN, akun Anda dihapus dan 

bendera merah akan menandai akun Anda di database kami, dan pada saat itu KLN tidak 

dapat menggunakan informasi pribadi Anda.<br>

Pada saat Anda memberikan kontribusi materi kepada KLN, kami hanya akan menjaga 

konten Anda selama selama diperlukan. Sebagai contoh, kami hanya akan menyimpan 

salinan dari konten untuk sebuah kompetisi fotografi selama kompetisi berlangsung. 

Namun konten lain seperti fitur-fitur (artikel) berseri cenderung memiliki durasi panjang 

atau bahkan permanen.<br>

<b>DAPATKAH ANDA MENCARI TAHU INFORMASI PRIBADI YANG 

ADA DI KLN MENGENAI ANDA?</b><br>

Menurut Undang-Undang Perlindungan Data, Anda memiliki hak untuk meminta salinan 

informasi pribadi mengenai Anda yang disimpan KLN, termasuk data yang tidak dikoreksi 

secara akurat.<br>

Kami akan berupaya sewajarnya untuk menyediakan data yang Anda inginkan, termasuk 

memperbaiki atau menghapus informasi pribadi mengenai Anda pada file-file yang ada 

pada database kami.<br>
<b>

PERLINDUNGAN DAN KEAMANAN INFORMASI</b></br>

Keamanan Data: Untuk mencegah akses data oleh pihak yang tidak memiliki wewenang, 

menjaga keakuratan data dan memastikan penggunaan informasi yang semestinya, kami 

menggunakan prosedur fisik, elektronik dan manajerial untuk melindungi informasi yang 

kami kumpulkan secara online.<br><b>

OPSI TIDAK IKUT SERTA DALAM TARGETING IKLAN</b><br>

Anda dapat memilih untuk tidak ikut serta dalam targeting Iklan melalui Pengaturan Iklan. 

Ketika Anda meninggalkan sebuah situs, Anda masih akan melihat iklan tetapi mungkin 

tidak berkaitan dengan faktor-faktor seperti kepentingan Anda, kunjungan sebelumnya ke 

situs lain, atau rincian demografis.<br>

Opsi ini akan berlaku untuk iklan di seluruh website yang merupakan bagian dari 

KapanLagi Network (KLN)

Bagaimana mengaktifkan Opsi Tidak Ikut Serta dalam Targeting Iklan?

Anda dapat melakukannya setelah iklan yang ditampilkan kepada Anda berdasarkan 

faktor-faktor sesuai dengan keinginan atau minat Anda, kunjungan sebelumnya ke situs 

lain, dan rincian demografis pada browser komputer Anda, 
<ol>

<li>Ke Ads Setting di www.google.com/settings/ads </li>

<li>Di bawah "Google Ads Across the Web" klik link "Opt Out" </li>

<li>Pada dialog yang terbuka, klik tombol Opt Out</li>
</ol>

Apa yang tidak bisa diterapkan setelah Opsi Keluar dari Keikutsertaan Targeting Iklan 

diaktifkan?<br>

Ada beberapa hal yang tidak bisa diterapkan, berikut adalah beberapa kondisi yang paling 

umum dan yang dapat Anda lakukan untuk mengatasinya:
<ol> 

<li>Menghentikan iklan Iklan sangat penting untuk menguntungkan banyak situs. 

Ketika Anda Opsi ini diaktifkan, Anda masih akan melihat iklan dari Kapanlagi 

Network, tetapi iklan iini mereka tidak hanya berdasarkan keinginan atau minat 

Anda, kunjungan Anda dari website lain atau demografis. </li>

<li>Menonaktifkan Advertiser lain, berdasarkan iklan Opsi ini tidak menghentikan iklan 

yang tidak dilayani oleh Kapanlagi Network. Maka, ketika Anda menjelajahi internet 

dan melihat situs website, video, atau aplikasi yang di luar Kapanlagi Network, 

Anda masih dapat melihat iklan dari Advertiser lain. </li>

<li>Opsi ini terapkan di beberapa browser atau komputer sekaligus Apakah Anda 

menggunakan browser yang berbeda pada komputer Anda? Bahkan jika Anda 

menyisihkan iklan dari Kapanlagi Network pada satu browser, Anda masih dapat 

melihat iklan dari Kapanlagi Network pada browser lainnya (seperti Internet 

Explorer dan Safari). Hal yang sama berlaku jika Anda menggunakan beberapa 

komputer atau perangkat.<br>

Yang harus Anda lakukan adalah menerapkan Opsi ini ke semua browser dan 

perangkat yang ada gunakan </li>

<li>Menyimpan Opsi ini setelah Anda menghapus Cookies di browser Anda Apakah 

Anda menghapus cache dan cookie browser Anda? Jika Anda sudah 

membersihkan cookies Anda setelah menerapkan Opsi ini, kemungkin Opsi ini 

telah dibatalkan di browser Anda.</li>
</ol>

<b>
KEPATUHAN PADA PROSES HUKUM
</b><br>
Kami dapat menyampaikan informasi pribadi jika diperintahkan oleh hukum atau percaya 

bahwa langkah tersebut adalah perlu dilakukan untuk (1) patuh pada hukum atau proses 

pengadilan; (2) melindungi dan mempertahankan hak cipta dan hak milik kami; (3) 

melindungi terhadap penyalahgunaan atau penggunaan tanpa ijin dari situs web kami; 

atau (4) melindungi keamanan pribadi atau properti atas pengguna kami atau publik (di 

antara hal lainnya, hal ini berarti jika Anda memberikan informasi palsu atau berpura-pura 

menjadi orang lain, informasi mengenai diri Anda dapat kami sampaikan sebagai bagian 

dari penyelidikan atas tindakan Anda).
<br><br>
<b>PERUBAHAN PRIVACY POLICY</b>
<br>
Privacy Policy ini dapat diubah atau ditambah sewaktu-waktu, sehingga Anda mungkin 

ingin memeriksa setiap kali Anda mengirimkan informasi pribadi kepada KLN. Setiap 

perubahan akan diinfokan dengan jelas di website.

Jika kami melakukan perubahan yang sangat signifikan atau perubahan materi pada cara 

kami menggunakan data pribadi Anda, perubahannya akan ditampilkan setidaknya tiga 

puluh (30) hari sebelum diberlakukan dan pengguna yang telah terdaftar akan 

diberitahukan melalui e-mail.

Tanggal revisi terbaru akan muncul di halaman situs KLN. Jika Anda tidak setuju dengan 

perubahan ini, disarankan untuk berhenti menggunakan situs KLN untuk mengirimkan 

informasi pribadi.	
	<!-- privacy -->
	</div>
</div>