
<div class="author-read clearfix">
    <span><img src="<?= $this->config['assets_image_url'] ?>brilio-logo-100.png"></span>
    <span>+</span>
    <span>
    	<a href="<?= !empty($brand['brand_url']) ? $brand['brand_url'] : $brand['tag_brand_url'] ?>" target="_blank" onclick="ga('send', 'event', '<?= $TE ?>', 'Logo brand', '<?= !empty($brand['brand_url']) ? $brand['brand_url'] : $brand['tag_brand_url'] ?>');" >
    		<img style='max-height:65px ; max-width:120px' src="<?= $brand['brand_image'] ?>">
    	</a>
    </span>
</div>
