<div class="article-col-right">
<div class="share-story" id="subs">
    <h6>MASIH PILIH-PILIH CERITA?</h6>
    <p>Biarkan Brilio yang rekomendasikan & mengirim cerita terbaik untukmu!</p>
    <div id="box-emailSuccess" style="display: none;">
    	<p><h6>Terima Kasih!</h6>Email kamu telah suskses terdaftar.</p>
    </div>
    <div id="box-form-email" style="display: none">
    <p id="emailError" style="color:red" ></p>
	    <form action="<?= $this->config['base_url'].'save_collect_email/'?>" method="POST" id="email-form">
	        <div class="input-group input-share">
	            <span class="input-group-addon"><img src="<?= $this->config['assets_image_url_v2']?>email-icon.png"></span>
	            <input type="text" class="form-control" name="emailsubscribe" id="txtEmail" placeholder="Isikan email kamu di sini">
	        </div>
	        <button type="submit" class="btn btn-share">Setuju, kirim ke saya</button>
	    </form>
    </div>
</div>
</div>
<!-- <script language="javascript">
		$(document).ready(function (){

			if (document.cookie.indexOf(document.domain + "desktop_email_subscribe") >= 0) {
					$("#box-emailSuccess").show();
					$("#box-form-email").hide();

      }
      else
      {
      		$("#box-form-email").show();
	      	$('#subs').on('submit', function (event){
					var email = document.getElementById('txtEmail');
					var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
					event.preventDefault();
					if (!filter.test(email.value))
					{
							document.getElementById('emailError').innerHTML = 'Please insert your valid email address';
					}
					else
					{
							$.ajax({
								url : $('#email-form').attr('action'),
								method : 'POST',
								data : $('#email-form').serialize(),

							}).done(function(data){
								if (data.trim() == 'taken')
									document.getElementById('emailError').innerHTML = 'Sorry, email already in use.';
								if (data.trim() == 'success'){
									var date, expires;
						            var value = document.domain + "desktop_email_subscribe";
						            date = new Date();
						            date.setTime(date.getTime()+(30 * 24 * 60 * 60 * 1000));
						            expires = "; expires="+date.toGMTString();
						            document.cookie = "brilionet="+value+expires+"; path=/";
									$("#box-emailSuccess").show();
									$("#box-form-email").hide();
								}
							}).fail(function(jqXHR, textStatus, errorThrown){
								if (jqXHR.status == 444)
									sessionExpireHandler();
								else
									console.log(errorThrown);
							});
						}
					});

      }

		});

	</script> -->
