<div class="tag-section">
    <div class="container">
        <ul class="list-tag list-unstyled clearfix">
            <li><a href="<?= $this->config['rel_url'] ?>popular/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Popular');" >POPULAR</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>news/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'News');" >NEWS</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>life/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Life');" >LIFE</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>ngakak/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Ngakak!');" >NGAKAK!</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>selebritis/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Selebritis');" >SELEBRITIS</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>sosok/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Sosok');" >SOSOK</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>komunitas/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Komunitas');" >KOMUNITAS</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>jorok/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Jorok!');" >JOROK!</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>global/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Global');" >GLOBAL</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>duh/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Duh!');" >DUH!</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>binatang/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Binatang');" >BINATANG</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>cinta/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Cinta');" >CINTA</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>gadget/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Gadget');" >GADGET</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>wow/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Wow!');" >WOW!</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>kesehatan/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Kesehatan');" >KESEHATAN</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>olahraga/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Olahraga');" >OLAHRAGA</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>serem/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Serem');" >SEREM</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>cewek/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Cewek');" >CEWEK</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>cowok/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Cowok');" >COWOK</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>jalan-jalan/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Jalan-jalan');" >JALAN-JALAN</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>politik/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Politik');" >POLITIK</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>ekonomi/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Ekonomi');" >EKONOMI</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>fashion/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Fashion');" >FASHION</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>orangtua/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Orang tua');" >ORANG TUA</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>musik/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Musik');" >MUSIK</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>ilmiah/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Ilmiah');" >ILMIAH</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>serius/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Serius');" >SERIUS</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>kepribadian/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Kepribadian');" >KEPRIBADIAN</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>sosialita/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Sosialita');" >SOSIALITA</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>rumah/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Rumah');" >RUMAH</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>film/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Film');" >FILM</a></li>
            <li><a href="<?= $this->config['rel_url'] ?>kuliner/" onclick="ga('send', 'event', '<?= $TE ?>', 'Category', 'Kuliner');" >KULINER</a></li>
        </ul>
    </div>
</div>