<!-- <div class="brilio-header-billboard clearfix">
        <div class="brilio-header-billboard-wording-gateway" style="padding-top:8px; padding-bottom:10px;">

            <a href="http://m.brilio.net/storytelling/" onclick="ga('send', 'event', 'All pages - Gateway story telling', 'Click', 'gateway story telling');" target="_blank">
                Everyone has Untold Stories. Share your story here +62-800-1-555-999.
            </a>
        </div>
</div> -->
