<?php
$no = 1;
foreach ($list_tags_top as $key):
    if($no == 1)
    {
        ?>
        <li><a href="<?= $key['TAG_URL'] ?>" onclick="ga('send', 'event', '<?php echo $key['TE'] ?> - Today tag bar', 'Click', 'Ramalan Shio 2016')"><?= $key['TAG_TITLE'] ?></a></li>
        <?php
    }
    else
    {
        ?>
        <li><a href="<?= $key['TAG_URL'] ?>" onclick="ga('send', 'event', 'Menu - Today tag', 'Click', '<?= $key['TAG_TITLE'] ?>');"><?= $key['TAG_TITLE'] ?></a></li>
        <?php
    }
    ?>

<?php
    $no++;
endforeach; ?>
