    <link href='http://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
    <link href='/brilionet/m/assets/css/collect.css' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="/brilionet/m/assets/js/collect.js"></script>
    <!--collect-email-->
    <div class="collect-email" id="collect-start">
        <div id="data"></div>
        <a href="javascript:void(0)" class="close-collect"><img src="/brilionet/m/assets/img/close.png" width="16" /></a>
        <div class="section-collect">
            <h6 class="title-collect">MASIH PILIH-PILIH CERITA?</h6>
            <p class="text-collect">Biarkan Brilio yang rekomendasikan & mengirim cerita terbaik untukmu!</p>
            <form class="form-collect-email" method="post" name="form" action="">
                <input type="text" class="form-collect" id="email" placeholder="Isi email kamu di sini" />
                <button type="submit" class="btn-collect" id="btn_collect">Setuju, kirimkan ke saya</button>
                <div class="btn-no">
                    <a href="javascript:void(0)" class="btn-collect-no">Nanti saja, ingatkan saya besok</a>
                </div>
            </form>
        </div>
    </div>
    <!--end collect email-->
    <div id="flash"></div>
    <div id="display"></div>
    <!--collect-email-->
    <div class="collect-email" id="collect-done">
    <a href="javascript:void(0)" class="close-collect-done"><img src="/brilionet/m/assets/img/close.png" width="16" /></a>
        <div class="section-collect">
            <h6 class="title-collect">Terima Kasih!</h6>
            <p class="text-collect">Proses berhasil, email kamu sudah sukses terdaftar</p>
        </div>
    </div>
    <!--end collect email-->