<?php if(!empty($code)): ?>

<div style="clear:both;">
        <div class="title-bg">
                Tahu Nggak Sih Panjang Mie Instan Yang Biasanya Kamu Makan?
        </div>
        <amp-iframe width="480" 
                height="270" 
                src="https://www.youtube.com/embed/<?php echo $code ?>" 
                frameborder="0" 
                sandbox="allow-scripts allow-same-origin allow-popups"
                layout="responsive"></amp-iframe>
        <div class="share-video">
            <h5 class="share-text">BRILIO VIDEO</h5>
            <div class="yt-share">
                <div class="g-ytsubscribe" data-channelid="UCjRH2OCntkHDJi0kIX3DZ3w" data-layout="default" data-count="default"></div>
            </div>
        </div>
        <div class="deskrip-video">
            Tahu Nggak Sih Panjang Mie Instan Yang Biasanya Kamu Makan?<br/><br/>
           Kebayang Berapa Panjangnya Kok Bisa Masuk Perut Kamu? Simak Videonya...
        </div>
</div>
<hr />
<?php endif; ?>