<div class="bottom-tags">
    <div class="bottom-tags-title">
        <div class="bottom-tags-title-line"></div>
        <div class="bottom-tags-title-name">Today Tags</div>
    </div>
    <div class="bootom-tags-list">
        <ul>
        <?php
        $no = 1;
        foreach ($list_tags_bottom as $key): 
            if($no == 1) {
                ?>
                    <li><a href="<?= $key['TAG_URL'] ?>" ><?= $key['TAG_TITLE'] ?></a></li>
                <?php
            }
            else {
                ?>
                    <li><a href="<?= $key['TAG_URL'] ?>" ><?= $key['TAG_TITLE'] ?></a></li>    
                <?php
            }
            ?>
        
        <?php $no++; endforeach; ?>
        </ul>
    </div>
</div>
